digitalocean/terraform-provider-digitalocean

digitalocean/import_digitalocean_firewall_test.go, digitalocean/provider.go, digitalocean/resource_digitalocean_firewall.go, digitalocean/resource_digitalocean_firewall_test.go, website/digitalocean.erb, website/docs/r/firewall.html.markdown
https://www.digitalocean.com/products/cloud-firewalls/
https://blog.digitalocean.com/cloud-firewalls-secure-droplets-by-default/
https://github.com/digitalocean/godo/commit/4fa9e9d999007b447089056a1c581b5594f0f851
```
air$ go test -v -run TestAccDigitalOceanFirewall
=== RUN   TestAccDigitalOceanFirewall_importBasic
=== RUN   TestAccDigitalOceanFirewall_importBasic/only_allow_inbound_SSH(TCP/22)
=== RUN   TestAccDigitalOceanFirewall_importBasic/only_allow_outbound_SSH(TCP/22)
=== RUN   TestAccDigitalOceanFirewall_importBasic/only_allow_inbound_SSH(TCP/22)_and_HTTP(TCP/80)
=== RUN   TestAccDigitalOceanFirewall_importBasic/only_allow_outbound_SSH(TCP/22)_and_DNS(UDP/53)
=== RUN   TestAccDigitalOceanFirewall_importBasic/allow_inbound_and_outbound_HTTPS(TCP/443),_inbound_SSH(TCP/22),_and_outbou …
```
=> resource_digitalocean_firewall.go: Add DO Cloud Firewalls (#15124)

website/docs/r/firewall.html.markdown, website/docs/r/volume.markdown
this PR improves the volume and firewall documentation
=> docs: add undocumented attribute to volume, update firewall docs

digitalocean/resource_digitalocean_droplet.go
fixes: https://github.com/terraform-providers/terraform-provider-digitalocean/issues/19
1) made waitForDropletAttribute private
2) renamed resize_disk to resizeDisk
3) Added a new private helper function: detachVolumeIDOnDroplet
=> detaching the disks before deleting a droplet

vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/account.go, vendor/github.com/digitalocean/godo/action.go, vendor/github.com/digitalocean/godo/certificates.go, vendor/github.com/digitalocean/godo/domains.go, vendor/github.com/digitalocean/godo/droplet_actions.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/firewalls.go, vendor/github.com/digitalocean/godo/floating_ips.go, vendor/github.com/digitalocean/godo/floating_ips_actions.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/image_actions.go, vendor/github.com/digitalocean/godo/images.go, vendor/github.com/digitalocean/godo/keys.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/github.com/digitalocean/godo/regions.go, vendor/github.com/digitalocean/godo/sizes.go, vendor/github.com/digitalocean/godo/snapshots.go, vendor/github.com/digitalocean/godo/storage.go, vendor/github.com/digitalocean/godo/storage_actions.go, vendor/github.com/digitalocean/godo/tags.go, vendor/vendor.json
Pulls in changes from digitalocean/godo#151
=> vendor: github.com/digitalocean/godo/...@v1.1.1

website/docs/r/ssh_key.html.markdown
As spotted by @discentem in hashicorp/terraform-website#92
=> `r/ssh_key` - fixing the grammar

website/docs/r/droplet.html.markdown
Hi
I wanted to suggest a small change.
I spent 30 minutes hunting down this info and thought this could help someone with a google-fu as bad as mine :)
Cheers.
=> Add link to available Droplet size list.

digitalocean/import_digitalocean_record_test.go, digitalocean/resource_digitalocean_record.go, website/docs/r/record.html.markdown
This builds on the work by @slapula in #71.
=> Add ability to import digitalocean_record resources

digitalocean/datasource_digitalocean_domain.go, digitalocean/datasource_digitalocean_domain_test.go, digitalocean/provider.go, website/digitalocean.erb, website/docs/d/domain.html.md
Builds on work by @slapula in #63
=> Add digitalocean_domain data source

digitalocean/datasource_digitalocean_record.go, digitalocean/datasource_digitalocean_record_test.go, digitalocean/provider.go, website/digitalocean.erb, website/docs/d/record.html.md
Builds on work from @slapula in #64
=> Adds digitalocean_record datasource

digitalocean/resource_digitalocean_tag.go, digitalocean/resource_digitalocean_tag_test.go
Builds on work by @inkel in #80
=> Validate tag name at time of creation

digitalocean/resource_digitalocean_floating_ip.go, digitalocean/resource_digitalocean_floating_ip_test.go
Build on @aknuds1's work in #57
=> Handle denial to unassign floating IP from already deleted Droplet

digitalocean/resource_digitalocean_floating_ip.go
When trying to unassign a floating IP, the DigitalOcean API may return a status code 422 meaning that the request was denied. In my experience this can happen because the droplet in question has been deleted. I make the change here to handle these failures gracefully, as it shouldn't abort Terraform.
I've verified through manual testing that this change solves the issue I was experiencing, i.e. that during `terraform destroy`, the floating IP deletion would abort the whole process since it couldn't be unassigned from the droplet that was deleted prior.
I would appreciate if someone explained to me how to write a test for this case :)
=> Handle denial to unassign floating IP from droplet

digitalocean/resource_digitalocean_volume.go, digitalocean/resource_digitalocean_volume_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/README.md, vendor/github.com/digitalocean/godo/account.go, vendor/github.com/digitalocean/godo/action.go, vendor/github.com/digitalocean/godo/certificates.go, vendor/github.com/digitalocean/godo/domains.go, vendor/github.com/digitalocean/godo/droplet_actions.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/firewalls.go, vendor/github.com/digitalocean/godo/floating_ips.go, vendor/github.com/digitalocean/godo/floating_ips_actions.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/image_actions.go, vendor/github.com/digitalocean/godo/images.go, vendor/github.com/digitalocean/godo/keys.go, vendor/github.com/digitalocean/godo/links.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/github.com/digitalocean/godo/regions.go, vendor/github.com/digitalocean/godo/sizes.go, vendor/github.com/digitalocean/godo/snapshots.go, vendor/github.com/digitalocean/godo/storage.go, vendor/github.com/digitalocean/godo/storage_actions.go, vendor/github.com/digitalocean/godo/tags.go, vendor/vendor.json, website/docs/r/volume.markdown
Added support for filesystem_type flag for volumes, related to issue: https://github.com/terraform-providers/terraform-provider-digitalocean/issues/103
Required upgrading godo dependency to version that supports this flag.
=> Add support for filesystem_type parameter for volume resource

digitalocean/resource_digitalocean_domain.go, digitalocean/resource_digitalocean_domain_test.go, website/docs/r/domain.html.markdown
=> Added the ability to create a domain without specifying the initial IP address

digitalocean/resource_digitalocean_record.go, digitalocean/resource_digitalocean_record_test.go, website/docs/r/record.html.markdown
Added missing functionality and fixed irregularities in the `digitalocean_record` resource and added basic validation to the schema properties.
Fixes #58 , #62 and #6
=> Added missing functionality/configuration to the `digitalocean_record` resource

digitalocean/resource_digitalocean_volume.go, digitalocean/resource_digitalocean_volume_test.go, website/docs/r/volume.markdown
Increasing the volumes size will now correctly expand the volume and not recreate it. 
Resolves #82
=> Added support for volume resizing

digitalocean/loadbalancer.go, digitalocean/resource_digitalocean_loadbalancer.go, website/docs/r/loadbalancer.html.markdown
Added some critical validation to the load balancer properties. In addition, updated the documentation on how to support in-place load balancer certificate renewals and updates with the same existing resources.
=> Added validations with minor optimizations to the load balancer resource

digitalocean/datasource_digitalocean_image.go
=> Handle pagination in digitalocean_image data source.

digitalocean/resource_digitalocean_certificate.go, website/docs/r/certificate.html.markdown
=> Added support for LetsEncrypt issued certificates

digitalocean/resource_digitalocean_firewall.go, digitalocean/resource_digitalocean_firewall_test.go, website/docs/r/firewall.html.markdown
The resource should be completely backward compatible with existing state files. 
Resolves #30
=> Refactored the firewall resource for better stability of diffs and updates

digitalocean/resource_digitalocean_loadbalancer_test.go
The PR adds additional tests for the load balancer resources to cover the default values for the `healthcheck` and `sticky_sessions` block.
=> Added additional tests for the load balancer resource

digitalocean/resource_digitalocean_record.go, digitalocean/resource_digitalocean_record_test.go
=> Fixed the function for generating a records FQDN to match DO API behaviour

digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_droplet_test.go
This PR includes minor fixes to ensure all the acceptance tests pass.
=> Ensure tests are consistent with the current status of the resources/datasources

digitalocean/resource_digitalocean_floating_ip_assignment.go, digitalocean/resource_digitalocean_floating_ip_assignment_test.go
This PR resolves an issue (#147) with using the `create_before_destroy` lifecycle rule with the new `floating_ip_assignment` resource.
What is currently occurring:
1. After the new Droplet is created, the Floating IP is reassigned by creating a new "virtual" attachment resource.
2. The old deposed attachment resource is deleted causing the Floating IP to be unassigned. Since this is the same FIP that was already re-assigned, we are left in a tainted state where the new attachment resource exists but the FIP is not actually assigned to the new Droplet.
This PR changes this behavior by re-reading the deposed attachment resource before unassigning the Floating IP. If the old Droplet ID is no longer found, it marks the attachment resource as destroyed.
=> Ensure floating_ip_assignment works with create_before_destroy (Fixes #147).

website/docs/r/droplet.html.markdown
The link for api docs on DO has been changed, update link to reflect that.
=> Update dead link

website/docs/d/kubernetes_cluster.html.md, website/docs/r/kubernetes_cluster.html.markdown, website/docs/r/kubernetes_node_pool.html.markdown
After feedback from the Terraform team I have updated the docs, currently, we have no concept for a Beta resource so the documentation for the K8s Cluster resources has been updated to remove this.
=> Updated documentation after feedback from Terraform team

digitalocean/config.go
This should be practically no-op change as even the logging format is the same. Using http Transport is however more common way of logging requests and responses which is compatible with most SDKs so I'm merely aligning this to match what we have elsewhere.
=> provider: Refactor logic for logging API requests/responses

website/docs/d/kubernetes_cluster.html.md, website/docs/r/kubernetes_cluster.html.markdown, website/docs/r/kubernetes_node_pool.html.markdown
=> fix typo: remove extra word

digitalocean/datasource_digitalocean_droplet_snapshot.go, digitalocean/datasource_digitalocean_volume.go, digitalocean/datasource_digitalocean_volume_snapshot.go, digitalocean/resource_digitalocean_floating_ip.go, digitalocean/resource_digitalocean_loadbalancer.go, digitalocean/resource_digitalocean_spaces_bucket.go, digitalocean/resource_digitalocean_volume.go
=> Normalize case for region attribute across all resources

digitalocean/datasource_digitalocean_floating_ip.go, digitalocean/datasource_digitalocean_floating_ip_test.go, digitalocean/resource_digitalocean_floating_ip.go, digitalocean/resource_digitalocean_floating_ip_test.go, website/docs/d/floating_ip.html.md, website/docs/r/floating_ip.html.markdown
This PR introduces the URN attribute for the Floating ip resource.  This covers the datasource and the resource.  Alterations also include the website to document the new attribute.
=> Updates the floating ip resource to expose the urn.

digitalocean/resource_digitalocean_droplet.go
Fixes #152 
The provider does not try to detect drift to a droplet image remotely, as this operation either can happen without rebuilding the image, in that case, the drift will be captured by the imageId.
Image remote image drift appears when the slug is promoted to a new patch image.
=> Avoid drift when remote slug is updated

README.md
Noticed a small typo in the read me. Figured I would just fix it!
=> ReadMe Typo

digitalocean/datasource_digitalocean_database_cluster.go, digitalocean/datasource_digitalocean_database_cluster_test.go, digitalocean/provider.go, website/digitalocean.erb, website/docs/d/database_cluster.html.markdown
Fixes: #236
```
▶ acctests digitalocean TestAccDataSourceDigitalOceanDatabaseCluster_Basic
=== RUN   TestAccDataSourceDigitalOceanDatabaseCluster_Basic
--- PASS: TestAccDataSourceDigitalOceanDatabaseCluster_Basic (343.56s)
PASS
ok  	github.com/terraform-providers/terraform-provider-digitalocean/digitalocean	343.609s
```
=> datasource: New Database Cluster Datasource

digitalocean/datasource_digitalocean_droplet.go, digitalocean/datasource_digitalocean_droplet_test.go, digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_droplet_test.go
=> Adds created_at attribute for droplets

digitalocean/import_digitalocean_database_replica_test.go, digitalocean/provider.go, digitalocean/resource_digitalocean_database_replica.go, digitalocean/resource_digitalocean_database_replica_test.go, website/docs/r/database_replica.html.markdown
Fixes #224 
Added DatabaseReplica resource support + tests
=> Added DatabaseReplica resource support

website/docs/r/kubernetes_cluster.html.markdown
=> Document using doctl to grab k8s versions

website/docs/d/kubernetes_cluster.html.md, website/docs/r/kubernetes_cluster.html.markdown
=> Update Kubernetes examples to use tokens over certs.

website/docs/d/database_cluster.html.markdown, website/docs/d/domain.html.md, website/docs/d/droplet.html.md, website/docs/d/floating_ip.html.md, website/docs/d/image.html.md, website/docs/d/loadbalancer.html.md, website/docs/d/record.html.md, website/docs/d/ssh_key.html.md, website/docs/d/tag.html.md, website/docs/d/volume.html.md, website/docs/d/volume_snapshot.html.md, website/docs/r/cdn.html.markdown, website/docs/r/certificate.html.markdown, website/docs/r/domain.html.markdown, website/docs/r/droplet_snapshot.html.markdown, website/docs/r/firewall.html.markdown, website/docs/r/floating_ip.html.markdown, website/docs/r/floating_ip_assignment.html.markdown, website/docs/r/kubernetes_cluster.html.markdown, website/docs/r/kubernetes_node_pool.html.markdown, website/docs/r/loadbalancer.html.markdown, website/docs/r/project.html.markdown, website/docs/r/record.html.markdown, website/docs/r/spaces_bucket.html.markdown, website/docs/r/ssh_key.html.markdown, website/docs/r/tag.html.markdown, website/docs/r/volume.html.markdown, website/docs/r/volume_attachment.html.markdown, website/docs/r/volume_snapshot.html.markdown
Previously, I had been a bit reluctant to update the docs to v0.12 syntax through out considering that earlier versions are still in use, but it's probably time to do this.
=> Update the documentation to v0.12 syntax (Fixes: #274).

digitalocean/resource_digitalocean_spaces_bucket.go, digitalocean/resource_digitalocean_spaces_bucket_test.go, website/docs/r/spaces_bucket.html.markdown
fixes #254 
note that `expose_headers` in the original AWS api is left out since it does not appear to be in the DO documentation
=> add support for spaces CORS

website/docs/r/project.html.markdown
Also adds Database Clusters as a supported type and alphabetizes the list.
=> Update project docs to include import example.

digitalocean/resource_digitalocean_kubernetes_cluster.go
Small fix to the comment around the default node pool tag
=> Fix default node pool tag comment

digitalocean/resource_digitalocean_project.go, digitalocean/resource_digitalocean_project_test.go
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanProject_WithManyResources'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanProject_WithManyResources -timeout 120m
=== RUN   TestAccDigitalOceanProject_WithManyResources
--- PASS: TestAccDigitalOceanProject_WithManyResources (27.91s)
PASS
ok  	github.com/terraform-providers/terraform-provider-digitalocean/digitalocean	27.934s
```
=> Handle pagination for project resources (Fixes: #368).

digitalocean/spaces_buckets.go
As it turns out, I didn't actually push this in https://github.com/terraform-providers/terraform-provider-digitalocean/pull/416 after commenting there that I was about too. Doh!
=> add comment why spaces regions are hard-coded in data source

digitalocean/spaces_buckets.go
Remove an extraneous debugging statement that I left in `digitalocean/spaces_buckets.go`.
=> remove extra debug logging statement

digitalocean/resource_digitalocean_kubernetes_cluster.go
https://github.com/terraform-providers/terraform-provider-digitalocean/issues/443
=> Add forcenew to vpc_uuid field of kubernetes cluster resource

website/docs/d/droplet.html.md
Found this mixup while reading the docs
=> Switch 2 words

digitalocean/app_spec.go, digitalocean/datasource_digitalocean_app.go, digitalocean/datasource_digitalocean_app_test.go, digitalocean/import_digitalocean_app_test.go, digitalocean/provider.go, digitalocean/resource_digitalocean_app.go, digitalocean/resource_digitalocean_app_test.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/modules.txt, website/digitalocean.erb, website/docs/d/app.html.md, website/docs/r/app.html.markdown
This PR adds initial support for App Platform.
https://www.digitalocean.com/docs/app-platform/resources/app-specification-reference/
https://godoc.org/github.com/digitalocean/godo#AppsService
=> Add support for App Platform

digitalocean/resource_digitalocean_app.go, digitalocean/resource_digitalocean_cdn.go
=> Fix panics introduced in move from ReadFunc to ReadContextFunc

digitalocean/resource_digitalocean_spaces_bucket.go
As we immediately apply additional configuration after creating the bucket,
we should first ensure that the bucket is available before leaving the create
method in order to protect against instability like seen in #510.
Closes: #510
=> spaces_bucket: Add retry logic to ensure bucket is available before proceeding

docs/data-sources/container_registry.md, docs/resources/container_registry.md
Closes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/522
=> registry: Update docs w/ subscription_tier_slug

digitalocean/resource_digitalocean_kubernetes_node_pool.go, docs/resources/kubernetes_node_pool.md, examples/kubernetes/main.tf
Closes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/436
=> k8s: Validate min_nodes is at least 1 and fix example.

docs/data-sources/app.md, docs/resources/app.md
Closes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/507
=> apps: Document the database spec.

digitalocean/provider.go, digitalocean/resource_digitalocean_image.go, digitalocean/resource_digitalocean_image_test.go, docs/resources/custom_image.md
Signed-off-by: Noel Georgi <git@frezbo.com>
Fixes #160
Good to Have:
- The `Update` operation currently only updates the name since the `godo` client only supports that at the moment
- Copying to multiple regions is not supported yet
=> Feature: digitalocean_image

docs/resources/custom_image.md
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/526
=> Expand digitalocean_custom_image docs.

digitalocean/datasource_digitalocean_loadbalancer.go, digitalocean/datasource_digitalocean_loadbalancer_test.go, digitalocean/resource_digitalocean_loadbalancer.go, digitalocean/resource_digitalocean_loadbalancer_test.go, docs/resources/loadbalancer.md
=> load balancers: add support for new size field

digitalocean/app_spec.go, digitalocean/resource_digitalocean_app_test.go
I extracted the `image` attribute thing from #544, and added acceptance tests which are still running so not sure they pass, this might still not be fully ready, but hey, figure I'd try.
=> Image attribute

digitalocean/app_spec.go, digitalocean/resource_digitalocean_app_test.go
I extracted the jobs attribute work from #544 and added some acceptance tests.
=> App jobs attribute

docs/data-sources/app.md, docs/resources/app.md
This documents the image source (#565), jobs component (#566),  domain changes (#572), and service internal ports (#570).
~Note: #570 has not yet been merged.~
=> App platform documentation updates

digitalocean/datasource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_database_cluster.go
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/576
=> dbaas: Protect against panic if connection details not available.

digitalocean/import_digitalocean_spaces_bucket_test.go, digitalocean/resource_digitalocean_spaces_bucket.go
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/627
=> digitalocean_spaces_bucket: Provide better error on malformated import.

README.md
=> Added note about dev_overrides

docs/resources/firewall.md
Corrects documentation of inbound and outbound rules exported attributes.
=> Fixes Firewall Resource exported attributes documentation to match actual.

CHANGELOG.md, docs/resources/database_cluster.md
https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/database_cluster#create-a-new-mongodb-database-cluster
=> Add code fence to docs for MongoDB. 🤦‍

digitalocean/resource_digitalocean_app.go, digitalocean/resource_digitalocean_cdn.go, digitalocean/resource_digitalocean_certificate.go, digitalocean/resource_digitalocean_container_registry.go, digitalocean/resource_digitalocean_container_registry_docker_credentials.go, digitalocean/resource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_domain.go, digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_droplet_snapshot.go, digitalocean/resource_digitalocean_firewall.go, digitalocean/resource_digitalocean_floating_ip.go, digitalocean/resource_digitalocean_floating_ip_assignment.go, digitalocean/resource_digitalocean_loadbalancer.go, digitalocean/resource_digitalocean_project.go, digitalocean/resource_digitalocean_record.go, digitalocean/resource_digitalocean_spaces_bucket.go, digitalocean/resource_digitalocean_ssh_key.go, digitalocean/resource_digitalocean_tag.go, digitalocean/resource_digitalocean_volume.go, digitalocean/resource_digitalocean_volume_attachment.go, digitalocean/resource_digitalocean_volume_snapshot.go, digitalocean/resource_digitalocean_vpc.go
All of them found with `staticcheck . | grep SA1019`
This is just a subset of API v2 deprecation updates.
=> Update to Context-aware API v2 functions

digitalocean/import_digitalocean_droplet_test.go, digitalocean/resource_digitalocean_droplet.go
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/674
=> Protect against panic when importing Droplet errors.

digitalocean/resource_digitalocean_app.go, digitalocean/resource_digitalocean_app_test.go, docs/resources/app.md, docs/resources/database_cluster.md, docs/resources/kubernetes_cluster.md, docs/resources/kubernetes_node_pool.md
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/628
=> apps: Make create timeout configurable (fixes: #628).

digitalocean/app_spec.go, digitalocean/resource_digitalocean_app_test.go, docs/resources/app.md
~Opening this as a draft for now as it still needs docs and more tests.~
Related to: https://github.com/digitalocean/terraform-provider-digitalocean/issues/686
=> apps: Support setting CORS policies.

digitalocean/resource_digitalocean_container_registry_docker_credentials.go, digitalocean/resource_digitalocean_container_registry_test.go
As the concept being used here is "destroying" the credentials, we should really revoke the generated token. 
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/726
=> docker creds: Revoke token on delete.

CHANGELOG.md
Following up on...  https://github.com/digitalocean/terraform-provider-digitalocean/pull/745
=> Fix version in changelog... 🤦

docs/resources/kubernetes_cluster.md
per #815
thanks for the catch @kylepeterdavies
=> Doc Update: Fix k8's node_pool.tags description

digitalocean/resource_digitalocean_kubernetes_cluster.go
version check does not depend on node_pool changes
=> kubernetes: always perform upgrade check. (#823)

digitalocean/datasource_digitalocean_app.go, digitalocean/datasource_digitalocean_app_test.go, digitalocean/resource_digitalocean_app.go, digitalocean/resource_digitalocean_app_test.go, docs/data-sources/app.md, docs/resources/app.md, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/balance.go, vendor/github.com/digitalocean/godo/billing_history.go, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/godo.go, vendor/modules.txt
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/853
=> apps: Add computed URN attribute.

digitalocean/datasource_digitalocean_loadbalancer.go, digitalocean/datasource_digitalocean_loadbalancer_test.go, digitalocean/resource_digitalocean_loadbalancer.go, digitalocean/resource_digitalocean_loadbalancer_test.go, docs/resources/loadbalancer.md, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/droplet_actions.go, vendor/github.com/digitalocean/godo/functions.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/image_actions.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/modules.txt
This fixes up some issues with the reverted PR https://github.com/digitalocean/terraform-provider-digitalocean/pull/897
CC: @StephenVarela
=> Load balancers: Support HTTP idle timeout & Project ID 

digitalocean/sweep/sweep_test.go, digitalocean/vpc/datasource_vpc_test.go, digitalocean/vpc/resource_vpc.go, digitalocean/vpc/sweep.go
Straight forward one. Just a sweeper. Already using the correct naming pattern.
=> Add sweeper for VPCs.

digitalocean/certificate/resource_certificate.go
Certificates can not be deleted while still attached to a load balancer. When a load balancer is deleted, it can take a moment for the certrifcates API to pick up this change. So this adds a retry for certificate deletes.
This resolves two load balancer test failures:
```
=== RUN   TestAccDataSourceDigitalOceanLoadBalancer_tlsCertByName
=== PAUSE TestAccDataSourceDigitalOceanLoadBalancer_tlsCertByName
=== RUN   TestAccDigitalOceanLoadbalancer_sslTermination
=== PAUSE TestAccDigitalOceanLoadbalancer_sslTermination
=== CONT  TestAccDataSourceDigitalOceanLoadBalancer_tlsCertByName
=== CONT  TestAccDigitalOceanLoadbalancer_sslTermination
--- PASS: TestAccDataSourceDigitalOceanLoadBalancer_tlsCertByName (121.28s)
--- PASS: TestAccDigitalOceanLoadbalancer_sslTermination (386.38s)
PASS
ok …
```
=> certificates: Add retry on delete.

digitalocean/database/datasource_database_cluster.go, digitalocean/database/datasource_database_cluster_test.go, digitalocean/database/resource_database_cluster.go, digitalocean/database/resource_database_cluster_test.go, docs/data-sources/database_cluster.md, docs/resources/database_cluster.md
Adds support for specifying a project ID for a database cluster.
=> databases: Support project assignment.

digitalocean/droplet/resource_droplet.go
When enabling IPv6 on a Droplet, you change the `ipv6` attribute and the `ipv6_address` is recomputed. If another resource (e.g. a `digitalocean_record`) is referencing the blank `ipv6_address` attribute, Terraform will find an "inconsistent plan" as Terraform does not understand that `ipv6_address` will be changing.
This is easy to reproduce, but difficult to model in an acceptance test as it requires a failure state.
Using the below config, create a domain and Droplet. Creating the record will fail with a 422 as `digitalocean_droplet.web.ipv6_address` computes to an empty string.
```hcl
resource "digitalocean_domain" "default" {
name       = "some-random-domain.com"
}
resource "digitalocean_record" "www" {
domain = digitalocean_domain.default.id
type   = "AAAA"
name   = "www"
value  = …
```
=> droplet: Prevent inconsistent plan when enabling IPv6.

CHANGELOG.md
We have a handful of bugfixes. Let's get a release out.
=> Prep v2.28.1 release.

digitalocean/database/datasource_database_user.go, digitalocean/database/datasource_database_user_test.go, digitalocean/provider.go, docs/data-sources/database_user.md
Adds a new data source for the database user.
=> databases: Add data source for database user.

CHANGELOG.md
~Draft pending https://github.com/digitalocean/terraform-provider-digitalocean/pull/1028 being merged~
=> Prep v2.30.0 release.

digitalocean/spaces/import_spaces_bucket_test.go, digitalocean/spaces/resource_spaces_bucket.go
=> spaces bucket: set force_destroy false on import.

digitalocean/database/resource_database_cluster_test.go, digitalocean/database/resource_database_mysql_config.go, digitalocean/database/resource_database_mysql_config_test.go, digitalocean/provider.go, docs/resources/database_mysql_config.md
=> Support MySQL database advanced configuration

CHANGELOG.md
Let get a release cut with these fixes!
=> Prep v2.34.0 release

digitalocean/uptime/resource_uptime_alert.go
=> uptime_alert: 1hr -> 1h

digitalocean/database/resource_database_redis_config.go, digitalocean/database/resource_database_redis_config_test.go
Fixes https://github.com/digitalocean/terraform-provider-digitalocean/issues/1106
=> redis config: allow setting timeout to 0

CHANGELOG.md
Just making the file aligned with previous format (or maybe we should change the previous format)
=> chore: fix header of changelog

digitalocean/app/app_spec.go, docs/resources/app.md
Terraform side of  https://github.com/digitalocean/godo/pull/704 and https://github.com/digitalocean/openapi/pull/896
=> apps: support additional database engines

digitalocean/app/app_spec.go
=> apps: support DEPLOYMENT_STARTED and DEPLOYMENT_CANCELLED alerts.

docs/resources/database_cluster.md
Since this is now in use, it might be good to call it out int he docs.
=> Add opensearch to cluster reference

digitalocean/spaces/spaces_buckets.go
Support for Spaces in London was added 3 days ago.
https://www.digitalocean.com/blog/digitalocean-spaces-now-available-in-london
=> Add support for Spaces in LON1

digitalocean/sshkey/resource_ssh_key.go
I've never been able to reproduce this issue, but as we have received multiple reports we should protect against it. While we retry 5xx errors, we do not generally retry 404s. This adds a retryable GET after creating an SSH key that blocks until the key is found. By default, we'll retry for 2 minutes. I think that is probably more than enough, but I've made it configurable as well.
Resolves: https://github.com/digitalocean/terraform-provider-digitalocean/issues/1163
Resolves: https://github.com/digitalocean/terraform-provider-digitalocean/issues/923
=> ssh: protect against database race condition in create

digitalocean/spaces/spaces_buckets.go
Closes #1248
This PR adds `tor1` region to spaces.
=> [spaces]: add tor1 to spaces

README.md
This PR updates the requirements in readme.
Links were updated because the old links redirect there.
=> [documentation]: update requirements in readme

digitalocean/kubernetes/resource_kubernetes_cluster.go, digitalocean/kubernetes/resource_kubernetes_cluster_test.go, docs/resources/kubernetes_cluster.md
https://docs.digitalocean.com/products/kubernetes/how-to/create-clusters/#create-with-vpc-native
CC: @gottwald
=> k8s: support setting cluster and service subnets on create.

CHANGELOG.md
=> [release]: prep v2.43.0

digitalocean/loadbalancer/datasource_loadbalancer.go, digitalocean/loadbalancer/resource_loadbalancer.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/github.com/digitalocean/godo/reserved_ipv6.go, vendor/github.com/digitalocean/godo/reserved_ipv6_actions.go, vendor/modules.txt
=> LBAAS-3552: add lb ipv6 field

docs/resources/firewall.md
=> docs: Clarify tags argument for firewall

digitalocean/app/app_spec.go, digitalocean/app/resource_app_test.go, docs/data-sources/app.md, docs/resources/app.md
Adds support for specifying images by digest.
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/1286
=> apps: support specifying images by digest

digitalocean/app/app_spec.go, digitalocean/app/resource_app_test.go, docs/data-sources/app.md, docs/resources/app.md
We already support autoscaling for services, but workers should also support it. 
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/1281
=> apps: workers support autoscaling

CHANGELOG.md
```
$ github-changelog-generator -org digitalocean -repo terraform-provider-digitalocean  -token $GH_TOKEN
- #1297 - @andrewsomething - apps: add support for termination configuration.
- #1296 - @andrewsomething - apps: workers support autoscaling
- #1295 - @andrewsomething - apps: support specifying images by digest
- #1294 - @moreinhardt - docs: Clarify tags argument for firewall
```
=> Prep v2.47.0 release.

digitalocean/loadbalancer/resource_loadbalancer.go, digitalocean/loadbalancer/resource_loadbalancer_test.go, docs/resources/loadbalancer.md, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/modules.txt
add ability to set load balancer tls cipher policy via terraform
=> LBAAS: add tls cipher policy arg to load balanacers

docs/resources/kubernetes_cluster.md
Adds documentation for https://github.com/digitalocean/terraform-provider-digitalocean/pull/1312
=> Docs: Update kubernetes_cluster.md for #1312

digitalocean/provider.go, digitalocean/vpcnatgateway/datasource_vpc_nat_gateway.go, digitalocean/vpcnatgateway/datasource_vpc_nat_gateway_test.go, digitalocean/vpcnatgateway/resource_vpc_nat_gateway.go, digitalocean/vpcnatgateway/resource_vpc_nat_gateway_test.go, docs/data-sources/vpc_nat_gateway.md, docs/resources/vpc_nat_gateway.md, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/genai.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/partner_network_connect.go, vendor/github.com/digitalocean/godo/vpc_nat_gateways.go, vendor/modules.txt
=> Introduce vpc nat gateways api

digitalocean/partnernetworkconnect/datasource_partner_network_connect.go, digitalocean/partnernetworkconnect/datasource_partner_network_connect_test.go, digitalocean/partnernetworkconnect/resource_partner_network_connect.go, digitalocean/partnernetworkconnect/resource_partner_network_connect_test.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/registry.go, vendor/modules.txt
Makes PNC redundancy_zone available in terraform.
I tested this locally and was able to set my desired redundancy zone.
=> Add redundancy_zone field to Partner Network Connect

digitalocean/spaces/spaces_entities.go
ATL1 was released as a Spaces region a while back, let's allow folks to use it here.
=> spaces: add atl1 as a region

digitalocean/database/resource_database_cluster.go
Fixes:- [1423](https://github.com/digitalocean/terraform-provider-digitalocean/issues/1423)
=> fixing metrics endpoint failure

digitalocean/kubernetes/datasource_kubernetes_cluster.go, digitalocean/kubernetes/datasource_kubernetes_cluster_test.go, digitalocean/kubernetes/kubernetes.go, digitalocean/kubernetes/resource_kubernetes_cluster.go, digitalocean/kubernetes/resource_kubernetes_cluster_test.go, docs/resources/kubernetes_cluster.md
`amd_gpu_device_plugin` and `amd_gpu_device_metrics_exporter_plugin` being those options.
=> add support for new doks cluster options
