digitalocean/resource_digitalocean_droplet_test.go, digitalocean/resource_digitalocean_floating_ip_test.go, digitalocean/resource_digitalocean_loadbalancer_test.go, digitalocean/resource_digitalocean_volume_test.go, digitalocean/sweeper_test.go
```
% go test ./digitalocean -v -sweep=do-region
2017/07/05 16:07:22 [DEBUG] Running Sweepers for region (do-region):
2017/07/05 16:07:22 [INFO] DigitalOcean Client configured for URL: https://api.digitalocean.com/
2017/07/05 16:07:23 [INFO] DigitalOcean Client configured for URL: https://api.digitalocean.com/
2017/07/05 16:07:24 [INFO] DigitalOcean Client configured for URL: https://api.digitalocean.com/
2017/07/05 16:07:25 [INFO] DigitalOcean Client configured for URL: https://api.digitalocean.com/
2017/07/05 16:07:27 Sweeper Tests ran:
- digitalocean_loadbalancer
- digitalocean_volume
- digitalocean_droplet
- digitalocean_floating_ip
ok  	github.com/terraform-providers/terraform-provider-digitalocean/digitalocean	5.338s
```
=> cleanup: Adding the test sweepers to DO

digitalocean/resource_digitalocean_droplet.go
In some cases DigitalOcean doesn't provide valid values, which had broken our automation several time. This happen really rare, mostly when DO guys do some updates to API, that is why it is really hard to reproduce.
=> Make sure we've got a proper IP address from DO

digitalocean/resource_digitalocean_droplet_test.go, digitalocean/resource_digitalocean_volume_test.go
This is to address a sweeper failure from this morning:
```
2017/08/11 05:09:52 [ERR] error running (digitalocean_volume): DELETE https://api.digitalocean.com/v2/volumes/212bc0da-7d8a-11e7-b204-0242ac112707: 409 A volume that's attached to a Droplet cannot be deleted. Please detach it first before deleting.
```
=> sweepers: Add missing droplet name pattern

README.md
The README displays 'make bin' as build command, but it's 'make build'.
=> Put correct build command in README

digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_droplet_test.go, website/docs/r/droplet.html.markdown
Added for enhancement: https://github.com/terraform-providers/terraform-provider-digitalocean/issues/12
=> Added monitoring boolean

digitalocean/resource_digitalocean_firewall.go, digitalocean/resource_digitalocean_firewall_test.go
Closes https://github.com/terraform-providers/terraform-provider-digitalocean/issues/33
Looks like destination tags were inadvertently being added to the destination addresses list. Test case updated to exercise this usecase. Failure demonstrating the bug before the fix:
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanFirewall_MultipleInboundAndOutbound'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanFirewall_MultipleInboundAndOutbound -timeout 120m
=== RUN   TestAccDigitalOceanFirewall_MultipleInboundAndOutbound
--- FAIL: TestAccDigitalOceanFirewall_MultipleInboundAndOutbound (1.89s)
testing.go:434: Step 0 …
```
=> Correctly hand destination_tags in firewall resource. Fixes: #33

website/docs/r/firewall.html.markdown
Digital Ocean API will throw a 422 error "You must specify a positive value for ports" if you send up “all” (as the documentation used to suggest), or “0”, or "", or anything other than “1-65535” if you want all ports opened.
There is still going to be a bug where if you don't specify the `port_range` parameter at all, the API will give you a 422 error. The documentation suggests the parameter is optional, but it will fail if you don't provide it, since Terraform will send up a `""`, which is also invalid and cause the same 422. I'm not sure what the intended behaviour is if you don't provide the `port_range`, but either way I'm not confident enough with go to fix this myself.
=> Firewall: fix port_range documentation

digitalocean/resource_digitalocean_firewall.go, digitalocean/resource_digitalocean_firewall_test.go
Fixes a bug mentioned in https://github.com/terraform-providers/terraform-provider-digitalocean/pull/39#issue-255538002
```
TF_ACC=1 go test ./digitalocean -v -run=TestAccDigitalOceanFirewall_ -timeout 120m
=== RUN   TestAccDigitalOceanFirewall_AllowOnlyInbound
--- PASS: TestAccDigitalOceanFirewall_AllowOnlyInbound (8.38s)
=== RUN   TestAccDigitalOceanFirewall_AllowMultipleInbound
--- PASS: TestAccDigitalOceanFirewall_AllowMultipleInbound (10.12s)
=== RUN   TestAccDigitalOceanFirewall_AllowOnlyOutbound
--- PASS: TestAccDigitalOceanFirewall_AllowOnlyOutbound (9.54s)
=== RUN   TestAccDigitalOceanFirewall_AllowMultipleOutbound
--- PASS: TestAccDigitalOceanFirewall_AllowMultipleOutbound (8.71s)
=== RUN   TestAccDigitalOceanFirewall_MultipleInboundAndOutbound
--- PASS: …
```
=> r/firewall: Suppress diff for 'all' port range

digitalocean/config.go
This configures the calling Terraform version as part of the `godo` client so that we know when calls are coming from Terraform and which version of Terraform.
cc @radeksimko
=> Configure Terraform version as part of the godo User-Agent

digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_droplet_test.go
Fixes #11 
```
TF_ACC=1 go test ./digitalocean -v -run=TestAccDigitalOceanDroplet_ -timeout 120m
=== RUN   TestAccDigitalOceanDroplet_importBasic
--- PASS: TestAccDigitalOceanDroplet_importBasic (39.55s)
=== RUN   TestAccDigitalOceanDroplet_Basic
--- PASS: TestAccDigitalOceanDroplet_Basic (50.31s)
=== RUN   TestAccDigitalOceanDroplet_WithID
--- FAIL: TestAccDigitalOceanDroplet_WithID (0.77s)
testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:
* digitalocean_droplet.foobar: 1 error(s) occurred:
* digitalocean_droplet.foobar: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation.
=== RUN   TestAccDigitalOceanDroplet_withSSH
--- PASS: TestAccDigitalOceanDroplet_withSSH (55.49s)
=== RUN …
```
=> r/droplet: Avoid crash on conditional volumes

website/docs/r/firewall.html.markdown
DNS uses both UDP and TCP. While UDP is usually the default TCP is
needed to handle larger responses. Especially so when the EDNS0
extension isn't available.
Yes, I do realize that this is just an example. Yet, a lot of people
learn from examples, and the misconception that DNS only needs UDP is
already way too common.
=> Use both TCP and UDP for DNS in firewall example

examples/droplet/main.tf, website/docs/d/image.html.md, website/docs/r/droplet.html.markdown, website/docs/r/firewall.html.markdown, website/docs/r/floating_ip.html.markdown, website/docs/r/loadbalancer.html.markdown, website/docs/r/tag.html.markdown, website/docs/r/volume.markdown
At DO, we recently released new Droplet plans. This updates
the docs to reference the slugs for these plans in preparation
for the old ones to be deprecated. Hopefully this will help
head off confusion like in #74.
See:
https://developers.digitalocean.com/documentation/changelog/api-v2/new-size-slugs-for-droplet-plan-changes/
=> Update docs to use new size slugs.

website/docs/r/domain.html.markdown
The problem with adding a domain like www.example.com is, when you create DNS records (such as one named 'blog') inside that zone, it ends up as a DNS record for blog.www.example.com. By adding the apex domain instead, DNS records will be created and work as expected, avoiding some occasional user confusion.
=> Use an apex domain as the example name

digitalocean/resource_digitalocean_droplet.go
I'm new to this codebase, and fairly new to golang, so please forgive my ignorance.
This issue https://github.com/terraform-providers/terraform-provider-digitalocean/issues/15 describes a bug. 
The current/old logic says to power off and resize iff `(the size changes OR the resize disk field changes) AND resizeDisk is true`. That's logic does not seem correct to me. Instead we should power off and resize iff `resizeDisk is true AND d.HasChange("size")`.
=> Correct the logic for resizing a droplet. Fixes 15

digitalocean/resource_digitalocean_record.go, digitalocean/resource_digitalocean_record_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/README.md, vendor/github.com/digitalocean/godo/domains.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/storage.go, vendor/vendor.json, website/docs/r/record.html.markdown
`terraform` adjustment to manage `CAA` domain records via https://github.com/digitalocean/godo/pull/152 (not yet tagged)
All validation is delegated to the client.
Create a new `CAA` record:
```
resource "digitalocean_record" "example_caa_issue" {
domain  = "${digitalocean_domain.example.name}"
type    = "CAA"
name    = "@"
value   = "letsencrypt.org."
ttl     = 1800
flags   = 0
tag     = "issue"
}
```
Evaluate execution plan:
```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
digitalocean_domain.example: Refreshing state... (ID: example.com)
... [CLIPPED] ...
------------------------------------------------------------------------
An execution plan …
```
=> Manage CAA domain records

digitalocean/datasource_digitalocean_record.go, digitalocean/datasource_digitalocean_record_test.go, digitalocean/provider.go, website/digitalocean.erb, website/docs/d/record.html.md
Similar to #63,  I've cobbled together another data source for DNS records managed by a Digital Ocean account. It also seems to work well for me. I'm no go programmer so any feedback would be much appreciated. I ended up using both the digitalocean_image data source and the digitalocean_record resource types as inspiration. Thanks in advance.
=> Adding digitalocean_record data source

digitalocean/resource_digitalocean_tag.go
DigitalOcean only allows letters, numbers, colons, dashes and underscores as valid characters in a tag name. This commit validates that the assigned name is valid before calling DO's API.
Fixes #78
=> Validate tag name when creating

digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_droplet_test.go
Fixes: #92 
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanDroplet_Basic'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanDroplet_Basic -timeout 120m
=== RUN   TestAccDigitalOceanDroplet_Basic
--- PASS: TestAccDigitalOceanDroplet_Basic (30.10s)
PASS
ok  	github.com/terraform-providers/terraform-provider-digitalocean/digitalocean	30.102s
```
=> When IPv6 and/or private networking are not enabled, default their addresses to "".

digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_droplet_test.go
This PR resolves issue #67. The panic was caused by `newDropletStateRefreshFunc` attempting to return a bool instead of a string. Additionally, if it had somehow gotten past that, there was no check whether `err` was `nil` or not before returning with the error. A new acceptance test was also added to exercise this functionality.
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanDroplet_UpdatePrivateNetworkingIpv6'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanDroplet_UpdatePrivateNetworkingIpv6 -timeout 120m
=== RUN   TestAccDigitalOceanDroplet_UpdatePrivateNetworkingIpv6
--- PASS: …
```
=> Don't panic when enabling private_networking or ipv6. (Fixes #67)

digitalocean/resource_digitalocean_droplet.go
This implements a new `resourceDigitalOceanDropletImport` function
so that we can handle some things differently while importing
than when using `resourceDigitalOceanDropletRead`.
In particular, this is needed here as `resize_disk` defaults to
`true`, but importing results in an empty value as it is a non-API
attribute. So when running `terraform apply` changes are found
regardless of the value in the tf file.
See: https://github.com/terraform-providers/terraform-provider-digitalocean/issues/76
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanDroplet_importBasic'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanDroplet_importBasic -timeout 120m
? …
```
=> Set resize_disk to the default value on import.

digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_firewall.go, digitalocean/resource_digitalocean_loadbalancer.go, digitalocean/resource_digitalocean_tag.go, digitalocean/resource_digitalocean_tag_test.go, digitalocean/set.go, digitalocean/suppress.go, digitalocean/suppress_test.go, digitalocean/tags.go, digitalocean/tags_test.go
Moved tags to a separate space/files, so that they can be managed in a single place and used by any resource that can be tagged.
Changed the schema and definition of the tags from a list to a set, to resolve outstanding issues with changing orders and duplicates. Fixes #7 
The change is backward compatible. If you have an existing state file, the tags inside it will be automatically updated/refreshed on the next read.
=> Migrated tags to use sets and centralised tag definitions/functionality

digitalocean/hash.go, digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_droplet_test.go, website/docs/r/droplet.html.markdown
The `user_data` property of the `digitalocean_droplet` resource was updated to use the hash of the value to save in the state and use for diffs instead of the full value, which can be quite large. This way the actual value won't be shown in the console when doing diffs. This increases visibility and clarity of the output, as well as prevents potential sensitive data from being shown.
Backward compatibility for existing state files with full `user_data` values saved is preserved.
In addition, the PR includes validations for the droplet properties and minor fixes and enhancements to the codebase of the resource.
Resolves #65
=> Updated the state representation of the `user_data` droplet property to a hashed one

digitalocean/resource_digitalocean_record_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/account.go, vendor/github.com/digitalocean/godo/domains.go, vendor/github.com/digitalocean/godo/godo.go, vendor/vendor.json
This PR includes the new version of the godo SDK (v1.4.2), that includes support for setting the weight of a dns record to zero.
=> Enable setting a dns' record weight to 0 (updated godo SDK)

digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_droplet_migrate.go, digitalocean/resource_digitalocean_droplet_migrate_test.go
Fixes a force recreate of a droplet If you have a state file from an older version of the terraform provider and didn't specify the `monitoring` or `backups` property in the resource.
=> Fixed an issue with force recreating droplets when using an older terraform state

digitalocean/resource_digitalocean_volume.go, digitalocean/resource_digitalocean_volume_test.go, website/docs/r/volume.html.markdown
The PR splits out the volume properties for the filesystem type/label that the volume is initially created with and the volumes current filesystem type/label. The reason behind the change is because the filesystem can not be changed through the API after the fact. However if the filesystem is changed by the droplet, the changes will be reflected in the API and consequentially the terraform state file on refresh.
The changes should be fully backward compatibly with a deprecation message for using the old property.
=> Refactored support for setting the volumes filesystem type and label

digitalocean/import_digitalocean_droplet_test.go, digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_droplet_test.go
When importing a Droplet based on an image that no longer has a slug (or never had one, e.g. a snapshot), the image ID is not properly being set to state. This had not been an issue in the past as we did not validate that the image value was not an empty string.
This PR ensures the correct value is set.
=> Ensure image ID set to state when importing a Droplet (Fixes: #144).

digitalocean/resource_digitalocean_certificate.go, digitalocean/resource_digitalocean_certificate_test.go
When creating a custom certificate, the DigitalOcean API does not accept the `domains` attribute. This is only used when creating a Let's Encrypt certificate. Though the API does return this attribute when reading an existing custom certificate as the information is inferred from the provided certificate. This leads to the situation seen in #146. This PR resolves this issue by suppressing the diff for the `domains` attribute when the `type` is `custom`.
Most of the code added here is in the test. Our previous test did not catch this issue as it used Terraform's `acctest.RandTLSCert` to generate the test data. This function does not set the DNS names for the certificate. The new code is based on it, but allows for passing DNS name.
=> Suppress diff for dns names on custom certificate resources (Fixes: #146)

digitalocean/config.go, digitalocean/provider.go, digitalocean/provider_test.go, website/docs/index.html.markdown
This allows you to change the default URL for accessing the DigitalOcean
API. It's similar to what you would do when overriding an endpoint in
the AWS provider, only with the DO API it's an all or nothing change.
=> Add an override for the DigitalOcean API URL

website/docs/r/kubernetes_cluster.html.markdown
Just a tiny fix to change `woker-pool` to `worker-pool`.
=> Fix typo in node pool name

digitalocean/datasource_digitalocean_droplet_snapshot_test.go, digitalocean/datasource_digitalocean_droplet_test.go, digitalocean/datasource_digitalocean_loadbalancer_test.go, digitalocean/datasource_digitalocean_record_test.go, digitalocean/resource_digitalocean_certificate_test.go, digitalocean/resource_digitalocean_domain_test.go, digitalocean/resource_digitalocean_droplet_snapshot_test.go, digitalocean/resource_digitalocean_droplet_test.go, digitalocean/resource_digitalocean_firewall_test.go, digitalocean/resource_digitalocean_floating_ip_assignment_test.go, digitalocean/resource_digitalocean_loadbalancer_test.go, digitalocean/resource_digitalocean_volume_snapshot_test.go, digitalocean/resource_digitalocean_volume_test.go
This PR contains a number of fixes and improvements to the sweeper that is used to destroy dangling resources left behind by HashiCorp's CI in the case of failures:
- Ensures resources are created with the correct prefixes to be found by the sweeper
- Adds new sweepers for domains, certificates, and firewalls
- Uses larger page sizes when looking for resources
- Uses a random public key in resource_digitalocean_droplet_test instead of hardcoding one
There should be no user facing changes.
=> Acceptance test sweeper improvements

digitalocean/provider.go, digitalocean/resource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_database_cluster_test.go, website/digitalocean.erb, website/docs/r/database_cluster.html.markdown
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanDatabaseCluster_'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanDatabaseCluster_ -timeout 120m
=== RUN   TestAccDigitalOceanDatabaseCluster_Basic
--- PASS: TestAccDigitalOceanDatabaseCluster_Basic (269.01s)
=== RUN   TestAccDigitalOceanDatabaseCluster_WithUpdate
--- PASS: TestAccDigitalOceanDatabaseCluster_WithUpdate (475.48s)
PASS
ok  	github.com/terraform-providers/terraform-provider-digitalocean/digitalocean	744.505s
```
=> r/digitalocean_database_cluster: Adding new resource to manage database clusters

digitalocean/datasource_digitalocean_loadbalancer.go, digitalocean/resource_digitalocean_loadbalancer.go, digitalocean/resource_digitalocean_loadbalancer_test.go, website/docs/r/loadbalancer.html.markdown
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanLoadbalancer_sslTermination'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanLoadbalancer_sslTermination -timeout 120m
=== RUN   TestAccDigitalOceanLoadbalancer_sslTermination
--- PASS: TestAccDigitalOceanLoadbalancer_sslTermination (79.61s)
PASS
ok  	github.com/terraform-providers/terraform-provider-digitalocean/digitalocean	79.623s
```
=> Add support for enabling PROXY Protocol on Load Balancers.

digitalocean/resource_digitalocean_certificate.go, digitalocean/resource_digitalocean_certificate_test.go
When CustomizeDiff is run for a new resource, it does not have access to the
current state. In the digitalocean_certificate resource, we are using a
CustomizeDiff function to validate that certain attributes are used together
depending on the certificate type. When the value for one of those attributes
is interpolated, as in the case of generating a cert using the acme provider,
the validation fails since it depends on reading the value from state. As state
is not present, the value is interpreted as empty.
From the CustomizeDiff doc string:
> // The phases Terraform runs this in, and the state available via functions
> // like Get and GetChange, are as follows:
> //
> //  * New resource: One run with no state
https://godoc.org/github.com/hashicorp/terraform/helper/schema#Resource
This PR …
=> Certificates: Move attribute validation from CustomizeDiff to Create (Fixes: #163).

digitalocean/resource_digitalocean_spaces_bucket.go, digitalocean/resource_digitalocean_spaces_bucket_test.go, website/docs/r/spaces_bucket.html.markdown
This PR Introduces the URN attribute into the spaces/bucket resource.  Unlike the other resources that use the structs from the godo client, the spaces resource does not do this in the read function.  As a result the URN is created in the read function.
**NOTE:**  DigitialOcean API is not allowing the use of nyc3 for spaces/bucket creation and so the use of ams3 as a region has been used to allow the tests to execute.
=> Updates the spaces resource to expose the urn.

website/docs/r/droplet.html.markdown
The DigitalOcean API will automatically create a tag if it does not already exist when specified in a request to create a Droplet.
https://developers.digitalocean.com/documentation/v2/#create-a-new-droplet
=> Remove outdated info from Droplet tag docs.

digitalocean/import_digitalocean_droplet_test.go, digitalocean/import_digitalocean_record_test.go, digitalocean/import_digitalocean_spaces_bucket_test.go, digitalocean/import_digitalocean_volume_test.go, digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_record.go, digitalocean/resource_digitalocean_spaces_bucket.go, digitalocean/resource_digitalocean_spaces_bucket_test.go, digitalocean/resource_digitalocean_volume.go
This PR brings in a number of improvements around resource importing. Specifically:
- For Volumes, it removes the need for a custom function altogether by just using `ImportStatePassthrough`
- For resources that really do require a custom import function (Droplet, Domain Records, and Spaces buckets), it removes unnecessary calls to the resource read functions. The only thing that is required in the import function is to set the specific attributes.
- For all of the changed resources, an additional test has been added to ensure that a proper error message is provided when the resource being imported does not exist (e.g. the ID was wrong).
- For the Droplet resource, it adds some additional error checking to the custom import function.
``` …
```
=> Various resource import improvements (Fixes: #231).

digitalocean/resource_digitalocean_droplet.go
Fixes: #181
DigitalOcean doesn't support IPv6 private networking. Therefore,
having a parameter in the schema for this isn't correct. It has
been marked as `removed` with an appropriate error message
=> resource/droplet: Removing the IPv6 private parameter

website/docs/r/record.html.markdown
According to https://tools.ietf.org/html/rfc6844 the valid tag is "issuewild", not "wildissue".
=> Fixed CAA record tag

digitalocean/resource_digitalocean_kubernetes_cluster.go, digitalocean/resource_digitalocean_kubernetes_cluster_test.go, digitalocean/resource_digitalocean_kubernetes_node_pool.go
While still in beta, the DigitalOcean Kubernetes API automatically applied tags
from the cluster to the node pools. The provider's `filterTags` function
accounted for this by not manually applying tags found on the parent cluster
to the children node pools:
```
// we need to filter tags to remove any automatically added to avoid state problems,
// these are tags starting with "k8s:", named "k8s" or duplicates of the cluster tags
```
This does not match the current behavior of the API. See:
#184
The updated test fails without the additional changes:
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanKubernetesCluster_Basic'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanKubernetesCluster_Basic …
```
=> K8s: Do not filter out node pool tags also applied to the cluster (Fixes: #184).

digitalocean/provider.go, website/docs/index.html.markdown
Fixes: #260
This follows the same usage as `doctl` so not having to reset env
vars would be a better experience. This DOT NOT remove DIGITALOCEAN_TOKEN,
this just adds the ability to specify one of the two and the
provider will continue to work as expected
=> provider: Add the ability to set DIGITALOCEAN_ACCESS_TOKEN

digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_droplet_test.go
Somehow we never seem to have supported enabling and disabling backups on Droplets. 😯 This fixes that!
New test failing pre-change:
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanDroplet_EnableAndDisableBackups'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanDroplet_EnableAndDisableBackups -timeout 120m
=== RUN   TestAccDigitalOceanDroplet_EnableAndDisableBackups
--- FAIL: TestAccDigitalOceanDroplet_EnableAndDisableBackups (36.81s)
testing.go:568: Step 1 error: Check failed: Check 2/2 error: digitalocean_droplet.foobar: Attribute 'backups' expected "true", got "false"
FAIL
FAIL …
```
=> Support enabling and disabling backups on Droplets (Fixes: #266).

digitalocean/resource_digitalocean_kubernetes_cluster_test.go, website/docs/r/kubernetes_cluster.html.markdown
DigitalOcean has deprecated version `1.14.2-do.0` in favor of version `1.14.4-do.0` for the `digitalocean_kubernetes_cluster` resource. 
Error when using version `1.14.2-do.0`:
> Error: Error creating Kubernetes cluster: POST https://api.digitalocean.com/v2/kubernetes/clusters: 422 rpc error: code = InvalidArgument desc = validation error: invalid version slug
=> Update digitalocean_kubernetes_cluster version

digitalocean/datasource_digitalocean_domain.go, digitalocean/datasource_digitalocean_floating_ip.go, digitalocean/datasource_digitalocean_image.go, digitalocean/datasource_digitalocean_kubernetes_cluster.go, digitalocean/datasource_digitalocean_record.go, digitalocean/datasource_digitalocean_tag.go, digitalocean/resource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_domain.go, digitalocean/resource_digitalocean_droplet_snapshot.go, digitalocean/resource_digitalocean_kubernetes_cluster.go, digitalocean/resource_digitalocean_kubernetes_node_pool.go, digitalocean/resource_digitalocean_record.go, digitalocean/resource_digitalocean_volume.go, digitalocean/resource_digitalocean_volume_attachment.go, digitalocean/resource_digitalocean_volume_snapshot.go
In many cases we handle 404s different than other errors. Though if an error contains no response at all, we panic. (See: #272) Some resources already protect against this, but not all of them.
=> Consistently protect against nil response in error handling (Fixes: #272).

website/docs/r/loadbalancer.html.markdown
DigitalOcean’s API supports HTTP2 in load balancers (see [docs](https://developers.digitalocean.com/documentation/v2/#load-balancers)).
=> Add HTTP2 protocol to load balancer docs

digitalocean/resource_digitalocean_kubernetes_cluster.go, digitalocean/resource_digitalocean_kubernetes_cluster_test.go
This data includes sensitive information about the cluster, such as its private key. This prevents that data from ending up in, for example, logs on a CI system that does a `terraform plan` as part of its build.
With this applied, a `terraform plan` or `terraform apply` instead shows:
```
...
ipv4_address   = "1.2.3.4"
kube_config    = (sensitive value)
name           = "roboticcheese"
...
```
Also updates the acceptance tests, as 1.14.4-do.0 is no longer available.
It's been five years since I last looked at any Go and never since I poked around Terraform code, so apologies in advance for any issues with this that I'm not considering. At first, I thought it could just mark the `client_key` and `client_certificate` as sensitive (matching what gets redacted by default from `kubectl config …
=> Mark the kubernetes_cluster resource's kube_config field as sensitive

digitalocean/config.go, digitalocean/provider.go
In order to switch to `github.com/hashicorp/terraform-plugin-sdk`, we first need to remove our usage of `terraform.VersionString()`
https://www.terraform.io/docs/extend/plugin-sdk.html#deprecations
=> terraform.VersionString() has been deprecated.

digitalocean/datasource_digitalocean_database_cluster.go, digitalocean/datasource_digitalocean_database_cluster_test.go, digitalocean/resource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_database_cluster_test.go, website/docs/r/database_cluster.html.markdown
Adds `private_host` and `private_uri` attributes for `digitalocean_database_cluster` resource and datasource.
Reference: https://github.com/terraform-providers/terraform-provider-digitalocean/issues/299.
=> Provide private connection details for `database_cluster'

digitalocean/resource_digitalocean_database_cluster.go
Fixes https://github.com/terraform-providers/terraform-provider-digitalocean/issues/298.
=> Mark uri, private_uri, password as sensitive for database_cluster.

digitalocean/datasource_digitalocean_database_cluster.go, digitalocean/datasource_digitalocean_database_cluster_test.go, digitalocean/resource_digitalocean_database_replica.go, digitalocean/resource_digitalocean_database_replica_test.go, website/docs/d/database_cluster.html.markdown, website/docs/r/database_replica.html.markdown
This PR ties up a few loose ends related to #294, #300, and #301. Specifically:  
* datasource/database_cluster: Add password to exported attributes and mark fields sensitive
* resource/database_replica: Expose private connection info and mark fields sensitive
=> Expose private connection info for replicas and mark final DBaaS fields sensitive

digitalocean/datasource_digitalocean_kubernetes_cluster_test.go, digitalocean/provider_test.go, digitalocean/resource_digitalocean_kubernetes_cluster_test.go, digitalocean/resource_digitalocean_kubernetes_node_pool.go, digitalocean/resource_digitalocean_kubernetes_node_pool_test.go, website/docs/r/kubernetes_cluster.html.markdown
A few `testacc` updates while working through some upcoming PRs:
- Support running the `testacc` tests in parallel using `t.Parallel()`
- Use alpha-prefixed random cluster and node pool names in tests to avoid validation errors when they start with a digit.
- Wait for number of nodes in a pool to match the expected count in `waitForKubernetesNodePoolCreate` (which is also used for waiting after updates)
I can break this into individual PRs if you'd prefer, just LMK.
@andrewsomething @eddiezane @timoreimann 
Node name validation failure:
```sh
--- FAIL: TestAccDigitalOceanKubernetesCluster_UpdateCluster (0.56s)
testing.go:569: Step 0 error: errors during apply:
Error: Error creating Kubernetes cluster: POST https://api.digitalocean.com/v2/kubernetes/clusters: 422 rpc error: code = …
```
=> doks: fix acc tests

digitalocean/resource_digitalocean_kubernetes_cluster.go, digitalocean/resource_digitalocean_kubernetes_cluster_test.go, digitalocean/resource_digitalocean_kubernetes_node_pool_test.go, website/docs/d/kubernetes_cluster.html.md, website/docs/r/kubernetes_cluster.html.markdown
This PR bumps DOKS versions in acc tests to latest (`1.15.3-do.3`), and updates tests to expect tokens instead of certs in the kubeconfig. This is in preparation for some other upcoming PRs.
*Note* that this PR is rebased on top of https://github.com/terraform-providers/terraform-provider-digitalocean/pull/308 until it's merged. See https://github.com/snormore/terraform-provider-digitalocean/compare/doks-testacc-fixes...doks-bump-versions until then.
@andrewsomething @eddiezane @timoreimann
```sh
$ GOFLAGS=-mod=vendor make testacc TESTARGS="-run=TestAccDigitalOceanKubernetes -parallel=10"
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanKubernetes -parallel=10 -timeout 120m
? …
```
=> doks: bump to latest cluster version and use token auth

digitalocean/resource_digitalocean_kubernetes_cluster_test.go, digitalocean/resource_digitalocean_kubernetes_node_pool_test.go, website/docs/r/kubernetes_cluster.html.markdown
Bumping this every time there's a new release definitely isn't ideal. I'm going to follow-up with a PR that handles this more dynamically, at some point this week. For now, let's bump it again.
@andrewsomething @eddiezane @timoreimann
=> doks: bump version in tests to 1.15.4-do.0

digitalocean/resource_digitalocean_kubernetes_cluster.go, digitalocean/resource_digitalocean_kubernetes_cluster_test.go, go.mod, website/docs/d/kubernetes_cluster.html.md, website/docs/r/kubernetes_cluster.html.markdown
As a side-effect of moving to the `GetCredentials` endpoint in https://github.com/terraform-providers/terraform-provider-digitalocean/pull/311, the `raw_config` is no longer a usable kubeconfig file. This PR attempts to fix that.
@snormore, I'd love your input here. This feels more fragile than I'd like. Is there a better way to get the cluster and user names for use in a kubeconfig file short of making calls to both `GetKubeConfig` and `GetCredentials`?
=> doks: Produce a valid kubeconfig file.

website/digitalocean.erb
There is a documentation page for this resource created in #294, but the sidebar doesn't display it.
=> Add missing sidebar link to digitalocean_database_replica resource page

digitalocean/datasource_digitalocean_account.go, digitalocean/datasource_digitalocean_account_test.go, digitalocean/provider.go, website/digitalocean.erb, website/docs/d/account.html.md
This PR creates a new data source `digitalocean_account` to retrieve information of the authenticated user used in the provider. It is currently a basic implementation as proposed in #263, but cannot retrieve information of other users yet.
```hcl
data "digitalocean_account" "example" {
}
```
=> Add data source for account

digitalocean/import_digitalocean_database_user_test.go, digitalocean/provider.go, digitalocean/resource_digitalocean_database_user.go, digitalocean/resource_digitalocean_database_user_test.go, website/digitalocean.erb, website/docs/r/database_user.html.markdown
Implement `digitalocean_database_user` as per #222.
```hcl
resource "digitalocean_database_user" "user-example" {
cluster_id = "${digitalocean_database_cluster.postgres-example.id}"
name       = "foobar"
}
resource "digitalocean_database_cluster" "postgres-example" {
name       = "example-postgres-cluster"
engine     = "pg"
version    = "11"
size       = "db-s-1vcpu-1gb"
region     = "nyc1"
node_count = 1
}
```
Currently it will always create `normal` user with limited access to the database. It'd be super useful if the API allows us to manage user's permissions as well, e.g. automatically giving the user read/write access to a database. Any way to give feedback to Digital Ocean about this? 😄
=> Add resource for database user

digitalocean/datasource_digitalocean_sizes.go, digitalocean/datasource_digitalocean_sizes_test.go, digitalocean/filter.go, digitalocean/filter_test.go, digitalocean/provider.go, digitalocean/sort.go, digitalocean/sort_test.go, website/digitalocean.erb, website/docs/d/sizes.html.md
Related with sizes data source proposal in #263. This PR creates a new data source `digitalocean_sizes` with a rudimentary implementation of filter and sort. The information is retrieved from https://developers.digitalocean.com/documentation/v2/#sizes.
Most common usage will probably be to supply a size to droplet:
```hcl
data "digitalocean_sizes" "main" {
filter {
key    = "slug"
values = ["s-1vcpu-1gb"]
}
}
resource "digitalocean_droplet" "web" {
image  = "ubuntu-18-04-x64"
name   = "web-1"
region = "sgp1"
size   = element(data.digitalocean_sizes.main.sizes, 0).slug
}
```
The data source also supports multiple filters and sorts. For example, fetch sizes with virtual CPU 1 or 2 that are available "sgp1" region. Pick the cheapest one:
```hcl
data "digitalocean_sizes" "main" {
filter {
key …
```
=> Add data source for sizes (with filter and sort)

digitalocean/datasource_digitalocean_volume.go, digitalocean/datasource_digitalocean_volume_test.go, digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_volume.go, digitalocean/resource_digitalocean_volume_test.go, digitalocean/tags.go, website/docs/d/volume.html.md, website/docs/r/volume.html.markdown
Saw volumes can support tags so this PR adds the `tags` argument to the `digitalocean_volume` resource.
Seems like a few other resources can support tags so if this PR looks good, I can probably spend some time adding tag support for other resources in future PR's.
=> Add support for volume tags

digitalocean/datasource_digitalocean_volume_snapshot.go, digitalocean/datasource_digitalocean_volume_snapshot_test.go, digitalocean/resource_digitalocean_volume_snapshot.go, digitalocean/resource_digitalocean_volume_snapshot_test.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/CONTRIBUTING.md, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/doc.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/links.go, vendor/github.com/digitalocean/godo/registry.go, vendor/github.com/digitalocean/godo/tags.go, vendor/modules.txt, website/docs/d/volume_snapshot.html.md, website/docs/r/volume_snapshot.html.markdown
This PR adds support for `tags` to the `digitalocean_volume_snapshot` resource and data source.
Volume Snapshot Resource Tests:
```
=== RUN   TestAccDigitalOceanVolumeSnapshot_importBasic
--- PASS: TestAccDigitalOceanVolumeSnapshot_importBasic (10.58s)
=== RUN   TestAccDigitalOceanVolumeSnapshot_Basic
--- PASS: TestAccDigitalOceanVolumeSnapshot_Basic (10.65s)
=== RUN   TestAccDigitalOceanVolumeSnapshot_UpdateTags
--- PASS: TestAccDigitalOceanVolumeSnapshot_UpdateTags (13.67s)
PASS
ok      github.com/terraform-providers/terraform-provider-digitalocean/digitalocean     34.940s
```
Volume Snapshot Data Source Tests:
```
=== RUN   TestAccDataSourceDigitalOceanVolumeSnapshot_basic
--- PASS: TestAccDataSourceDigitalOceanVolumeSnapshot_basic (22.78s)
=== RUN …
```
=> add support for volume snapshot tags

digitalocean/hash.go, digitalocean/resource_digitalocean_certificate.go, digitalocean/resource_digitalocean_certificate_test.go, digitalocean/resource_digitalocean_droplet.go
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanCertificate_Basic'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanCertificate_Basic -timeout 120m
=== RUN   TestAccDigitalOceanCertificate_Basic
--- PASS: TestAccDigitalOceanCertificate_Basic (21.16s)
PASS
ok  	github.com/terraform-providers/terraform-provider-digitalocean/digitalocean	21.181s
```
=> Don't store full certificate data in state file (Fixes: #156).

digitalocean/import_digitalocean_database_firewall_test.go, digitalocean/provider.go, digitalocean/resource_digitalocean_database_firewall.go, digitalocean/resource_digitalocean_database_firewall_test.go, website/digitalocean.erb, website/docs/r/database_firewall.html.markdown
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanDatabaseFirewall'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanDatabaseFirewall -timeout 120m
=== RUN   TestAccDigitalOceanDatabaseFirewall_importBasic
--- PASS: TestAccDigitalOceanDatabaseFirewall_importBasic (262.07s)
=== RUN   TestAccDigitalOceanDatabaseFirewall_Basic
--- PASS: TestAccDigitalOceanDatabaseFirewall_Basic (237.98s)
=== RUN   TestAccDigitalOceanDatabaseFirewall_MultipleResourceTypes
--- PASS: TestAccDigitalOceanDatabaseFirewall_MultipleResourceTypes (282.36s)
PASS
ok  	github.com/terraform-providers/terraform-provider-digitalocean/digitalocean …
```
=> Add support for Database Firewalls (Fixes :#340).

digitalocean/resource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_database_cluster_test.go, website/docs/r/database_cluster.html.markdown
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanDatabaseCluster_Redis'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanDatabaseCluster_Redis -timeout 120m
=== RUN   TestAccDigitalOceanDatabaseCluster_RedisNoVersion
--- PASS: TestAccDigitalOceanDatabaseCluster_RedisNoVersion (263.90s)
=== RUN   TestAccDigitalOceanDatabaseCluster_RedisWithEvictionPolicy
--- PASS: TestAccDigitalOceanDatabaseCluster_RedisWithEvictionPolicy (296.65s)
PASS
ok  	github.com/terraform-providers/terraform-provider-digitalocean/digitalocean	560.568s
```
=> Add support for Redis eviction policies (Fixes: #342).

digitalocean/resource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_database_cluster_test.go, website/docs/r/database_cluster.html.markdown
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanDatabaseCluster_WithSQLMode'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanDatabaseCluster_WithSQLMode -timeout 120m
=== RUN   TestAccDigitalOceanDatabaseCluster_WithSQLMode
--- PASS: TestAccDigitalOceanDatabaseCluster_WithSQLMode (324.50s)
PASS
ok  	github.com/terraform-providers/terraform-provider-digitalocean/digitalocean	324.521s
```
=> Add support for configuring SQL mode.

digitalocean/resource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_database_cluster_test.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/action.go, vendor/github.com/digitalocean/godo/balance.go, vendor/github.com/digitalocean/godo/cdn.go, vendor/github.com/digitalocean/godo/certificates.go, vendor/github.com/digitalocean/godo/domains.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/firewalls.go, vendor/github.com/digitalocean/godo/floating_ips.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/images.go, vendor/github.com/digitalocean/godo/keys.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/github.com/digitalocean/godo/meta.go, vendor/github.com/digitalocean/godo/projects.go, vendor/github.com/digitalocean/godo/regions.go, vendor/github.com/digitalocean/godo/sizes.go, vendor/github.com/digitalocean/godo/snapshots.go, vendor/github.com/digitalocean/godo/storage.go, vendor/github.com/digitalocean/godo/storage_actions.go, vendor/github.com/digitalocean/godo/tags.go, vendor/github.com/digitalocean/godo/vpcs.go, vendor/modules.txt
This PR adds support for updating tags to the `digitalocean_database_cluster` resource.
```
=== RUN   TestAccDigitalOceanDatabaseCluster_TagUpdate
--- PASS: TestAccDigitalOceanDatabaseCluster_TagUpdate (381.72s)
PASS
ok      github.com/terraform-providers/terraform-provider-digitalocean/digitalocean     381.822s
```
=> add support for updating database cluster tags

website/docs/d/kubernetes_cluster.html.md, website/docs/r/kubernetes_cluster.html.markdown
In the case demonstrated by this example, the user should probably use
``load_config_file = false`` to avoid running into validation errors due
to unrelated kubeconfigs.
Refs #358
=> Improve kubernetes configuration example

digitalocean/provider.go
This resolves the issue reported in #354 in a way that is consistent with other providers. It has the added benefit of now allowing Spaces only usage.
=> provider: Mark API token as optional (Fixes: #354).

website/docs/index.html.markdown
Looks like I missed the main index page when I update all of the individual resources to use the current syntax.
=> Update provider docs to use >= 0.12 syntax.

digitalocean/datasource_digitalocean_droplet.go, digitalocean/datasource_digitalocean_droplet_test.go, digitalocean/resource_digitalocean_kubernetes_node_pool.go, go.mod, website/docs/d/droplet.html.md, website/docs/r/kubernetes_cluster.html.markdown, website/docs/r/kubernetes_node_pool.html.markdown
Add `droplet_id` attribute to the nodes in a node pool of a Kubernetes cluster. And then allow lookups of droplets by ID for `data.digitalocean_droplet`. This seemed a more robust way of looking up full information on a droplet in a node pool since it was unclear to me whether `name` is guaranteed to be unique within an account. (In my use case, getting the public IP of a node in a node pool to assign to a DNS record.)
=> add droplet ID to node pools and droplet datasource

go.mod, website/docs/r/record.html.markdown
Document that `@` as the name on a `digitalocean_record` resource allows the creation of DNS records on the exact domain.
=> document use of @ as name on digitalocean_record

digitalocean/import_digitalocean_kubernetes_cluster_node_pool_test.go, digitalocean/import_digitalocean_kubernetes_cluster_test.go, digitalocean/import_digitalocean_kubernetes_node_pool_test.go, digitalocean/resource_digitalocean_kubernetes_cluster.go, digitalocean/resource_digitalocean_kubernetes_cluster_test.go, digitalocean/resource_digitalocean_kubernetes_node_pool.go, website/docs/r/kubernetes_cluster.html.markdown, website/docs/r/kubernetes_node_pool.html.markdown
Teach `digitalocean_kubernetes_cluster` how to import existing clusters.
The main issue is that the provider expects the default node pool to have a `terraform:default-node-pool` tag. This PR adds a check in `digitaloceanKubernetesClusterRead` to ensure that one and only one node pool has that tag. Users importing an existing cluster will need to add that tag manually.
A more advanced implementation might infer the default node pool (for example, if there was only one node pool), and automatically set the tag, but making mutating API calls during an import seems complicated so I avoided doing that. Much easier to just have the documentation mention the need to add the tag.
I ran the the acceptance test successfully (with the kubeconfig and node pool count attributes filtered out). The …
=> add import support for digitalocean_kubernetes_cluster and digitalocean_kubernetes_node_pool resources

digitalocean/datasource_digitalocean_droplet_snapshot.go, digitalocean/datasource_digitalocean_volume_snapshot.go, digitalocean/resource_digitalocean_floating_ip.go, digitalocean/resource_digitalocean_floating_ip_assignment.go
In https://github.com/terraform-providers/terraform-provider-digitalocean/pull/375, we updated the terraform-plugin-sdk to 1.6.0. This renamed and deprecated a number of helper/validation methods. See: https://github.com/hashicorp/terraform-plugin-sdk/blob/master/CHANGELOG.md#160-january-29-2020
This PR updates the to the new versions.
=> Update for deprecated terraform-plugin-sdk helper/validation methods. 

digitalocean/datasource_digitalocean_kubernetes_cluster.go, digitalocean/datasource_digitalocean_kubernetes_cluster_test.go, digitalocean/resource_digitalocean_kubernetes_cluster.go, digitalocean/resource_digitalocean_kubernetes_cluster_test.go, digitalocean/resource_digitalocean_kubernetes_node_pool.go, digitalocean/resource_digitalocean_kubernetes_node_pool_test.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/.whitesource, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/registry.go, vendor/modules.txt, website/docs/d/kubernetes_cluster.html.md, website/docs/r/kubernetes_cluster.html.markdown, website/docs/r/kubernetes_node_pool.html.markdown
Adds support to configure labels on `digitalocean_kubernetes_node_pool` resources and the default node pool of `digitalocean_kubernetes_cluster` resources. Upgrades `godo` to v1.30.0 to pick up labels support. Implements https://github.com/terraform-providers/terraform-provider-digitalocean/issues/374.
=> add labels support to Kubernetes node pools

digitalocean/datasource_digitalocean_region.go, digitalocean/datasource_digitalocean_region_test.go, digitalocean/datasource_digitalocean_regions.go, digitalocean/datasource_digitalocean_regions_test.go, digitalocean/provider.go, digitalocean/regions.go, digitalocean/schema.go, digitalocean/testing.go, go.mod, website/digitalocean.erb, website/docs/d/region.html.md, website/docs/d/regions.html.md
Add `digitalocean_regions` and `digitalocean_region` data sources. `digitalocean_regions` allows filtering by whether a region is available and the features present in the region. `digitalocean_region` returns metadata on a single region.
This is intended to supersede https://github.com/terraform-providers/terraform-provider-digitalocean/pull/281.
=> add digitalocean_regions and digitalocean_region data sources

digitalocean/resource_digitalocean_volume.go
I tried to create a volume. Terraform failed with:
```
Error: Error creating Volume: POST https://api.digitalocean.com/v2/volumes: 422 (request "a1952cf3-2088-4e8d-802d-xxxxx") failed to create volume: invalid volume name. names must be lowercase and alphanumeric
```
=> Require that volume names be lowercase and alphanumeric

digitalocean/datasource_digitalocean_project.go, digitalocean/datasource_digitalocean_project_test.go, digitalocean/datasource_digitalocean_projects.go, digitalocean/datasource_digitalocean_projects_test.go, digitalocean/projects.go, digitalocean/provider.go, digitalocean/resource_digitalocean_project.go, website/digitalocean.erb, website/docs/d/project.html.md, website/docs/d/projects.html.md
Adds `digitalocean_project` and `digitalocean_projects` datasources using the datalist library to be added in https://github.com/terraform-providers/terraform-provider-digitalocean/pull/385. The test for `digitalocean_projects` still needs a bug fixed, but this generally shows the approach of how to use `datalist` to add a new datasource.
Some modifications to `datalist` were made and will be moved to https://github.com/terraform-providers/terraform-provider-digitalocean/pull/385.
=> add datasource for projects

digitalocean/datasource_digitalocean_image.go, digitalocean/datasource_digitalocean_image_test.go, digitalocean/datasource_digitalocean_images.go, digitalocean/datasource_digitalocean_images_test.go, digitalocean/images.go, digitalocean/provider.go, go.mod, website/digitalocean.erb, website/docs/d/image.html.md, website/docs/d/images.html.md
Use the datalist library to add a `digitalocean_images` datasource. Also update the `digitalocean_image` datasource to use the new common code.
This should supersede https://github.com/terraform-providers/terraform-provider-digitalocean/pull/79, although an open question is whether there should be a `type` attribute like in the DO API for applications and distributions.
=> add digitalocean_images datasource

digitalocean/datasource_digitalocean_image.go, website/docs/d/image.html.md
Default `digitalocean_image` to user images to match previous behavior (i.e., principle of least surprise).
=> default digitalocean_image to user images

digitalocean/resource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_database_cluster_test.go, website/docs/r/database_cluster.html.markdown
Previously, the DigitalOcean API only returned a version number for Postgres clusters. More recently, it has begun returning them for both Redis and MySQL ones as well. Creating a cluster without explicitly setting a version will use DigitalOcean's default. This change makes it so that does not return a diff when the resource is refreshed.
Successful test with this change applied:
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanDatabaseCluster_RedisNoVersion'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanDatabaseCluster_RedisNoVersion -timeout 120m
=== RUN   TestAccDigitalOceanDatabaseCluster_RedisNoVersion
--- …
```
=> Make DBaaS version required due to DigitalOcean API changes.

website/docs/d/image.html.md, website/docs/d/images.html.md, website/docs/d/project.html.md, website/docs/d/projects.html.md, website/docs/d/region.html.md, website/docs/d/regions.html.md, website/docs/d/sizes.html.md
Fix some minor issues with some of the docs updated recently. The main issue was that the bullet point documenting `filter` blocks needed a newline between it and the previous line in order to not be folded into the prior line.
=> fix some minor issues with recently-updated docs

digitalocean/resource_digitalocean_volume.go
#386 introduced validation that disallows dashes, which is allowed according to DigitalOcean's API documentation: https://developers.digitalocean.com/documentation/v2/#block-storage
We have several volumes that contain dashes, which means that with the latest version of the provider we cannot update our stack anymore, as it considers the volume names invalid. I assume this would have been caught by the acceptance tests, as they have names like `volume-abcdefghij`, but I suppose they must not have been run (or I am reading them wrong. Go is not my main language).
=> Fix volume name validation

digitalocean/import_digitalocean_kubernetes_cluster_test.go, digitalocean/resource_digitalocean_kubernetes_cluster.go, digitalocean/resource_digitalocean_kubernetes_cluster_test.go
In https://github.com/terraform-providers/terraform-provider-digitalocean/pull/365, a check was added to the `digitaloceanKubernetesClusterRead` method for the `terraform:default-node-pool` tag in order to support importing. A latter commit in that PR added a separate  `resourceDigitalOceanKubernetesClusterImportState` method that enforces this. The Kubernetes cluster data source also uses the `digitaloceanKubernetesClusterRead` method and should support accessing cluster information even if a node pool is not tagged. This PR changes the errors into warning as it is still useful for debugging.
Fixes: https://github.com/terraform-providers/terraform-provider-digitalocean/issues/399
CC @tdyas
=> Do not error out if terraform:default-node-pool tag is missing when reading k8s cluster.

digitalocean/resource_digitalocean_kubernetes_cluster_test.go
When running the acceptance tests for https://github.com/terraform-providers/terraform-provider-digitalocean/pull/401, I noticed failures due to my local kubeconfig file being used. This sets `load_config_file = false` in the test.
=> Allow running KubernetesProviderInteroperability test locally.

digitalocean/resource_digitalocean_database_connection_pool.go, digitalocean/resource_digitalocean_project.go
As mentioned in #381, DO is returning 500 when you try to create a connection pool with a name longer than 60 characters. While generally I prefer relying on DOs validation, so that the provider doesn't have to be kept up to date with whatever changes DO makes, in this case I think adding the validation to the provider is the lesser of two evils - since DO doesn't return any validation error, making it really hard to know what's wrong.
Their UI states that the name has to be between 3 and 63 characters, which is what I've encoded into the validation, assuming that they'll fix the bug and that what they say in their UI is what it's supposed to be.
I also fixed a minor typo that I accidentally spotted.
=> Validate connection pool name

digitalocean/resource_digitalocean_volume.go
In 2019, DigitalOcean accepted volumes created with underscores in the name. In 2020, this is no longer the case but it leaves us without a way to work with volumes created in the old rules.
This PR allows underscores so that I can work with a couple volumes that I had created in October or so, detailed in ~~https://github.com/hashicorp/terraform/issues/24468~~ https://github.com/terraform-providers/terraform-provider-digitalocean/issues/405
=> support volumes created before name rules changed

digitalocean/config.go, digitalocean/provider.go, digitalocean/provider_test.go, website/docs/index.html.markdown
Allow the endpoint URL used for the Spaces client to be configured via a `spaces_endpoint` argument on the provider.  The Go template replacement `{{.Region}}` will be replaced by the applicable Spaces region.
Implements https://github.com/terraform-providers/terraform-provider-digitalocean/issues/384.
=> add spaces_endpoint config to provider

digitalocean/resource_digitalocean_volume.go
Previously DigitalOcean allowed also volumes with a dot in the name, this PR make possible to manage also this case.
Related PR #404
=> support old volumes created with a dot in the name

digitalocean/resource_digitalocean_spaces_bucket.go, digitalocean/resource_digitalocean_spaces_bucket_test.go, website/docs/r/spaces_bucket.html.markdown
Support enabling bucket versioning via `versioning` configuration similar to the [`versioning` attribute](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html#versioning) of [`aws_s3_bucket`](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html).
=> digitalocean_spaces_bucket: support bucket versioning

digitalocean/resource_digitalocean_spaces_bucket_object.go, digitalocean/resource_digitalocean_spaces_bucket_object_test.go, website/docs/r/spaces_bucket_object.html.markdown
Thinking this over a bit more, `storage_class` as implemented is essentially a no-op right now.
https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/digitalocean/resource_digitalocean_spaces_bucket_object.go#L300-L305
We should remove it here to not cause confusion around Spaces support for storage classes and protect against any unforeseen ways Spaces might interact with storage classes in the future.
@tdyas, any thoughts here?
=> Remove storage_class attribute from spaces_bucket_object.

digitalocean/resource_digitalocean_spaces_bucket.go
As noted by @tdyas, the region attribute for `digitalocean_spaces_bucket` should be `ForceNew`
https://github.com/terraform-providers/terraform-provider-digitalocean/pull/411#issuecomment-612509653
=> spaces_bucket: Region attribute should be ForceNew.

digitalocean/datasource_digitalocean_spaces_bucket.go, digitalocean/datasource_digitalocean_spaces_bucket_test.go, digitalocean/datasource_digitalocean_spaces_buckets.go, digitalocean/datasource_digitalocean_spaces_buckets_test.go, digitalocean/provider.go, digitalocean/resource_digitalocean_spaces_bucket_test.go, digitalocean/spaces_buckets.go, website/digitalocean.erb, website/docs/d/spaces_bucket.html.md, website/docs/d/spaces_buckets.html.md
This PR adds `digitalocean_spaces_bucket` and `digitalocean_spaces_buckets` data sources. The attributes exported by the data sources do not include any attributes that require additional Spaces API calls to retrieve. (Subsequent PRs will add those since they will involve refactoring the resources and data sources to use common read methods. I didn't want to complicate this PR with those refactorings.)
Open question:
- It was unclear to me how to differentiate regions with Spaces and regions without. The "features" list in godo.Region does not appear to have a "spaces" feature. The closest is "storage" but both nyc1 and nyc3 have that feature, but only nyc3 has Spaces.
=> add preliminary data sources for Spaces buckets

digitalocean/datasource_digitalocean_droplet.go, digitalocean/datasource_digitalocean_droplets.go, digitalocean/datasource_digitalocean_droplets_test.go, digitalocean/droplets.go, digitalocean/provider.go, internal/datalist/schema.go, website/digitalocean.erb, website/docs/d/droplets.html.md
Adds a `digitalocean_droplets` data source.
Note: I don't have access to the VPC preview so the existing tests for the `digitalocean_droplet` data source fail when I ran those acceptance tests to ensure that the refactoring didn't cause a regression.
=> add digitalocean_droplets data source

digitalocean/resource_digitalocean_record.go, digitalocean/resource_digitalocean_record_test.go
Fixes: https://github.com/terraform-providers/terraform-provider-digitalocean/issues/421
New test failing before change:
```
asb@asb-home:~/development/gocode/src/github.com/terraform-providers/terraform-provider-digitalocean$ make testacc TESTARGS="-run='TestAccDigitalOceanRecord_iodefCAA' -parallel=20 -count=1"
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run='TestAccDigitalOceanRecord_iodefCAA' -parallel=20 -count=1 -timeout 120m
=== RUN   TestAccDigitalOceanRecord_iodefCAA
--- FAIL: TestAccDigitalOceanRecord_iodefCAA (3.81s)
testing.go:640: Step 0 error: Check failed: Check 4/7 error: digitalocean_record.CAA_iodef: Attribute 'value' …
```
=> Fix handling of CAA records with iodef tag (fixes: #421).

digitalocean/datasource_digitalocean_loadbalancer.go, digitalocean/datasource_digitalocean_loadbalancer_test.go, digitalocean/loadbalancer.go, digitalocean/resource_digitalocean_loadbalancer.go, digitalocean/resource_digitalocean_loadbalancer_test.go
Use `TypeSet` instead of `TypeList` as order is not important and add a test case for using multiple rules.
```
$ make testacc TESTARGS="-run='Loadbalancer|LoadBalancer' -parallel=20 -count=1"
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run='Loadbalancer|LoadBalancer' -parallel=20 -count=1 -timeout 120m
=== RUN   TestAccDataSourceDigitalOceanLoadBalancer_Basic
=== PAUSE TestAccDataSourceDigitalOceanLoadBalancer_Basic
=== RUN   TestAccDigitalOceanLoadBalancer_importBasic
--- PASS: TestAccDigitalOceanLoadBalancer_importBasic (111.93s)
=== RUN   TestAccDigitalOceanLoadbalancer_Basic
=== PAUSE TestAccDigitalOceanLoadbalancer_Basic
=== RUN …
```
=> load balancers: Fix support for multiple forwarding rules (fixes: #414).

website/docs/d/vpc.html.md
`.data` is required to access the example vpc data.
https://github.com/terraform-providers/terraform-provider-aws/issues/11258
=> Fixed incorrect data reference

digitalocean/datasource_digitalocean_loadbalancer.go, digitalocean/datasource_digitalocean_loadbalancer_test.go, digitalocean/resource_digitalocean_loadbalancer.go, digitalocean/resource_digitalocean_loadbalancer_test.go, website/docs/r/loadbalancer.html.markdown
https://developers.digitalocean.com/documentation/changelog/api-v2/backend-keepalive-for-load-balancers/
```
$ make testacc TESTARGS="-run='TestAccDigitalOceanLoadbalancer|TestAccDataSourceDigitalOceanLoadBalancer' -parallel=10 -count=1"
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run='TestAccDigitalOceanLoadbalancer|TestAccDataSourceDigitalOceanLoadBalancer' -parallel=10 -count=1 -timeout 120m
=== RUN   TestAccDataSourceDigitalOceanLoadBalancer_Basic
=== PAUSE TestAccDataSourceDigitalOceanLoadBalancer_Basic
=== RUN   TestAccDataSourceDigitalOceanLoadBalancer_multipleRules
=== PAUSE …
```
=> load balancers: Add support for backend keepalive (Fixes: #427).

digitalocean/resource_digitalocean_kubernetes_cluster.go, digitalocean/resource_digitalocean_kubernetes_cluster_test.go
I was able to reproduce the issue reported in #434 using the API directly. The `cluster.Status.State` is  actually:
```
"status": {
"state": "error",
"message": "requesting droplet create via droplet service: rpc error: code = Internal desc = An internal error has occurred. Please try again."
},
```
We are currently only polling for it to move to "running." We could have failed faster here instead of waiting for a timeout. While the error message returned by the API is not great, it would at least have indicated to the user that there was a problem.
```
$ make testacc TESTARGS="-run='TestAccDigitalOceanKubernetesCluster' -parallel=20 -count=1"
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v …
```
=> kubernetes: Fail faster on cluster create error (fixes: #434).

digitalocean/datasource_digitalocean_kubernetes_cluster_test.go, digitalocean/import_digitalocean_kubernetes_cluster_test.go, digitalocean/import_digitalocean_kubernetes_node_pool_test.go, digitalocean/resource_digitalocean_kubernetes_cluster_test.go, digitalocean/resource_digitalocean_kubernetes_node_pool_test.go
Since the addition of the `digitalocean_kubernetes_versions` data source, there is no longer any excuse for the hard-coded versions in the test. They need frequent updating. Let's replace them!
```
$ make testacc TESTARGS="-run='Kubernetes' -parallel=20 -count=1"
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run='Kubernetes' -parallel=20 -count=1 -timeout 120m
=== RUN   TestAccDataSourceDigitalOceanKubernetesCluster_Basic
=== PAUSE TestAccDataSourceDigitalOceanKubernetesCluster_Basic
=== RUN   TestAccDataSourceDigitalOceanKubernetesVersions_Basic
=== PAUSE TestAccDataSourceDigitalOceanKubernetesVersions_Basic
=== RUN …
```
=> kubernetes: Re-work tests to no longer rely on hard-coded versions.

digitalocean/resource_digitalocean_database_replica.go, digitalocean/resource_digitalocean_database_replica_test.go
```
$ make testacc TESTARGS="-run='DatabaseReplica' -parallel=20 -count=1"
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run='DatabaseReplica' -parallel=20 -count=1 -timeout 120m
=== RUN   TestAccDigitalOceanDatabaseReplica_importBasic
--- PASS: TestAccDigitalOceanDatabaseReplica_importBasic (478.12s)
=== RUN   TestAccDigitalOceanDatabaseReplica_Basic
=== PAUSE TestAccDigitalOceanDatabaseReplica_Basic
=== RUN   TestAccDigitalOceanDatabaseReplica_WithVPC
=== PAUSE TestAccDigitalOceanDatabaseReplica_WithVPC
=== CONT  TestAccDigitalOceanDatabaseReplica_Basic
=== CONT  TestAccDigitalOceanDatabaseReplica_WithVPC
--- PASS: …
```
=> dbaas: Add support for specifying a VPC for read-only replicas.

website/docs/r/vpc.html.markdown
With imports, it's incorrect to specify the attribute. It should just be `<resource_type>.<resource_name> ...`.
=> Fix vpc import syntax

digitalocean/datasource_digitalocean_droplets_test.go, digitalocean/droplets.go
`data.digitalocean_droplets` does not correctly set the individual Droplet IDs. For example, this config:
```
data "digitalocean_droplets" "list" {
filter {
key    = "tags"
values = ["stage"]
}
}
output "droplets" {
value = data.digitalocean_droplets.list.droplets.*.id
}
```
outputs:
```
droplets = [
0,
0,
0,
0,
0,
0,
0,
]
```
This problem only effected `data.digitalocean_droplets` as other resources call `d.SetId` explicitly. For the data list, the Droplet's ID is not the resource's ID.
New test failing before change:
```
$ make testacc TESTARGS='-run=TestAccDataSourceDigitalOceanDroplets_Basic'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDataSourceDigitalOceanDroplets_Basic -timeout 120m
? …
```
=> Set ID in flattenDigitalOceanDroplet.

digitalocean/resource_digitalocean_vpc.go
Sometimes a lag between when a resource is deleted and when it is de-registered from the VPC service can be observed. We currently will retry failed VPC delete requests for one minute before timing out. This PR raises the default to two minutes and makes it user configurable. I'm reluctant to raise the default to a much larger value as this can be a legitimate error (e.g. a Droplet created in the control panel was added to a VPC managed with Terraform).
This should help to resolve https://github.com/terraform-providers/terraform-provider-digitalocean/issues/446
=> Increase timeout on VPC deletion retry.

digitalocean/resource_digitalocean_loadbalancer.go, website/docs/r/loadbalancer.html.markdown
DigitalOcean's API supports `https` for load balancer health check configuration, but the Terraform provider does not. This fixes that and updates the documentation.
DigitalOcean API v2
=> digitalocean_loadbalancer - Adds 'https' to list of acceptable healthcheck protocols

.github/workflows/release.yml, .gitignore, .goreleaser.yml, .travis.yml, README.md
This new release pipeline has two parts:
* A Gorelaser configuration that should produce build artifacts matching the [layout required](https://www.terraform.io/docs/registry/providers/publishing.html#manually-preparing-a-release) to publish the provider in the Terraform Registry.
* A GitHub Action that workflow should be configured to automatically build and publish assets for release when a tag is pushed that matches the pattern `v*` (ie. `v0.1.0`).
Both the Goreleaser configuration and the release workflow are essentially unchanged from the version provided at:
https://github.com/hashicorp/terraform-provider-scaffolding
in order to share a consistent approach to building and releasing with other providers.
=> New Goreleaser and GitHub Actions-based release pipeline

.travis.yml, GNUmakefile
As part of the repo transition, our docs have been removed from terraform.io They now redirect to our page in the registry.
https://github.com/hashicorp/terraform-website/commit/e832984aa69102de12938775cade42cce5b9bbc3
This leads to test failures in CI. These test can be removed as they are no longer relevant.
HashiCorp has provided a tool for previewing how markdown will render on the registry.
=> Remove website-test from CI and Makefile.

digitalocean/resource_digitalocean_container_registry_docker_credentials.go, digitalocean/resource_digitalocean_container_registry_docker_credentials_test.go, website/docs/r/container_registry_docker_credentials.html.markdown
The API has placed a new upper limit on the accepted expiry seconds for registry credentials. The problem was hidden due to error response when calling `updateExpiredDockerCredentials` getting ignored.
Fixes: #466
=> registry credentials: Update default expiry and don't ignore error

digitalocean/datasource_digitalocean_images.go
This resolves #477, See the issue for more detail.
* [The API returns `created_at`](https://developers.digitalocean.com/documentation/v2/#list-all-images)
* [DO's Go client converts that to `created`](https://github.com/digitalocean/terraform-provider-digitalocean/blob/master/vendor/github.com/digitalocean/godo/images.go#L46)
* [The TF docs use `created`](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/data-sources/images)
=> Add created to SortKeys

website/docs/d/droplets.html.md, website/docs/d/images.html.md, website/docs/d/projects.html.md, website/docs/d/regions.html.md, website/docs/d/spaces_buckets.html.md
Fix some broken links in the docs by using a relative path to the linked page. Plus remove some extraneous quote marks.
=> fix broken links in docs

digitalocean/datasource_digitalocean_domains.go, digitalocean/datasource_digitalocean_domains_test.go, digitalocean/domains.go, digitalocean/provider.go, website/docs/d/domains.html.md
Add a `digitalocean_domains` data source as the list version of `digitalocean_domain`. This data source is not as useful it could be since `datalist` does not support regex or substring matching yet.
=> add digitalocean_domains data source

GNUmakefile, digitalocean/config.go, digitalocean/resource_digitalocean_database_cluster_test.go, digitalocean/resource_digitalocean_kubernetes_cluster_test.go, digitalocean/sweeper_test.go
I noticed that the acceptance test sweeper has not been running. This was this was because it does not have access to the provider's `DefaultFunc` at runtime. In particular, `DIGITALOCEAN_API_URL` was not being correctly set.
This resolves that issue as well as adding sweepers for database clusters and Kubernetes clusters.
=> Fix and extend acceptance test sweeper.

digitalocean/datasource_digitalocean_certificate.go, digitalocean/datasource_digitalocean_certificate_test.go, digitalocean/datasource_digitalocean_loadbalancer.go, digitalocean/datasource_digitalocean_loadbalancer_test.go, digitalocean/loadbalancer.go, digitalocean/resource_digitalocean_cdn.go, digitalocean/resource_digitalocean_certificate.go, digitalocean/resource_digitalocean_certificate_test.go, digitalocean/resource_digitalocean_loadbalancer.go, digitalocean/resource_digitalocean_loadbalancer_test.go, website/docs/d/certificate.html.md, website/docs/r/cdn.html.markdown, website/docs/r/certificate.html.markdown, website/docs/r/loadbalancer.html.markdown
This builds on the work originally done by @snormore in https://github.com/digitalocean/terraform-provider-digitalocean/pull/320 making `name` the primary identifier for a certificate. This is needed as when the certificate type is lets_encrypt, the certificate ID will change on renewal (after 3 months). 
This goes further than that PR in a few ways:
* It uses v0.12 Terraform SDK [state migrations](https://www.terraform.io/docs/extend/resources/state-migration.html#terraform-v0-12-sdk-state-migrations) rather than the older v0.11 `StateUpgrader`.
* It handles the changes needed in the `digitalocean_cdn` resource as well as the `digitalocean_loadbalancer` and `digitalocean_certificate` resources.
* For  `digitalocean_cdn` and `digitalocean_loadbalancer`, it deprecates the `certificate_id` …
=> Use certificate name as primary identifier instead of ID

digitalocean/datasource_digitalocean_droplet.go, digitalocean/datasource_digitalocean_image.go, digitalocean/datasource_digitalocean_project.go, digitalocean/datasource_digitalocean_records.go, digitalocean/datasource_digitalocean_records_test.go, digitalocean/datasource_digitalocean_region.go, digitalocean/datasource_digitalocean_sizes.go, digitalocean/datasource_digitalocean_spaces_bucket.go, digitalocean/datasource_digitalocean_tags.go, digitalocean/domains.go, digitalocean/droplets.go, digitalocean/images.go, digitalocean/projects.go, digitalocean/provider.go, digitalocean/records.go, digitalocean/regions.go, digitalocean/spaces_buckets.go, docs/data-sources/records.md, internal/datalist/schema.go
Adds a `digitalocean_records` data source to access DNS records of a domain.
Note: This PR modifies the `datalist` package to support "extra queries." I've exposed that by having an alternate set of callbacks that take a `*schema.ResourceData`. It might be better to just port the existing datalist uses to take that argument and avoid having two sets of functions. Thoughts?
=> add digitalocean_records data source

docs/data-sources/domains.md, docs/data-sources/records.md
Fix copy/paste leftovers in the `digitalocean_domains` and `digitalocean_records` data sources. Also corrects the example in `digitalocean_records` to use a "list splat" correctly, and demonstrates using a regular expression match in the `digitalocean_domains` example.
=> fix docs for digitalocean_domains and digitalocean_records data sources

digitalocean/app_spec.go, digitalocean/resource_digitalocean_app_test.go
The API does not consistently return `"type":"GENERAL"` when set for an environment variable. This leads to changes shown on each run if an env var type is set to `GENERAL`. As being unset and being set to `GENERAL` are functionally, the same, we can safely ignore the diff.
Resolves one issue mentioned in #514
Test failure with the test change adding ` type  = "GENERAL"`:
```
$ make testacc TESTARGS="-run='TestAccDigitalOceanApp_Envs'"==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run='TestAccDigitalOceanApp_Envs' -timeout 120m
=== RUN   TestAccDigitalOceanApp_Envs
=== PAUSE TestAccDigitalOceanApp_Envs
=== CONT  TestAccDigitalOceanApp_Envs …
```
=> apps: Suppress diff when env type is GENERAL.

digitalocean/datasource_digitalocean_container_registry.go, digitalocean/datasource_digitalocean_container_registry_test.go, digitalocean/import_digitalocean_container_registry_test.go, digitalocean/resource_digitalocean_container_registry.go, digitalocean/resource_digitalocean_container_registry_docker_credentials_test.go, digitalocean/resource_digitalocean_container_registry_test.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/CONTRIBUTING.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/domains.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/firewalls.go, vendor/github.com/digitalocean/godo/floating_ips.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/images.go, vendor/github.com/digitalocean/godo/invoices.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/github.com/digitalocean/godo/projects.go, vendor/github.com/digitalocean/godo/registry.go, vendor/github.com/digitalocean/godo/storage.go, vendor/github.com/digitalocean/godo/strings.go, vendor/github.com/digitalocean/godo/vpcs.go, vendor/modules.txt
When registry support went into general availability, it added the requirement of specifying a subscription plan. This adds the `subscription_tier_slug` to both the resource and data source allowing it to be specified on create and updated.
```
$ make testacc TESTARGS=-run='ContainerRegistry'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=ContainerRegistry -timeout 120m
=== RUN   TestAccDataSourceDigitalOceanContainerRegistry_Basic
=== PAUSE TestAccDataSourceDigitalOceanContainerRegistry_Basic
=== RUN   TestAccDigitalOceanContainerRegistry_importBasic
--- PASS: TestAccDigitalOceanContainerRegistry_importBasic (19.08s)
=== RUN …
```
=> Fix container registry creation and support updating subscription plans.

digitalocean/datasource_digitalocean_ssh_key.go, digitalocean/datasource_digitalocean_ssh_keys.go, digitalocean/datasource_digitalocean_ssh_keys_test.go, digitalocean/provider.go, digitalocean/ssh_keys.go, docs/data-sources/ssh_keys.md
Fixes: #518
```
▶ TF_ACC=1 go test -v -tags=go -parallel 4 -timeout 2h --run=TestAccDataSourceDigitalOceanSSHKeys
=== RUN   TestAccDataSourceDigitalOceanSSHKeys_Basic
=== PAUSE TestAccDataSourceDigitalOceanSSHKeys_Basic
=== CONT  TestAccDataSourceDigitalOceanSSHKeys_Basic
--- PASS: TestAccDataSourceDigitalOceanSSHKeys_Basic (9.75s)
PASS
ok  	github.com/digitalocean/terraform-provider-digitalocean/digitalocean	9.766s
terraform-providers/terraform-provider-digitalocean/digitalocean  ssh_keys_datasource ✗                                                                                                                                                                                9m ⚑
▶ TF_ACC=1 go test -v -tags=go -parallel 4 -timeout 2h --run=TestAccDataSourceDigitalOceanSSHKey_
=== RUN …
```
=> Adding a datasource for listing all SSH Keys

digitalocean/resource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_database_cluster_test.go, docs/resources/database_cluster.md
Redis 5 clusters can no longer be created. For backwards compatibility the API allows for POST requests that specify "5" for the version, but a Redis 6 cluster is actually created. The response body specifies "6" for the version. This should be handled without Terraform attempting to recreate the cluster.
Acceptance test failure without change:
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanDatabaseCluster_oldRedisVersion'==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanDatabaseCluster_oldRedisVersion -timeout 120m
=== RUN   TestAccDigitalOceanDatabaseCluster_oldRedisVersion
=== PAUSE …
```
=> database_cluster: Handle Redis version change with DiffSuppressFunc.

.goreleaser.yml
When HashiCorp managed the build and distribution of the module directly, they provided OpenBSD binaries. Looking back at the last release before the transition to the registry distribution model, they were provided for i386 and amd64. So I've skipped the ARM builds for OpenBSD. This also matches with the OpenBSD support for Terraform binaries provided by HashiCorp: https://www.terraform.io/downloads.html
```
curl 'https://registry.terraform.io/v1/providers/terraform-providers/digitalocean/versions' | jq '.versions[]  | select(.version=="1.20.0") | .platforms[] | select(.os=="openbsd")'
{
"os": "openbsd",
"arch": "386"
}
{
"os": "openbsd",
"arch": "amd64"
}
```
Closes: #533
=> goreleaser: Build OpenBSD binaries.

digitalocean/datasource_digitalocean_kubernetes_cluster_test.go, digitalocean/import_digitalocean_kubernetes_cluster_test.go, digitalocean/import_digitalocean_kubernetes_node_pool_test.go, digitalocean/resource_digitalocean_kubernetes_cluster_test.go, digitalocean/resource_digitalocean_kubernetes_node_pool_test.go
This update the k8s versions used in acceptance tests as 1.16.x is no longer available for new clusters:
```
$ doctl kubernetes options versions 
Slug            Kubernetes Version
1.19.3-do.2     1.19.3
1.18.10-do.2    1.18.10
1.17.13-do.2    1.17.13
```
```
$ make testacc TESTARGS='-run=Kubernetes -count=1 -parallel=10'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=Kubernetes -count=1 -parallel=10 -timeout 120m
=== RUN   TestAccDataSourceDigitalOceanKubernetesCluster_Basic
=== PAUSE TestAccDataSourceDigitalOceanKubernetesCluster_Basic
=== RUN   TestAccDataSourceDigitalOceanKubernetesVersions_Basic
=== PAUSE …
```
=> k8s: Update k8s versions used in acceptance tests.

digitalocean/resource_digitalocean_image.go, digitalocean/resource_digitalocean_image_test.go, docs/resources/custom_image.md, go.mod, go.sum
Signed-off-by: Noel Georgi <git@frezbo.com>
* Fixes the doc update that was missed in the initial implementation.
* Pulls in the changes to update `description` and `distribution` from https://github.com/digitalocean/godo/pull/413
=> Docs update and custom image options update

docs/resources/kubernetes_cluster.md, docs/resources/kubernetes_node_pool.md
Thank you for creating such great documentation!
However, when I try to create a kubernetes cluster using the following as a reference, I get the error.
Referred: 
https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/kubernetes_cluster
https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/kubernetes_node_pool
result: 
```
Error: Error creating Kubernetes cluster: POST https://api.digitalocean.com/v2/kubernetes/clusters: 422 validation error: invalid version slug
```
This is probably due to the fact that it is an older version and is not supported.
So I changed to the current latest version and it works fine now.
What do you feel about this PR?
Thanks!
=> bump kubernetes version to 1.19.3-do.3

digitalocean/app_spec.go
An app env var's `type` can be `GENERAL` or `SECRET`. Unfortunately there is not a way to set an attribute on one field based on an attribute from another. So we should error on the side of safely, and treat all env var values as sensitive when it comes to logging.
=> apps: Mark env var values as sensitive (Closes: #554).

digitalocean/provider.go, digitalocean/resource_digitalocean_vpc.go, digitalocean/resource_digitalocean_vpc_test.go, internal/mutexkv/mutexkv.go, internal/mutexkv/mutexkv_test.go
This prevents parallel creation of VPCs in the same region to protect against race conditions in IP range assignment. Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/551
It creates an internal copy of the mutexkv package that had previously been part of the Terraform SDK. This is the same strategy employed by other providers.
https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#removal-of-helper-mutexkv-package
> Providers that need the functionality provided by the `helper/mutexkv` package are encouraged to copy the types and functions it provided into their own codebase, provided here under a public domain license
Before change, the new test fails with:
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanVPC_IPRangeRace'
==> Checking that code …
```
=> vpcs: Protect against race conditions in IP range assignment.

digitalocean/app_spec.go, digitalocean/resource_digitalocean_app_test.go, docs/resources/app.md, go.sum
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanApp_Envs'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanApp_Envs -timeout 120m
=== RUN   TestAccDigitalOceanApp_Envs
=== PAUSE TestAccDigitalOceanApp_Envs
=== CONT  TestAccDigitalOceanApp_Envs
--- PASS: TestAccDigitalOceanApp_Envs (289.69s)
PASS
ok      github.com/digitalocean/terraform-provider-digitalocean/digitalocean    289.695s
testing: warning: no tests to run
PASS
ok      github.com/digitalocean/terraform-provider-digitalocean/internal/datalist       (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok …
```
=> apps: Add support for global env vars (Fixes: #549).

docs/resources/kubernetes_cluster.md
Happened to notice that some of the blocks on this page aren't using syntax highlighting
https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/kubernetes_cluster#autoscaling-example
=> docs: Use HCL highlighting on k8s examples.

.gitignore, digitalocean/resource_digitalocean_kubernetes_cluster_test.go, docs/data-sources/kubernetes_cluster.md, docs/resources/container_registry_docker_credentials.md, docs/resources/kubernetes_cluster.md, examples/kubernetes/README.md, examples/kubernetes/doks-cluster/main.tf, examples/kubernetes/doks-cluster/outputs.tf, examples/kubernetes/doks-cluster/variables.tf, examples/kubernetes/kubernetes-config/main.tf, examples/kubernetes/kubernetes-config/variables.tf, examples/kubernetes/main.tf, examples/kubernetes/outputs.tf, examples/kubernetes/variables.tf
As seen in https://github.com/digitalocean/terraform-provider-digitalocean/issues/562, using interpolation to pass credentials to the Kubernetes provider from other resources can cause some issues due to the order in which Terraform evaluates the provider blocks vs. actual resources. In fact, the Kubernetes provider docs have added a warning to discourage using interpolation to pass credentials: 
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#stacking-with-managed-kubernetes-cluster-resources
This PR expands the Kubernetes example in this repo to be more complete and better adhere to best practices for interacting with the Kubernetes provider. It also adds a notes to the Kubernetes cluster resource docs addressing the issue and linking to that example. Finally, …
=> kubernetes: Expand example to show best practices for interacting with k8s provider.

digitalocean/app_spec.go, digitalocean/resource_digitalocean_app_test.go
This PR addresses #567 by allowing multiple routes for a service or static site. As workers and jobs are not publicly rotatable, this moves the attribute out of the `appSpecComponentBase()` and directly into `appSpecServicesSchema()` and `appSpecStaticSiteSchema()`
=> apps: Allow multiple routes (Closes: #567).

digitalocean/app_spec.go, digitalocean/datasource_digitalocean_app.go, digitalocean/resource_digitalocean_app.go, digitalocean/resource_digitalocean_app_test.go
This builds off of the work by @acraven in https://github.com/digitalocean/terraform-provider-digitalocean/pull/544 It deprecates the `domains` array in favor of a `domain` block that supports additional features like wildcard domains. Existing users of `domains` should not see any behavior change, only a deprecation warning.
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanApp_Domain'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanApp_Domain -timeout 120m
=== RUN   TestAccDigitalOceanApp_Domain
=== PAUSE TestAccDigitalOceanApp_Domain
=== RUN   TestAccDigitalOceanApp_DomainsDeprecation
=== PAUSE …
```
=> apps: Deprecate domains list in favor of domain block.

digitalocean/app_spec.go, digitalocean/resource_digitalocean_app_test.go
The digitalocean_app spec was also missing the internal_ports attribute on a service, this should fix this. Acceptance test (`TestAccDigitalOceanApp_InternalPort`) is passing
internal_ports are specified like `internal_ports = ["5000"]`, maybe an array syntax
```
internal_port {
port = 5000
}
internal_port {
port = 2000
}
```
would be preferred, similarly to the routes attribute. not sure.
=> App: internal ports array attribute

digitalocean/resource_digitalocean_cdn.go, digitalocean/resource_digitalocean_cdn_test.go
This resolves a bug introduced in https://github.com/digitalocean/terraform-provider-digitalocean/pull/500. We made changes to use certificate names as primary identifier instead of IDs. This included the CDN resource, but I missed the update flow for CDNs. We did not have an acceptance test excercising using CDNs with custom domains/certificates.
The new test fails before the code changes are appiled:
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanCDN_CustomDomain'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanCDN_CustomDomain -timeout 120m
=== RUN   TestAccDigitalOceanCDN_CustomDomain
=== PAUSE …
```
=> cdn: Handle certificate name updates.

digitalocean/resource_digitalocean_container_registry_docker_credentials.go, docs/resources/container_registry_docker_credentials.md
The `updateExpiredDockerCredentials` function gets called when the state is being refreshed, but the change to the configuration is not available at refresh. So you can encounter a situation like #581 where a bad value has been set in state but the validation prevents the value from being corrected. We should prevent the bad value from ever being entered in the first place.
Fixes: #581
=> Fix docs and validation for expiry_seconds on registry docker credentials resource.

docs/resources/kubernetes_cluster.md, docs/resources/kubernetes_node_pool.md
Hi!
Thanks for provide great documentation.
Currently, choosable latest kubernetes version is "1.20.2-do.0"  also "1.19.3-do.3" is already abolished.
```
❯ doctl kubernetes o versions                                                                                                                                              [10:27:36]
Slug            Kubernetes Version
1.20.2-do.0     1.20.2
1.19.6-do.0     1.19.6
1.18.14-do.0    1.18.14
```
Error
```
Error: Error creating Kubernetes cluster: POST https://api.digitalocean.com/v2/kubernetes/clusters: 422 validation error: invalid version slug
```
I've updated documentation content.
What do you feel about this PR?
Thanks!
=> bump kubernetes version

docs/resources/database_replica.md
Looks like we missed documenting these attributes:
`private_network_uuid`: https://github.com/digitalocean/terraform-provider-digitalocean/blob/2c4bf56fe1da163346f8bfa98ec9dbb996355b3b/digitalocean/resource_digitalocean_database_replica.go#L52
`tags`: https://github.com/digitalocean/terraform-provider-digitalocean/blob/2c4bf56fe1da163346f8bfa98ec9dbb996355b3b/digitalocean/resource_digitalocean_database_replica.go#L103
=> dbaas replica: Add missing attributes to docs.

digitalocean/datasource_digitalocean_projects_test.go, digitalocean/resource_digitalocean_project.go, digitalocean/resource_digitalocean_project_resources.go, digitalocean/set.go, digitalocean/set_test.go
The current implementation moves all resources in the old config to the default project and then adds the resources in the new config to the Terraform-managed project. This creates a lot of unnecessary churn.
https://github.com/digitalocean/terraform-provider-digitalocean/blob/2c4bf56fe1da163346f8bfa98ec9dbb996355b3b/digitalocean/resource_digitalocean_project.go#L208-L209
This PR adds a helper function to compares two `*schema.Set`s, producing lists of which should be added and which should be removed. Resources that were in both the old and new configs will no longer be touched.
Fixes: #585
=> Assign and remove project resources without unnecessary churn (Fixes: #585).

digitalocean/resource_digitalocean_kubernetes_cluster.go
Description: Now that surge upgrades is stable, enable surge upgrades by default as it is a better user experience during upgrades.
cc @adamwg
=> kubernetes - enable surge upgrades by default during cluster creation

.github/workflows/test.yml, digitalocean/resource_digitalocean_kubernetes_cluster.go
Run tests on `pull_request` not `pull_request_target` to  prevent failures like this from only being found after merge into main.
https://github.com/digitalocean/terraform-provider-digitalocean/runs/1936909608?check_suite_focus=true
=> Run tests on pull_request not pull_request_target.

README.md, docs/data-sources/loadbalancer.md, docs/resources/droplet.md, examples/droplet/README.md
Several broken links remain after the docs restructuring in PR #501.
This commit serves to update those links to point to the correct pages.
=> Fix broken documentation links

docs/resources/kubernetes_cluster.md
The existing statement is not accurate as specifying a node pool
min_nodes to 0 will result in the following error.
```
422 validation error: worker_node_pool_spec.min nodes must be greater than or equal to 1
```
For clarity sake I got this error when adding a 2nd node pool with autoscaling to an existing cluster.  So the cluster itself had other nodes.
=> Update the statement below the autoscaling example

digitalocean/resource_digitalocean_loadbalancer.go, digitalocean/resource_digitalocean_loadbalancer_test.go
Load balancers can now be resized: https://www.digitalocean.com/docs/release-notes/#march-16
Note that since load balancers can only be resized once an hour, and the initial create counts as a "resize" in this context. This test can't actually perform a resize, but it does ensure that the the PUT includes the expected content by checking for the failure.
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanLoadbalancer_resizeExpectedFailure'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanLoadbalancer_resizeExpectedFailure -timeout 120m
=== RUN   TestAccDigitalOceanLoadbalancer_resizeExpectedFailure
=== PAUSE …
```
=> load balancers: Allow resizing without ForceNew.

digitalocean/resource_digitalocean_image.go
When we initiate an import of a custom image, we poll until it becomes `available`. If there is a problem with the image its status moves to `deleted` and an `error_message` is populated.  We do not currently surface that error message to users. It's only visible in the debug logging for the API requests.
After this PR, error message should be more helpful. E.g.
> Error: Error waiting for image (81502973) to become ready: We had a problem decompressing your file. This typically happens if the archive is corrupt or contains multiple files. Please try decompressing the file locally and uploading the uncompressed image, or recompressing using gzip or bzip2.
=> custom_image: Surface a better error to users if image import fails.

digitalocean/datasource_digitalocean_database_cluster.go, digitalocean/datasource_digitalocean_database_cluster_test.go, digitalocean/resource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_database_cluster_test.go
Support for the MongoDB beta.
MongoDB clusters only return their password in response to the initial POST. This means they need to be handled differently than other database clusters:
- We need to set the password to state directly in the create function before doing any polling for status.
- As the host for the cluster is not known until it becomes available, we must save the password and then add it to the URL returned latter to build a usable connection URI.
=> database cluster: Handle MongoDB password differences.

digitalocean/config.go, digitalocean/datasource_digitalocean_spaces_bucket.go, digitalocean/datasource_digitalocean_spaces_bucket_object.go, digitalocean/datasource_digitalocean_spaces_bucket_object_test.go, digitalocean/datasource_digitalocean_spaces_bucket_objects.go, digitalocean/datasource_digitalocean_spaces_bucket_test.go, digitalocean/resource_digitalocean_spaces_bucket.go, digitalocean/resource_digitalocean_spaces_bucket_object.go, digitalocean/resource_digitalocean_spaces_bucket_object_test.go, digitalocean/resource_digitalocean_spaces_bucket_test.go, digitalocean/spaces_buckets.go
Do some input validation on the region for Spaces operations as the `no such host` error message is not helpful. The new error would be:
```
Error: expected region to be one of [nyc3 sfo2 sfo3 ams3 sgp1 fra1], got ny2
on main.tf line 21, in resource "digitalocean_spaces_bucket" "i-dont-exist":
21:   region = "ny2"
```
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/617
=> spaces: Validate input for region.

digitalocean/datasource_digitalocean_kubernetes_cluster.go, digitalocean/datasource_digitalocean_kubernetes_cluster_test.go, digitalocean/resource_digitalocean_kubernetes_cluster.go, digitalocean/resource_digitalocean_kubernetes_cluster_test.go, docs/data-sources/kubernetes_cluster.md, docs/resources/kubernetes_cluster.md, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/sizes.go, vendor/github.com/digitalocean/godo/vpcs.go, vendor/modules.txt
Simplify  Kubernetes clusters project assignment.
Follows up on: https://github.com/digitalocean/godo/pull/441
Related to: https://github.com/digitalocean/terraform-provider-digitalocean/issues/469
=> Expose URNs for Kubernetes clusters.

.github/workflows/release.yml
HashiCorp forked the action we are using to import our GPG key to sign releases. This moves to it so that it is controlled by a trusted organization, not an individual.
Context: https://github.com/hashicorp/terraform-provider-scaffolding/issues/22
=> Use hashicorp/ghaction-import-gpg in release workflow.

docs/index.md
The example on the index page of our docs does not show the needed `required_providers` block.
This also adds a note for module developers about the  need to include the `required_providers` block in children modules. Rather than go into detail on module development here, I link out to the main Terraform module development docs as the cover it in much more depth than we can or should on this page.
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/636
=> Cover required_providers in the main docs.

digitalocean/resource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_kubernetes_cluster.go, digitalocean/resource_digitalocean_kubernetes_cluster_test.go, digitalocean/resource_digitalocean_kubernetes_node_pool.go
DBaaS and K8s clusters can take awhile to come online. This PR makes the timeouts for them user configurable. It also bumps up the default K8s create timeout to 30 minutes.
Fixes: #329
=> Make create timeouts configurable for DBaaS and K8s clusters.

digitalocean/datasource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_database_cluster_test.go, digitalocean/resource_digitalocean_database_replica.go, digitalocean/tags.go
There seems to have been a change in the DBaaS API. It is now returning:
```
"tags": [
""
]
```
in the response body for MongoDB clusters without any tags applied. This is wrong, but we should still protect against this here. Without doing so, we end up with a diff and a failing acceptance test:
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanDatabaseCluster_MongoDBPassword'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDigitalOceanDatabaseCluster_MongoDBPassword -timeout 120m
=== RUN   TestAccDigitalOceanDatabaseCluster_MongoDBPassword
=== PAUSE TestAccDigitalOceanDatabaseCluster_MongoDBPassword
=== CONT …
```
=> dbaas: Protect against setting empty tags.

digitalocean/datasource_digitalocean_database_cluster.go, digitalocean/datasource_digitalocean_droplet_snapshot.go, digitalocean/datasource_digitalocean_loadbalancer.go, digitalocean/datasource_digitalocean_tags.go, digitalocean/datasource_digitalocean_volume.go, digitalocean/datasource_digitalocean_volume_snapshot.go, digitalocean/datasource_digitalocean_vpc.go, digitalocean/kubernetes.go, digitalocean/loadbalancer.go, digitalocean/resource_digitalocean_project.go
More details about the pattern are given in https://staticcheck.io/docs/checks#S1011
I found the matches with `staticcheck . | grep S1011` inside the digitalocean directory.
**Edit**: Same with S1031.
=> Simplified some loops based on go-staticcheck S1011

digitalocean/resource_digitalocean_record.go, digitalocean/resource_digitalocean_record_test.go
Fixes: #664 
`@` is synonymous with for the current domain. There are some places in the API where the full value may be supplied but `@` is returned. We need to compensate for that using a `DiffSuppressFunc`. We have something similar in place for the `value` attribute, but for some record types this behavior can be with the  `name` attribute as well. 
https://github.com/digitalocean/terraform-provider-digitalocean/blob/4fdccb665316809b4e797bd263b019142ac1af85/digitalocean/resource_digitalocean_record.go#L89-L93
This also required a change to the `constructFqdn` function to prevent output like `@.example.com`
=> Fix unexpected diffs for when TXT records are for the apex domain

digitalocean/resource_digitalocean_record.go, digitalocean/resource_digitalocean_record_test.go
Fixes: #670 
We're doing validation inside of a `CustomizeDiff` function. The interpolated values are not available there on plan. This prevents user from doing things like referencing a database cluster's port in a SRV record. This is similar to hashicorp/terraform-provider-consul#260 This PR moves that validation to later in the process.
This has one side effect. The reason for using a `CustomizeDiff` for something like this is that it allows you to error out early before any of the plan runs. Now the error will not happen until the record is being created. I don't love that, but not sure I see a better way to do it.
=> record: Move validation by type out of CustomizeDiff.

digitalocean/resource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_database_user.go, digitalocean/resource_digitalocean_database_user_test.go
MongoDB clusters only return the password in response to the initial POST. We handle this in the database resource for the default user, but it looks like we missed it for new users created in with the database user resource.
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/696
I was also seeing an expected diff preventing the tests from passing  when seconds were being included in response for database maintenance windows, e.g: "13:00" -> "13:00:00". I've added a DiffSuppressFunc to handle this case.
=> database user: Handle passwords for MongoDB.

docs/resources/app.md
This updates the docs to provide more context around an apps' `instance_size_slug`. This addresses the last two points in https://github.com/digitalocean/terraform-provider-digitalocean/issues/686 The alerts piece has its own issue (https://github.com/digitalocean/terraform-provider-digitalocean/issues/683) and the CORS piece will be closed in https://github.com/digitalocean/terraform-provider-digitalocean/pull/699. So I think we're good to close that issue.
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/686
=> docs: Provide more context for apps' 'instance_size_slug'

docs/resources/monitor_alert.md
Resource name in the docs should be `digitalocean_monitor_alert` instead of `digitalocean_monitoring` according to what https://github.com/digitalocean/terraform-provider-digitalocean/pull/679 introduced in v2.12.0
=> docs: Fix typo in digitalocean monitoring

CHANGELOG.md
It's a bit annoying that the live docs can't be updated without cutting a release. Since this has tripped up a few people now, it's worth doing.
=> Prep v2.12.1 bugfix release.

digitalocean/datasource_digitalocean_tags.go
Fixes a regression introduced in 35e97db3 (2.11.0). Previously, any use of `digitalocean_tags` would fail with an interface conversion error:
```
Stack trace from the terraform-provider-digitalocean_v2.12.1 plugin:
panic: interface conversion: interface {} is []godo.Tag, not godo.Tag
goroutine 27 [running]:
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.flattenDigitalOceanTag(0xef8d80, 0xc000522f18, 0xf67880, 0xc00059ae40, 0xc000827aa0, 0x1, 0x0, 0x0)
github.com/digitalocean/terraform-provider-digitalocean/digitalocean/datasource_digitalocean_tags.go:79 +0x458
github.com/digitalocean/terraform-provider-digitalocean/internal/datalist.dataListResourceRead.func1(0x1242f78, 0xc000140d80, 0xc00019d200, 0xf67880, 0xc00059ae40, 0xc000762ab0, 0xc0003a5
948, 0x40e0f8) …
```
=> Fix tag collection in digitalocean_tags data source

digitalocean/datasource_digitalocean_database_ca.go, digitalocean/datasource_digitalocean_database_ca_test.go, digitalocean/provider.go, docs/data-sources/database_ca.md
This PR adds a data source for retrieving the CA certificate for a database cluster. 
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/388
=> Add digitalocean_database_ca data source.

.github/workflows/acceptance-test-schedule.yml
This workflow runs the acceptance tests every weekday at 14:00 UTC (10a Eastern)
=> Add scheduled acceptance test runs

digitalocean/resource_digitalocean_certificate_test.go
We have a number of new acceptance test failures around certificates. The API recently began enforcing that customer certificates use private keys using a minimum of 2048 bits (RSA) or 224 bits (ECDSA). The dummy test data we've been generating is only 1024 bits. This fixes these errors:
```
=== CONT  TestAccDigitalOceanLoadbalancer_sslCertByName
resource_digitalocean_loadbalancer_test.go:404: Step 1/1 error: Error running apply: exit status 1
Error: Error creating Certificate: POST https://api.digitalocean.com/v2/certificates: 422 (request "242f60e5-2a57-48fe-83ff-2f84b5d4c82e") Invalid certificate data: the provided private key is not a minimum of 2048 bits (RSA) or 224 bits (ECDSA)
with digitalocean_certificate.foobar,
on terraform_plugin_test.tf line 2, in resource …
```
=> Acceptance tests: Use 2048 bit private keys in test data.

digitalocean/resource_digitalocean_floating_ip_test.go, digitalocean/resource_digitalocean_volume_attachment_test.go, digitalocean/resource_digitalocean_volume_test.go, docs/resources/project.md, docs/resources/project_resources.md
These size slugs pointing to legacy Droplet plans have been deprecated and are not available on most accounts. This leads to test failures when run under the new acceptance testing account.
=> Acceptance tests: Don't use deprecated size slugs.

.github/workflows/acceptance-test-schedule.yml, .github/workflows/test.yml
This sets the [concurrency group](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency) for the acceptance test job and workflow to ensure only one runs at any given time.
=> Limit acceptance test job/workflow to single run at a time

go.mod, go.sum, vendor/modules.txt
Fixes build failure:
https://github.com/digitalocean/terraform-provider-digitalocean/runs/4072779143?check_suite_focus=true#step:6:59
```
⨯ release failed after 15.59s error=failed to get module path: exit status 1: go: inconsistent vendoring in /home/runner/work/terraform-provider-digitalocean/terraform-provider-digitalocean:
github.com/hashicorp/go-uuid@v1.0.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
To ignore the vendor directory, use -mod=readonly or -mod=mod.
To sync the vendor directory, run:
go mod vendor
```
=> go mod vendor; go mod tidy

digitalocean/firewalls.go, docs/resources/firewall.md
Add `source_kubernetes_ids` and `destination_kubernetes_ids` attributes to firewall rules.
=> add attributes for kubernetes cluster IDs to firewall rules

digitalocean/resource_digitalocean_vpc.go, digitalocean/resource_digitalocean_vpc_test.go
The PUT request for updating a VPC needs to include the `default` attribute even if it is not changed in order to support updating  the name or description of a region's default vpc.
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/747
=> vpc: Allow updating name and description of default vpcs.

.github/workflows/acceptance-test-schedule.yml, .github/workflows/test.yml, digitalocean/datasource_digitalocean_domain_test.go, digitalocean/datasource_digitalocean_domains_test.go, digitalocean/datasource_digitalocean_record_test.go, digitalocean/datasource_digitalocean_records_test.go, digitalocean/import_digitalocean_domain_test.go, digitalocean/import_digitalocean_record_test.go, digitalocean/provider_test.go, digitalocean/resource_digitalocean_domain_test.go, digitalocean/resource_digitalocean_project_test.go, digitalocean/resource_digitalocean_record_test.go
I noticed domain resources aren't getting cleaned up after acceptance tests but it's difficult to identify which tests aren't properly cleaning up after themselves.
This change includes a few things to help diagnose as well clean up:
1. Update the domains resource sweeper to use match resources with the common `testNamePrefix` (a const value set in the [digitalocean/provider_test.go#L17](https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/digitalocean/provider_test.go#L17))
2. Update the names used for domains in tests to call `randomTestName()` (which uses the above common prefix)
3. Extended `randomTestName()` to allow a list of strings that will get concatenated with `-` (and will replace spaces with `_`). 
* **_I'm curious what thoughts there are on this_**. I …
=> Update domains sweeper

GNUmakefile
The other packages don't import `github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource`, so that leads to failures when the sweeper is ran. E.g.
https://github.com/digitalocean/terraform-provider-digitalocean/runs/4565075328?check_suite_focus=true#step:4:205
=> Makefile: Only run sweep against the digitalocean package.

docs/data-sources/database_cluster.md
Remove an incorrect comment from the `digitalocean_database_cluster` data source example
=> Fix database cluster documentation

digitalocean/resource_digitalocean_database_cluster.go
After calling the following POST endpoint to create database cluster, database cluster should be created and calling GET endpoint should be succeeded
https://github.com/digitalocean/terraform-provider-digitalocean/blob/v2.14.0/digitalocean/resource_digitalocean_database_cluster.go#L248
But, according to #728, 404 error occurs occasionally when calling GET endpoint in the following line
https://github.com/digitalocean/terraform-provider-digitalocean/blob/v2.14.0/digitalocean/resource_digitalocean_database_cluster.go#L483
This PR is the workaround for this issue
=> Fixed issue about database cluster

digitalocean/import_digitalocean_floating_ip_assignment_test.go, digitalocean/resource_digitalocean_floating_ip_assignment.go, digitalocean/resource_digitalocean_floating_ip_assignment_test.go, docs/resources/floating_ip_assignment.md
`floating_ip_assignment` resources currently use [`schema.ImportStatePassthrough`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema#ImportStatePassthroughContext) for importing. This is meant for use when an ID-only refresh is possible. It would have never worked for this resource which needs both the floating IP and the Droplet ID. 
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/763
=> floating_ip_assignment: Properly support importing existing assignments.

docs/resources/record.md
As discussed in https://github.com/digitalocean/terraform-provider-digitalocean/issues/769, using the domain's `id` instead of its `name` can be useful to ensure a record is recreated when a domain is.
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/769
=> docs: Update records examples to use domain id over name.

digitalocean/datasource_digitalocean_loadbalancer.go, digitalocean/datasource_digitalocean_loadbalancer_test.go, docs/data-sources/loadbalancer.md
Issue: https://github.com/digitalocean/terraform-provider-digitalocean/issues/772
Currently we can fetch loadbalancer resource in datasource by only its name.
https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/data-sources/loadbalancer
By this update, we will be able to fetch loadbalancer resource by its ID in addition to name like below.
```
data "digitalocean_loadbalancer" "example" {
id = "loadbalancer_id"
}
```
This update is referring to the following droplet datasource.
https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/digitalocean/datasource_digitalocean_droplet.go#L40
=> Fetch loadbalancer resource in datasource by ID

digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_droplet_test.go
This PR refactors the code used to poll a Droplet's status after the request to create it. https://github.com/digitalocean/terraform-provider-digitalocean/pull/767 points out one issue with the existing implementation, but it also exposes another issue with it. So I've taken the opportunity to fix those and make the entire process more efficient.
It now first uses `waitForAction` to ensure that the Droplet create action completes successfully. This allows us to fail fast in the case of a real error instead of continuing to poll the non-existent Droplet. Polling the action endpoint allows for an error to be reported while polling the droplet endpoint just 404s (which we retry on) if the create fails.
The call to `waitForDropletAttribute` checking for the Droplet's `status` attribute to …
=> droplet: Refactor post-create polling code.

docs/resources/monitor_alert.md
A few small docs updates for the `digitalocean_monitor_alert` resource including making it a bit more prominent that it currently only supports Droplets.
fixes: #780
=> monitor_alert: Docs update (fixes: #780).

digitalocean/app_spec.go, docs/data-sources/app.md, docs/resources/app.md
This change adds `MONGODB` as an `engine` option to the `databases` block of an App spec. It's necessary for anyone wishing to attach an already-existing managed MongoDB cluster to an App Platform app.
From the [DigitalOcean docs](https://docs.digitalocean.com/products/app-platform/#limits): 
> App Platform’s engine support for dev databases is currently limited to PostgresSQL, but you can create a PostgresSQL, MySQL, Redis, or MongoDB managed database with DigitalOcean for use in your app.
Here's a working plan file that uses this change to provision a managed MongoDB cluster and then an App Platform app with a named reference (`db`) to it:
```tf
terraform {
required_providers {
digitalocean = {
source = "digitalocean/digitalocean"
version = "~> 2.0"
}
}
}
variable "do_token" {
type = …
```
=> Add MONGODB as a database engine option

digitalocean/import_digitalocean_project_test.go, digitalocean/resource_digitalocean_project.go, digitalocean/resource_digitalocean_project_test.go
Setting a default value for an optional filed can create an issue when importing a resource with that field not set. For projects, the environment is optional. 
We were missing an import test, but that wouldn't have actually caught this as the resource being imported would have been created by Terraform and thus would have had the default set. :upside_down_face: 
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/787
=> projects: Environment is optional, don't set default.

digitalocean/app_spec.go, digitalocean/datasource_digitalocean_app_test.go, digitalocean/resource_digitalocean_app_test.go, docs/resources/app.md
Possible PR for #796.
I branched from #797 and this PR uses that as a base branch, so that I could build on the changes by @andrewsomething for alerts. Hence, that should get merged first.
This is my first time contributing to this repo so I'd appreciate a careful review.
=> Implement support for App Platform log_destinations

digitalocean/resource_digitalocean_loadbalancer.go, digitalocean/resource_digitalocean_loadbalancer_test.go
This adds UDP as a target and entry protocol for DigitalOcean Load Balancers.
=> load-balancers: support udp as a target and entry protocol

docs/resources/database_user.md
Document the limitations on importing MongoDB users discussed in https://github.com/digitalocean/terraform-provider-digitalocean/issues/814
=> docs: Note limitations on importing MongoDB users.

digitalocean/datasource_digitalocean_kubernetes_cluster_test.go, digitalocean/import_digitalocean_kubernetes_cluster_test.go, digitalocean/import_digitalocean_kubernetes_node_pool_test.go, digitalocean/resource_digitalocean_kubernetes_cluster_test.go, digitalocean/resource_digitalocean_kubernetes_node_pool_test.go, docs/data-sources/kubernetes_versions.md, docs/resources/kubernetes_cluster.md, docs/resources/kubernetes_node_pool.md, examples/kubernetes/README.md, examples/kubernetes/variables.tf
* update k8s versions used for tests
* docs: refresh example with current versions
* rename symbols to avoid mentioning specific versions and ease future tests maintenance
Closes #825
=> digitalocean_kubernetes_cluster: fix k8s versions in acceptance tests

digitalocean/app_spec.go, digitalocean/resource_digitalocean_app.go, digitalocean/resource_digitalocean_app_test.go, docs/data-sources/app.md, docs/resources/app.md
This PR adds support functions components to the app resource and data source. 
The new acceptance test creates an app with a functions component and then updates it by adding a CORs configuration. The update was triggering an infinite loop as the in-progress deployment completes before we poll the app to find it. I've fixed this with an approach like what we are now doing in doctl (https://github.com/digitalocean/doctl/pull/1143). I've left comments around why this fix is not ideal, but after conversations with the Apps team for the doctl issue, it is currently the best solution. Unfortunately, it actually looks like we missed reviewing a PR attempting to fix this (https://github.com/digitalocean/terraform-provider-digitalocean/pull/818) previously. 
```
$ make testacc …
```
=> apps: Support functions components.

docs/data-sources/ssh_keys.md
=> docs: Document values attribute in ssh_keys data source (fixes: #792).

examples/kubernetes/kubernetes-config/main.tf
In Kubernetes 1.22, the v1beta1 version of Ingress
is [no longer available](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122), thus the example fails to create
the ingress on Kubernetes >= 1.22 with the following error:
```
╷
│ Error: Failed to create Ingress 'test/test-ingress' because: the server could not find the requested resource (post ingresses.extensions)
│ 
│   with module.kubernetes-config.kubernetes_ingress.test_ingress,
│   on kubernetes-config/main.tf line 126, in resource "kubernetes_ingress" "test_ingress":
│  126: resource "kubernetes_ingress" "test_ingress" {
│ 
```
Instead, switch the example to use `kubernetes_ingress_v1`. 
Note that this now increases the minimum version of
terraform-provider-kubernetes since kubernetes_ingress_v1 was …
=> Change k8s example to use ingress v1

digitalocean/resource_digitalocean_database_firewall.go
Uncovered an issue whereby refreshing Terraform state would return an error stating a database cluster didn't exist if a previously existing cluster with a firewall rule is manually deleted rather than deleting the resource from its state. This PR hopes to address this problem by checking the status code, and if it's a 404, then clear the ID for that resource and return nil from its read method.
Since one rule can only be attached to one cluster, simply deleting the rule from state should be safe.
=> Remove database cluster and/or database firewall rule from state if missing

docs/data-sources/droplet_snapshot.md, docs/resources/droplet.md, docs/resources/droplet_snapshot.md
It was hard for me to understand how to create droplet from snapshot so I have decided to contribute with some working examples how to do it so nobody else has to struggle as much as I had to :)
=> Add more docs examples on using droplet snapshots

digitalocean/datasource_digitalocean_droplet_snapshot_test.go, digitalocean/datasource_digitalocean_droplet_test.go, digitalocean/datasource_digitalocean_droplets_test.go, digitalocean/resource_digitalocean_database_firewall_test.go, digitalocean/resource_digitalocean_droplet_snapshot_test.go, digitalocean/resource_digitalocean_floating_ip_assignment_test.go, digitalocean/resource_digitalocean_floating_ip_test.go, digitalocean/resource_digitalocean_loadbalancer_test.go, digitalocean/resource_digitalocean_project_resources_test.go, digitalocean/resource_digitalocean_project_test.go, digitalocean/resource_digitalocean_reserved_ip_assignment_test.go, digitalocean/resource_digitalocean_reserved_ip_test.go, digitalocean/resource_digitalocean_volume_attachment_test.go, digitalocean/resource_digitalocean_volume_test.go, docs/resources/database_firewall.md, docs/resources/droplet_snapshot.md, docs/resources/project.md, docs/resources/project_resources.md
The CentOS images were retired in favor of the new CentOS Stream ones. All tests referencing them fail.  EOL for Ubuntu 22.04 LTS isn't until April 2032, so this shouldn't need updating again for a long time. :crossed_fingers: 
https://wiki.ubuntu.com/Releases
=> testing: Use supported OS for Droplet image slug.

.github/ISSUE_TEMPLATE/bug_report.md
Based on the context in the section and the earlier, larger heading for expected behavior, along with looking at older issues in the repo, I'm pretty sure this title is supposed to be "Terraform version."
=> chore: fix incorrect heading in bug template

digitalocean/resource_digitalocean_project.go, digitalocean/resource_digitalocean_project_test.go, docs/resources/project.md
(murked my previous PR #849 bc got into a hairy merge issue)
Per https://github.com/digitalocean/terraform-provider-digitalocean/issues/848.
@yordis had a great suggestion for allowing to provision digitalocean_project resource as "Default Project". Making "is_default" configurable. This means:
- You can initialize a new project to be the default.
- You can’t edit a project to no longer be default (400 (request "acb5906e-bf48-49e3") you must always have a default project) even if you have other projects, it won’t automatically assign another project to be default
- You can’t delete a project that is the default (^^)
- You must first assign another project to be default first before you can delete the old default project
=> Updating Project Resource to have "is_default" configurable

.github/workflows/release.yml
Fix broken release workflow by switching to `crazy-max/ghaction-import-gpg@v5.0.0` as per https://github.com/hashicorp/ghaction-import-gpg/issues/11#issuecomment-1185107410
=> release workflow: switch to crazy-max/ghaction-import-gpg@v5.0.0

digitalocean/resource_digitalocean_app.go
This works around an issue with the App Platform API where the response body can be too large. We are only actually using the first deployment from the list, so we can use the default page size of 20 rather than 200 to prevent this. I've also removed the loop to prevent iterating through all deployments and using up API request quotas we only need the first one.
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/864
=> apps: Limit the number of deployments listed when polling.

digitalocean/resource_digitalocean_database_connection_pool.go, digitalocean/resource_digitalocean_database_connection_pool_test.go, docs/resources/database_connection_pool.md
The DO API allows DB pools to be created without a user specified. This PR modifies the `digitalocean_database_connection_pool` resource and removes user as a required field. Without user specified, pool uses the connection credentials of the inbound user. 
Adds  new test case for creates w.o specified user, `TestAccDigitalOceanDatabaseConnectionPool_InboundUser`, and modifies `TestAccDigitalOceanDatabaseConnectionPool_Basic` to cover pool updates.
=> make user optional in db connection pool, update acc tests

digitalocean/resource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_database_cluster_test.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/godo.go, vendor/modules.txt
To ensure customer Redis instances do not get destroyed and recreated after their Redis clusters are forced to upgrade, this change updates the `DiffSuppressFunc` logic for Database Cluster resources to suppress diffs when the DB engine is `redis` and `version` is newer on the remote resource than what is specified in the configuration.
This should also help us avoid having to make this change for forced upgrades in the future.
for APICLI-1526
=> Suppress diffs on forced Redis version upgrades

digitalocean/resource_digitalocean_droplet.go, digitalocean/resource_digitalocean_droplet_test.go
Follows up on https://github.com/digitalocean/terraform-provider-digitalocean/pull/839 After creating a Droplet, we're polling using both `waitForAction` and then `waitForDropletAttribute`. This is redundant and  `waitForAction` does not currently support configurable timeouts.  So configuring a create timeout is effectively ignored. This resolves the issue by removing the   `waitForAction` call. 
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/828
=> droplet: Fix configurable timeouts for Droplet creates.

digitalocean/resource_digitalocean_record.go
Add `SOA` as possible record type.
Without it it's not possible to manage `SOA` records as the following error would be raised.
```shell
Error: expected type to be one of [A AAAA CAA CNAME MX NS TXT SRV], got SOA
```
=> Add SOA as possible record type

.github/workflows/release.yml, .github/workflows/test.yml, go.mod, go.sum
This upgrades to Go 1.19 and removes testing for 1.16.x, 1.17.x following our policy of supporting to two most recent releases.
=> Upgrade to Go 1.19

digitalocean/datasource_digitalocean_spaces_bucket_test.go, digitalocean/datasource_digitalocean_spaces_buckets_test.go, digitalocean/resource_digitalocean_spaces_bucket.go, digitalocean/spaces_buckets.go, docs/data-sources/spaces_bucket.md, docs/data-sources/spaces_buckets.md, docs/resources/spaces_bucket.md
This pull request adds an `endpoint` attribute to the `digitalocean_spaces_bucket` data source and resource.
What do we think about the attribute name and description?
```
endpoint: The FQDN of the bucket without the bucket name
```
Example terraform manifest with resource
```
terraform {
required_providers {
digitalocean = {
source = "digitalocean/digitalocean"
version = ">= 2.22.3"
}
}
}
provider "digitalocean" {}
resource "digitalocean_spaces_bucket" "example" {
name   = "unique-bucket-cc7bf683"
region = "nyc3"
}
output "bucket_attributes" {
value = digitalocean_spaces_bucket.example
}
```
Current output for `digitalocean_spaces_bucket` resource with `Terraform 1.3.1` and `terraform-provider-digitalocean_v2.22.3`
```
root@2d7700f3d983:/go/src/github.com/digitalocean/terraform-provider-d …
```
=> spaces: add endpoint attribute to bucket

docs/resources/project_resources.md
The `digitalocean_project_resources` resource was referencing a non-existing data source.
=> Fix reference in documentation of `project_resources`

digitalocean/resource_digitalocean_loadbalancer.go, docs/resources/loadbalancer.md
=> load balancers: add HTTP/3 as an entry protocol

digitalocean/resource_digitalocean_loadbalancer.go, digitalocean/resource_digitalocean_loadbalancer_test.go, docs/resources/loadbalancer.md, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/droplet_actions.go, vendor/github.com/digitalocean/godo/functions.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/image_actions.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/modules.txt
=> Support HTTP idle timeout & Project ID

digitalocean/resource_digitalocean_database_replica.go, digitalocean/resource_digitalocean_vpc.go
Implements fix for https://github.com/digitalocean/terraform-provider-digitalocean/issues/906 by adding more permissive retry logic in two places:
- Call to `client.Databases.CreateReplica` in `resourceDigitalOceanDatabaseReplicaCreate` now allows 412 as a  retryable error.
- Call to `GetReplica` in `waitForDatabaseReplica` allows 404 while replica creates. Same logic as currently used in `resourceDigitalOceanDatabaseClusterCreate`.
With the change, one can run a plan that creates a DB and replica as shown below without running into race condition on replica create:
```
resource "digitalocean_database_replica" "read-replica" {
cluster_id = digitalocean_database_cluster.postgres-example.id
name       = "test-postgres-cluster-replica"
size       = "db-s-1vcpu-1gb"
region     = "nyc1"
} …
```
=> add retry on db replica create

docs/resources/app.md
I believe the docs for app spec are slighty off. 
[The docs say](https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/docs/resources/app.md?plain=1#L198) `"route"`, but [the implementation](https://github.com/digitalocean/terraform-provider-digitalocean/blob/60147643e0e82acd1b1014a84ac2007d9b91dddb/digitalocean/app_spec.go#L523-L530) uses `"routes"`.
=> `routes` documentation in `app.md` matches `app_spec.go`

digitalocean/resource_digitalocean_kubernetes_cluster_test.go
The DOKS acceptance tests are currently failing due to changes in the available Kubernetes versions. 1.21.x and 1.22.x are no longer available:
```
$ doctl kubernetes options versions 
Slug            Kubernetes Version    Supported Features
1.25.4-do.0     1.25.4                cluster-autoscaler, docr-integration, ha-control-plane, token-authentication
1.24.8-do.0     1.24.8                cluster-autoscaler, docr-integration, ha-control-plane, token-authentication
1.23.14-do.0    1.23.14               cluster-autoscaler, docr-integration, ha-control-plane, token-authentication
```
The only reason why we have specific versions referenced is to test the upgrade path, and generally upgrades are only supported from the previous major version. This change calculates the previous version …
=> testing: Find previous K8s release dynamically.

digitalocean/resource_digitalocean_database_cluster.go, digitalocean/resource_digitalocean_database_cluster_test.go, docs/resources/database_cluster.md, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/tokens.go, vendor/github.com/digitalocean/godo/uptime.go, vendor/modules.txt
Enables upgrading the database version without forcing a new database deployment.
For DBAAS-3899
Closes #471
=> databases: Support upgrading the database version

digitalocean/resource_digitalocean_database_replica.go, digitalocean/resource_digitalocean_database_replica_test.go, docs/resources/database_replica.md
Addresses #878
Added a `uuid` attribute to allow users who need to reference the database replica as the target database cluster in other resources. 
I looked into creating a [state migration](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/state-migration) to instead try to update the current `id` attribute to reference the db replica's ID fetched from the DO API- verse the currently implemented `id` that is generated in terraform (in `makeReplicaId`). State migrations seem useful for changing the attribute/schema's configuration, not the actual values that are set in the CreateContext. Thus, decided adding a `uuid` attribute would suffice. Updated documentation to reflect this.
The terraform config would look like this:
```
output "UUID" {
value = …
```
=> database replica: Expose Database Replica ID

CHANGELOG.md, README.md
This change just adds missing entries to the CHANGELOG.md so we don't have a gap for the next release.
I also included extra instructions for this in README's Releasing section.
=> Add releasing notes & missing changelog entries

digitalocean/monitoring/resource_monitor_alert_test.go
```
digitalocean/monitoring/resource_monitor_alert_test.go:15:2: `slackChannels` is unused (varcheck)
slackChannels = `
^
```
This is failing on push to main. It's not clear why the check didn't pick it up in the PR.
https://github.com/digitalocean/terraform-provider-digitalocean/actions/runs/4117578398/jobs/7109046614#step:5:25
=> Remove unused const to fix linting.

digitalocean/image/resource_custom_image.go
This PR changes the pending status of custom images from `new` to `NEW`. According to the API docs, this uppercase value is correct and I was receiving the following failure previously:
```
digitalocean_custom_image.talos-linux: Creating...
╷
│ Error: Error waiting for image (126518466) to become ready: unexpected state 'NEW', wanted target 'available'. last error: %!s(<nil>)
│
│   with digitalocean_custom_image.talos-linux,
│   on main.tf line 1, in resource "digitalocean_custom_image" "talos-linux":
│    1: resource "digitalocean_custom_image" "talos-linux" {
│
╵
```
I'm assuming the value changed in the API some time ago, but it's unclear to me from the docs when that might have been.
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>
=> images: use correct pending statuses for custom images

digitalocean/acceptance/droplets.go, digitalocean/droplet/datasource_droplet_test.go, digitalocean/droplet/datasource_droplets_test.go, digitalocean/droplet/import_droplet_test.go, digitalocean/droplet/resource_droplet_test.go, digitalocean/droplet/sweep.go, digitalocean/image/datasource_image_test.go, digitalocean/loadbalancer/resource_loadbalancer_test.go, digitalocean/monitoring/import_monitor_alert_test.go, digitalocean/monitoring/resource_monitor_alert_test.go, digitalocean/project/resource_project_test.go, digitalocean/reservedip/import_floating_ip_test.go, digitalocean/reservedip/import_reserved_ip_test.go, digitalocean/reservedip/resource_floating_ip_assignment_test.go, digitalocean/reservedip/resource_floating_ip_test.go, digitalocean/reservedip/resource_reserved_ip_assignment_test.go, digitalocean/reservedip/resource_reserved_ip_test.go, digitalocean/snapshot/import_droplet_snapshot_test.go, digitalocean/snapshot/resource_droplet_snapshot_test.go, digitalocean/volume/resource_volume_attachment_test.go, digitalocean/volume/resource_volume_test.go
All resources created by our provider's acceptance tests should use a standard naming structure to make sweeping simpler and reduce risk of running the sweeper for external contributors. This PR ensures we are using a consistent naming for all Droplets created in tests. 
I'll be following this up with PRs for other resource types. As Droplets are used by other resources, this is likely the most invasive PR. Hopefully the others should be easier to review.
=> Use consistent naming for all Droplets created in tests.

digitalocean/certificate/datasource_certificate_test.go, digitalocean/certificate/import_certificate_test.go, digitalocean/certificate/resource_certificate_test.go, digitalocean/certificate/sweep.go
Like https://github.com/digitalocean/terraform-provider-digitalocean/pull/933 but for certificate resources.
```
$ make testacc PKG_NAME=digitalocean/certificate
TF_ACC=1 go test -v ./digitalocean/certificate/...  -timeout 120m -parallel=2
=== RUN   TestAccDataSourceDigitalOceanCertificate_Basic
=== PAUSE TestAccDataSourceDigitalOceanCertificate_Basic
=== RUN   TestAccDigitalOceanCertificate_importBasic
=== PAUSE TestAccDigitalOceanCertificate_importBasic
=== RUN   TestResourceExampleInstanceStateUpgradeV0
2023/02/09 11:29:47 [DEBUG] Migrating certificate schema from v0 to v1.
--- PASS: TestResourceExampleInstanceStateUpgradeV0 (0.00s)
=== RUN   TestAccDigitalOceanCertificate_Basic
=== PAUSE TestAccDigitalOceanCertificate_Basic …
```
=> Use consistent naming for all certs created in tests.

digitalocean/sshkey/datasource_ssh_key_test.go, digitalocean/sshkey/datasource_ssh_keys_test.go, digitalocean/sshkey/import_ssh_key_test.go, digitalocean/sshkey/resource_ssh_key_test.go, digitalocean/sshkey/sweep.go, digitalocean/sweep/sweep_test.go
This adds a sweeper for SSH keys. It also removes a custom helper for generating keys for use in tests. The SDK already provides a helper for this that we use elsewhere. There is no need to duplicate that functionality.
```
$ make testacc PKG_NAME=digitalocean/sshkey 
TF_ACC=1 go test -v ./digitalocean/sshkey/...  -timeout 120m -parallel=5
=== RUN   TestAccDataSourceDigitalOceanSSHKey_Basic
=== PAUSE TestAccDataSourceDigitalOceanSSHKey_Basic
=== RUN   TestAccDataSourceDigitalOceanSSHKeys_Basic
=== PAUSE TestAccDataSourceDigitalOceanSSHKeys_Basic
=== RUN   TestAccDigitalOceanSSHKey_importBasic
=== PAUSE TestAccDigitalOceanSSHKey_importBasic
=== RUN   TestAccDigitalOceanSSHKey_Basic
=== PAUSE TestAccDigitalOceanSSHKey_Basic
=== CONT …
```
=> Add sweeper for SSH keys.

digitalocean/firewall/datasource_firewall_test.go, digitalocean/firewall/resource_firewall_test.go, digitalocean/firewall/sweep.go
This time for firewalls... 
```
$ make testacc PKG_NAME=digitalocean/firewall
TF_ACC=1 go test -v ./digitalocean/firewall/...  -timeout 120m -parallel=2
=== RUN   TestAccDataSourceDigitalOceanFirewall_Basic
=== PAUSE TestAccDataSourceDigitalOceanFirewall_Basic
=== RUN   TestAccDigitalOceanFirewall_AllowOnlyInbound
=== PAUSE TestAccDigitalOceanFirewall_AllowOnlyInbound
=== RUN   TestAccDigitalOceanFirewall_AllowMultipleInbound
=== PAUSE TestAccDigitalOceanFirewall_AllowMultipleInbound
=== RUN   TestAccDigitalOceanFirewall_AllowOnlyOutbound
=== PAUSE TestAccDigitalOceanFirewall_AllowOnlyOutbound
=== RUN   TestAccDigitalOceanFirewall_AllowMultipleOutbound
=== PAUSE TestAccDigitalOceanFirewall_AllowMultipleOutbound
=== RUN …
```
=> Use consistent naming for all firewalls created in tests.

digitalocean/loadbalancer/datasource_loadbalancer_test.go, digitalocean/loadbalancer/import_loadbalancer_test.go, digitalocean/loadbalancer/resource_loadbalancer_test.go, digitalocean/loadbalancer/sweep.go
And now for load balancers... 
This also fixes a test. Previously load balancers could only be resized once an hour. The initial create counted as a "resize." So the resize test was just checking for the error to validate that we at least sent a proper request. This restriction has been changed to once a minute, so we can now test the complete resize.
```
$ make testacc PKG_NAME=digitalocean/loadbalancer
TF_ACC=1 go test -v ./digitalocean/loadbalancer/...  -timeout 120m -parallel=2
=== RUN   TestAccDataSourceDigitalOceanLoadBalancer_BasicByName
=== PAUSE TestAccDataSourceDigitalOceanLoadBalancer_BasicByName
=== RUN   TestAccDataSourceDigitalOceanLoadBalancer_BasicById
=== PAUSE TestAccDataSourceDigitalOceanLoadBalancer_BasicById …
```
=> Use consistent naming for all load balancers created in tests.

digitalocean/acceptance/droplets.go, digitalocean/image/datasource_image_test.go, digitalocean/snapshot/datasource_droplet_snapshot_test.go, digitalocean/snapshot/datasource_volume_snapshot_test.go, digitalocean/snapshot/import_droplet_snapshot_test.go, digitalocean/snapshot/import_volume_snapshot_test.go, digitalocean/snapshot/resource_droplet_snapshot_test.go, digitalocean/snapshot/resource_volume_snapshot_test.go, digitalocean/snapshot/sweep.go
```
$ make testacc PKG_NAME=digitalocean/snapshot
TF_ACC=1 go test -v ./digitalocean/snapshot/...  -timeout 120m -parallel=2
=== RUN   TestAccDataSourceDigitalOceanDropletSnapshot_basic
=== PAUSE TestAccDataSourceDigitalOceanDropletSnapshot_basic
=== RUN   TestAccDataSourceDigitalOceanDropletSnapshot_regex
=== PAUSE TestAccDataSourceDigitalOceanDropletSnapshot_regex
=== RUN   TestAccDataSourceDigitalOceanDropletSnapshot_region
=== PAUSE TestAccDataSourceDigitalOceanDropletSnapshot_region
=== RUN   TestAccDataSourceDigitalOceanVolumeSnapshot_basic
=== PAUSE TestAccDataSourceDigitalOceanVolumeSnapshot_basic
=== RUN   TestAccDataSourceDigitalOceanVolumeSnapshot_regex
=== PAUSE TestAccDataSourceDigitalOceanVolumeSnapshot_regex
=== RUN …
```
=> Use consistent naming for all snapshots created in tests.

digitalocean/volume/datasource_volume_test.go, digitalocean/volume/import_volume_test.go, digitalocean/volume/resource_volume_attachment_test.go, digitalocean/volume/resource_volume_test.go, digitalocean/volume/sweep.go
```
$ make testacc PKG_NAME=digitalocean/volume ACCTEST_PARALLELISM=5
TF_ACC=1 go test -v ./digitalocean/volume/...  -timeout 120m -parallel=5
=== RUN   TestAccDataSourceDigitalOceanVolume_Basic
=== PAUSE TestAccDataSourceDigitalOceanVolume_Basic
=== RUN   TestAccDataSourceDigitalOceanVolume_RegionScoped
=== PAUSE TestAccDataSourceDigitalOceanVolume_RegionScoped
=== RUN   TestAccDigitalOceanVolume_importBasic
=== PAUSE TestAccDigitalOceanVolume_importBasic
=== RUN   TestAccDigitalOceanVolumeAttachment_Basic
=== PAUSE TestAccDigitalOceanVolumeAttachment_Basic
=== RUN   TestAccDigitalOceanVolumeAttachment_Update
=== PAUSE TestAccDigitalOceanVolumeAttachment_Update
=== RUN   TestAccDigitalOceanVolumeAttachment_UpdateToSecondVolume …
```
=> Use consistent naming for all volumes created in tests.

digitalocean/project/resource_project.go, digitalocean/project/resource_project_test.go, digitalocean/project/sweep.go, digitalocean/sweep/sweep_test.go
This adds a sweeper for projects. Additionally it adds a retry for project deletion. Projects must be empty to be deleted. We handle reassigning resources to the default project, but this is an async process. Retrying deletion resolves some flaky tests.
```
$ make testacc PKG_NAME=digitalocean/project TESTARGS="-count=1"
TF_ACC=1 go test -v ./digitalocean/project/... -count=1 -timeout 120m -parallel=2
=== RUN   TestAccDataSourceDigitalOceanProject_DefaultProject
=== PAUSE TestAccDataSourceDigitalOceanProject_DefaultProject
=== RUN   TestAccDataSourceDigitalOceanProject_NonDefaultProject
=== PAUSE TestAccDataSourceDigitalOceanProject_NonDefaultProject
=== RUN   TestAccDataSourceDigitalOceanProjects_Basic
--- PASS: …
```
=> Add sweeper for projects and add retry for project deletion.

digitalocean/cdn/resource_cdn_test.go, digitalocean/spaces/datasource_spaces_bucket_object_test.go, digitalocean/spaces/datasource_spaces_bucket_objects_test.go, digitalocean/spaces/datasource_spaces_bucket_test.go, digitalocean/spaces/datasource_spaces_buckets_test.go, digitalocean/spaces/import_spaces_bucket_policy_test.go, digitalocean/spaces/import_spaces_bucket_test.go, digitalocean/spaces/resource_spaces_bucket.go, digitalocean/spaces/resource_spaces_bucket_object_test.go, digitalocean/spaces/resource_spaces_bucket_policy_test.go, digitalocean/spaces/resource_spaces_bucket_test.go, digitalocean/spaces/spaces_buckets.go, digitalocean/spaces/sweep.go, digitalocean/sweep/sweep.go, digitalocean/sweep/sweep_test.go
```
$ make testacc PKG_NAME=digitalocean/spaces TESTARGS="-count=1"
TF_ACC=1 go test -v ./digitalocean/spaces/... -count=1 -timeout 120m -parallel=10
=== RUN   TestAccDataSourceDigitalOceanSpacesBucketObject_basic
=== PAUSE TestAccDataSourceDigitalOceanSpacesBucketObject_basic
=== RUN   TestAccDataSourceDigitalOceanSpacesBucketObject_readableBody
=== PAUSE TestAccDataSourceDigitalOceanSpacesBucketObject_readableBody
=== RUN   TestAccDataSourceDigitalOceanSpacesBucketObject_allParams
=== PAUSE TestAccDataSourceDigitalOceanSpacesBucketObject_allParams
=== RUN   TestAccDataSourceDigitalOceanSpacesBucketObject_LeadingSlash
=== PAUSE TestAccDataSourceDigitalOceanSpacesBucketObject_LeadingSlash
=== RUN …
```
=> Add sweeper and use consistent naming for all Spaces buckets in tests.

digitalocean/cdn/resource_cdn.go, digitalocean/cdn/resource_cdn_test.go, digitalocean/cdn/sweep.go, digitalocean/sweep/sweep_test.go
The CDN API seems to have additional rate limiting applied to it that is stricter than the rest of our API. I also experienced some lag in being able to GET a newly created CDN where it would return 404 for the first few attempts. So this adds a retry with backoff for GETing a CDN. 
It also adds a test sweeper and fixes a test failure cause due to the type of certificate that was used.
```
$ make testacc PKG_NAME=digitalocean/cdn TESTARGS="-count=1"
TF_ACC=1 go test -v ./digitalocean/cdn/... -count=1 -timeout 120m -parallel=2
=== RUN   TestAccDigitalOceanCDN_Create
=== PAUSE TestAccDigitalOceanCDN_Create
=== RUN   TestAccDigitalOceanCDN_Create_with_TTL
=== PAUSE TestAccDigitalOceanCDN_Create_with_TTL
=== RUN …
```
=> cdn: Add test sweeper and retry with backoff.

digitalocean/droplet/datasource_droplet_test.go, digitalocean/droplet/datasource_droplets_test.go, digitalocean/droplet/import_droplet_test.go, digitalocean/droplet/resource_droplet_test.go
This PR contains a number of fixes and improvements to the Droplet acceptance tests. 
- Adds a const for default Droplet size and image in tests so that they can be updated in one place.
- Skip tests a number of tests that were meant to handling cases where Droplet OSes didn't support the Droplet agent (generally container based). Since the removal of Rancher and CoreOS, all supported Droplet OSes can now install the agent. I skipped them rather than deleting them as we may have new container based OSes in the future.
=> droplet: Fix acceptance testing

digitalocean/database/import_database_replica_test.go, digitalocean/database/resource_database_replica.go
As pointed out in https://github.com/digitalocean/terraform-provider-digitalocean/issues/878, we've exposed the `uuid` of a database replica, but it is not set during imports. We only set it in the create method. It should be set in the read method as well.
Test change on its own shows the problem:
```
=== CONT  TestAccDigitalOceanDatabaseReplica_importBasic
import_database_replica_test.go:23: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) {
}
(map[string]string) (len=1) {
(string) (len=4) "uuid": (string) (len=36) "bcb92ee3-5f0b-4b90-8a43-a0350b718396"
}
--- FAIL: TestAccDigitalOceanDatabaseReplica_importBasic (509.30s)
```
Fixed with the code change:
```
=== RUN …
```
=> database replicas: set uuid on read.

digitalocean/database/datasource_database_replica.go, digitalocean/database/datasource_database_replica_test.go, docs/data-sources/database_replica.md
I noticed a new test failure cause by a panic. The database cluster replica data source calls the resource's `resourceDigitalOceanDatabaseReplicaRead` method. We recently added support for the new replica UUIDs to the resource, so it calls `d.Set("uuid", replica.ID)`. The schema for the replica data source was never updated to include `uuid`. So it panics:
```
panic: Invalid address to set: []string{"uuid"}
goroutine 943 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc0008cd000, {0x1072624, 0x4}, {0xee54a0, 0xc0003e5120})
/home/asb/development/gocode/src/github.com/digitalocean/terraform-provider-digitalocean/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:230 +0x291 …
```
=> datbase replica: Add uuid to data source schema.

docs/resources/uptime_alert.md
Hi!
I noticed some inconsistencies in [the documentation of the `digitalocean_uptime_alert` resource](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/uptime_alert). The `type` argument mentions the options `ping`, `http` and `https`, which actually belong to the `digitalocean_uptime_check` resource instead. When diving into the source code I also noticed some other issues in the documentation.
This PR should fix those, and also adds the contents of the `notifications` object to the argument reference. Last but not least I have fixed some formatting issues and a small typo in the example code.
=> Fix inconsistencies in digitalocean_uptime_alert documentation

docs/resources/uptime_alert.md, docs/resources/uptime_check.md
These are not linking to the canonical location of the API documentation.
=> docs: Use correct links in Update docs.

digitalocean/kubernetes/import_kubernetes_cluster_test.go, digitalocean/kubernetes/resource_kubernetes_cluster.go
The API does not have an endpoint to know if `registry_integration` has been set or not for a Kubernetes cluster. So its state can not be imported. This adds it to `ImportStateVerifyIgnore` for `TestAccDigitalOceanKubernetesCluster_ImportBasic`
It also cleans up a golint issue. `s/cluster_uuid/clusterUUID/g`
Fixup for https://github.com/digitalocean/terraform-provider-digitalocean/pull/963
=> kubernetes: add registry_integration to ImportStateVerifyIgnore

digitalocean/kubernetes/import_kubernetes_cluster_test.go, digitalocean/kubernetes/resource_kubernetes_cluster.go, digitalocean/kubernetes/resource_kubernetes_cluster_test.go, docs/resources/kubernetes_cluster.md, docs/resources/kubernetes_node_pool.md
This resolves https://github.com/digitalocean/terraform-provider-digitalocean/issues/892 by only importing the default node pool when importing a cluster. Additional pools should now be imported separately as `digitalocean_kubernetes_node_pool` resources.
The old approach of importing multiple resources in one go was fragile, and the upstream Terraform developer documentation has begun to actively discourage it:
> Multiple resource import is generally discouraged due to the implementation/testing complexity and since the resource addresses saved into the Terraform state will likely not align with the operator's configuration.
https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/import#multiple-resource-import
Other providers like AWS' have removed all usage of "complex …
=> kubernetes: Require importing additional node pools manually.

digitalocean/domain/datasource_record.go
The domain record data source does not handle pagination properly causing any record found on the second page of results to be missed.
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/978
=> records: Handle pagination in data source.

digitalocean/database/resource_database_replica.go, digitalocean/database/resource_database_replica_test.go, docs/resources/database_replica.md
Now that database replicas expose their UUID, we are able to support resizing them.
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/902
=> databases: Add support for resizing replicas.

digitalocean/image/resource_custom_image.go
Custom images can take a long time to create. There is a hard coded timeout here, but that is actually ignored. The default create timeout for Terraform is 20m. To support anything longer and make it configurable, we need to set a `ResourceTimeout` block in the schema.
=> custom image: use custom create timeout.

digitalocean/database/resource_database_cluster.go
Looks like we accidentally used `TimeoutDelete` where it should be `TimeoutCreate` :man_facepalming: 
Also noticed `=` when it should be `>=` to prevent the corner case of the timeout being set lower than the interval. 
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/986
=> databases: Fix custom create timeouts.

digitalocean/spaces/resource_spaces_bucket.go
Users have been experiencing errors being returned on successful spaces create requests that take longer than 1 minute. Github issue is #996 
The only referenced function in `resourceDigitalOceanBucketCreate` that's using a 1 minute timeout is the `retryOnAwsCode` so updating that to 5 minutes to hopefully mitigate the errors on successful bucket creations.
=> Update retryOnAwsCode to Five Minutes

digitalocean/database/datasource_database_cluster_test.go, digitalocean/database/resource_database_cluster_test.go, digitalocean/database/resource_database_connection_pool_test.go, digitalocean/database/resource_database_db_test.go, digitalocean/database/resource_database_firewall_test.go, digitalocean/database/resource_database_user_test.go
We have acceptance tests failing:
```
datasource_database_cluster_test.go:20: Step 1/2 error: Error running apply: exit status 1
Error: Error creating database cluster: POST https://api.digitalocean.com/v2/databases: 422 (request "f1627cab-76fe-4d38-b86c-1f6460daed6a") invalid cluster engine version
with digitalocean_database_cluster.foobar,
on terraform_plugin_test.tf line 2, in resource "digitalocean_database_cluster" "foobar":
2: resource "digitalocean_database_cluster" "foobar" {
--- FAIL: TestAccDataSourceDigitalOceanDatabaseCluster_Basic (0.91s)
```
Looks like version 11 has been EOLed for Postgres:
```
$ doctl databases options versions 
Engine     Versions
mysql      [8]
pg         [12,13,14,15]
redis      [7]
mongodb    [4.4,5.0,6.0]
```
=> databases: Update Postgres versions in acceptance tests.

digitalocean/kubernetes/resource_kubernetes_cluster.go, digitalocean/kubernetes/resource_kubernetes_cluster_test.go, docs/resources/kubernetes_cluster.md
This adds an option to destroy all associated DigitalOcean resources created via the Kubernetes API (load balancers, volumes, and volume snapshots) along with the cluster when it is destroyed.
=> k8s: Add destroy_all_associated_resources option.

docs/resources/volume.md
In the DigitalOcean [API docs](https://docs.digitalocean.com/reference/api/api-reference/#operation/volumes_create) for creating a volume, it is stated that the volume must start wit a letter which is missing from the provider docs.
```text
name required | string 
A human-readable name for the block storage volume.
Must be lowercase and be composed only of numbers, letters and "-", up to a limit of 64 characters. 
The name must begin with a letter.
```
=> fix(docs): make it clear that volume name has to start with a letter

digitalocean/database/resource_database_user.go, digitalocean/database/resource_database_user_test.go
This PR resolves an issue where creating multiple users for a MongoDB cluster at once can return a 500-level response by preventing parallel creation or deletion of users for the same cluster using a mutex.
(Annoyingly using `for_each` is not supported in the acceptance test framework. https://github.com/hashicorp/terraform-plugin-sdk/issues/536)
=> database_user: Prevent creating multiple users for the same cluster in parallel.

digitalocean/database/resource_database_user.go
We have reports that the post-create GET requests can unexpectedly fail with a 404 at times despite the create succeeding. For the most part, this request is unnecessary. The information is returned in the POST response. This sets state with that information and removes the unnecessary GET.
```
=== RUN   TestAccDigitalOceanDatabaseUser_importBasic
=== PAUSE TestAccDigitalOceanDatabaseUser_importBasic
=== RUN   TestAccDigitalOceanDatabaseUser_Basic
=== PAUSE TestAccDigitalOceanDatabaseUser_Basic
=== RUN   TestAccDigitalOceanDatabaseUser_MongoDB
=== PAUSE TestAccDigitalOceanDatabaseUser_MongoDB
=== RUN   TestAccDigitalOceanDatabaseUser_MongoDBMultiUser
=== PAUSE TestAccDigitalOceanDatabaseUser_MongoDBMultiUser
=== RUN   TestAccDigitalOceanDatabaseUser_MySQLAuth
=== PAUSE …
```
=> database user: Remove unneeded GET request post-create.

GNUmakefile, docs/data-sources/domains.md, docs/data-sources/firewall.md, docs/data-sources/kubernetes_cluster.md, docs/data-sources/records.md, docs/index.md, docs/resources/app.md, docs/resources/container_registry_docker_credentials.md, docs/resources/custom_image.md, docs/resources/database_cluster.md, docs/resources/kubernetes_cluster.md, docs/resources/monitor_alert.md, docs/resources/spaces_bucket_policy.md, docs/resources/uptime_check.md
Went to use `make terrafmt` on some new docs I'm writing and found we aren't pointing it at the docs directory in the makefile target. This updates the makefile to run it against the docs and fixes up existing formatting issues.
=> Use terrafmt on docs directory.

digitalocean/loadbalancer/resource_loadbalancer.go
Global lb creates are crashing on read after creates as it tries to parse nil `region` object: global lb doesn't have an associated region.
=> Parse nil region for global lb

digitalocean/loadbalancer/resource_loadbalancer.go, digitalocean/loadbalancer/resource_loadbalancer_test.go
Created a custom diff function to validate that `region` field is not required if the type file is set to `GLOBAL` and if set to `REGIONAL` validate `region` value is present and not empty. 
Verified by running `terraform plan` for each case
=> LBAAS-2800: no region field needed for global lb type

digitalocean/app/resource_app.go, digitalocean/app/resource_app_test.go
This commit modifies the logic used by the `digitalocean_app` resource to check each step for a success status rather than using the counts of steps. The step counting method fails to work with jobs of kind `FAILED_DEPLOY` as these will always be pending, meaning that any app deployed with a job of this type will always time out even when it is successful.
Closes #1047
=> Rework deployment logic

docs/resources/database_firewall.md, docs/resources/database_user.md
Clarify that when referencing `digitalocean_database_replica`, the `uuid` must be used instead of `id`
=> Database: Clarify Docs for Referencing DB Replicas

digitalocean/kubernetes/resource_kubernetes_cluster.go
For some reason, we only return an error when attempting to fetch a cluster's credentials if it is a 404 response. This can lead to a panic in other error cases as we attempt to flatten the credential which are `nil`. This handles the error properly and protect against a panic in `flattenCredentials`.
Example panic:
```
Stack trace from the terraform-provider-digitalocean_v2.30.0 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xcfad4c]
goroutine 465 [running]:
github.com/digitalocean/terraform-provider-digitalocean/digitalocean/kubernetes.flattenCredentials({0xc000b61490, 0xc}, {0xc000b6147c, 0x4}, 0x0)
github.com/digitalocean/terraform-provider-digitalocean/digitalocean/kubernetes/resource_kuber …
```
=> k8s: Handle error from GetCredentials and protect against panic.

digitalocean/app/app_spec.go, digitalocean/app/resource_app_test.go, docs/resources/app.md
Hello, this PR is intended to resolve the issue [#1033](https://github.com/digitalocean/terraform-provider-digitalocean/issues/1033)
=> Support `features` in App spec

digitalocean/loadbalancer/resource_loadbalancer.go
As brought up in this discussion thread, there are cases where Kubernetes will delete a load balancer itself. This can cause an error when Terraform attempts to do so. We can safely ignore a 404 error when attempting to delete as that just indicates that the load balancer has already been destroyed. 
https://github.com/digitalocean/terraform-provider-digitalocean/discussions/1065
=> load balancers: ignore 404 on delete.

digitalocean/database/resource_database_kafka_topic.go, digitalocean/database/resource_database_kafka_topic_test.go, docs/resources/database_kafka_topic.md
**What**
- remove `unclean_leader_election_enable` property for topic configuration
**Why**
This property is no longer supported for kafka topics due to the dangerous nature of enabling it
=> Remove unclean_leader_election_enable for kafka topic configuration

digitalocean/app/app_spec.go, digitalocean/app/resource_app_test.go, docs/resources/app.md
=> fix: added missing option to set port on health_check

digitalocean/app/app_spec.go
terraform-provider-digitalocean % TF_ACC=1 go test -v -run TestAccDigitalOceanApp_Basic ./digitalocean testing: warning: no tests to run
PASS
ok      github.com/digitalocean/terraform-provider-digitalocean/digitalocean    0.627s [no tests to run]
=> Apps: Reference Port in expandAppHealthCheck and flattenAppHealthCheck

digitalocean/database/resource_database_cluster_test.go, digitalocean/database/resource_database_kafka_topic.go, digitalocean/database/resource_database_kafka_topic_test.go, digitalocean/database/resource_database_user_test.go, docs/resources/database_cluster.md, docs/resources/database_kafka_topic.md, docs/resources/database_user.md
**What**
- Address default minimum for `min_insync_replicas` for topic advanced config
- Address deprecated kafka plan
- Update documentation
**Why**
When providing a topic's advanced config, we should enforce the default to be 1 for `min_insync_replicas`, even when it is not set. The default is in line with kafka defaults.
https://kafka.apache.org/documentation/#brokerconfigs_min.insync.replicas
**Before**
```
│ Error: Error creating database kafka topic: POST https://api.digitalocean.com/v2/databases/d75f23ac-41db-48f4-9364-33438fc5fe96/topics: 422 (request "4f8db04d-5c7a-4002-837c-5cc81b266999") invalid input for config 'min.insync.replicas': 0 is less than the minimum of 1
```
**After**
```
digitalocean_database_kafka_topic.foobar_topic_6: Creating... …
```
=> Kafka topic + user ACL management doc fixes

digitalocean/spaces/spaces_buckets.go
`blr1` is a supported region for Spaces: https://docs.digitalocean.com/products/spaces/details/availability/
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/1083
=> spaces: blr1 is a supported region.

digitalocean/cdn/resource_cdn.go, digitalocean/cdn/resource_cdn_test.go, docs/resources/cdn.md
Address #1086 
In order to have Cloudflare generate a certificate, `certificate_id` must be set to the value "needs-cloudflare-cert" in our API.
In the Terraform provider `certificate_name` is passed in instead of a `certificate_id` _(we've deprecated certificate_id attribute in favor of certificate_name for digitalocean_cdn because when the certificate type is lets_encrypt, the certificate ID will change on renewal (after 3 months)_), we use the name to look up the id and then set that id to `certificate_id`.....hence the `certificate_id` will not be `needs-cloudflare-cert` [here](https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/digitalocean/cdn/resource_cdn.go#L142-L151):
```
if name, nameOk := d.GetOk("certificate_name"); nameOk {
certName := name.(string)
if …
```
=> CDN: Add Support for "needs-cloudflare-cert"

digitalocean/database/resource_database_cluster.go, digitalocean/database/resource_database_cluster_test.go
This resolves an issue with unexpected diffs from `maintenance_window.hour`. The logic in the existing `DiffSuppressFunc` is a bit backwards. It's not entirely clear to me if this was always just wrong or if the API changed behaviour at some point.
I think the best path forward from the provider perspective it to make it so seconds are ignored completely when calculating the diff. Users should not need to scheduled a maintenance down to the second. They are too fine grained.
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/1093
=> databases: ignore seconds in maintenance_window.hour

digitalocean/cdn/resource_cdn.go, digitalocean/cdn/resource_cdn_test.go
This addresses the continued issue called out in https://github.com/digitalocean/terraform-provider-digitalocean/issues/1086. We need to handle the 'needs-cloudflare-cert' case in read func as well as create. 
The acceptance test did not catch this. In order to fully test the flow, we would need an active domain. We can do this in our own testing, but the acceptance test suite must be usable by external contributors and not depend on external resources. So the updated test is skipped if `DO_TEST_SUBDOMAIN` is not set to an active DO manage sub domain.
=> cdn: handle 'needs-cloudflare-cert' case in read func.

digitalocean/database/datasource_database_user.go, digitalocean/database/datasource_database_user_test.go, digitalocean/database/resource_database_user.go, digitalocean/database/resource_database_user_test.go, docs/data-sources/database_user.md, docs/resources/database_user.md
I didn't create an issue but saw this functionality was missing while it was available via the DO API as well as in `godo`.
I ran the following acceptance tests:
```
➜  terraform-provider-digitalocean git:(add-database-user-cert-attributes) ✗ make testacc TESTARGS='-run="^(TestAccDigitalOceanDatabaseUser_Basic|TestAccDigitalOceanDatabaseUser_KafkaACLs|TestAccDataSourceDigitalOceanDatabaseUser_Basic)$$"' PKG_NAME=digitalocean/database
TF_ACC=1 go test -v ./digitalocean/database/... -run="^(TestAccDigitalOceanDatabaseUser_Basic|TestAccDigitalOceanDatabaseUser_KafkaACLs|TestAccDataSourceDigitalOceanDatabaseUser_Basic)$" -timeout 120m -parallel=3
=== RUN   TestAccDataSourceDigitalOceanDatabaseUser_Basic
=== PAUSE …
```
=> database: Add access_cert and access_key for kafka users

digitalocean/database/datasource_database_replica.go, digitalocean/database/datasource_database_replica_test.go, digitalocean/database/resource_database_cluster.go, digitalocean/database/resource_database_cluster_test.go, digitalocean/database/resource_database_replica.go, digitalocean/database/resource_database_replica_test.go, digitalocean/database/resource_database_user_test.go, docs/resources/database_cluster.md, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/godo.go, vendor/modules.txt
**What**
- Enables read-replicas to set their own value for `storage_size_mib` to specify disk space
- Resolves some outdated Mongo tests using older versions
- Fixes resize issue for clusters when omitting `storage_size_mib`
=> Support scalable storage settings separately for read-replica vs. primary

digitalocean/droplet/resource_droplet.go
It appears the API does not support disablement of IPv6, only enablement. If ipv6 is set to false after being set to true then nothing changes on the cloud provider and the diff keeps happening forever #1104
This update uses forces a replacement if the user is trying to disable ipv6
=> Error out with a message if the user tries to disable IPv6 on a droplet

digitalocean/app/app_spec.go
`GHCR` is now a supported registry type, but it never made its way here.
Fixes https://github.com/digitalocean/terraform-provider-digitalocean/issues/1107
=> apps: Add GHCR as a supported registry type.

digitalocean/droplet/resource_droplet.go, docs/resources/droplet.md
Enabling IPv6 on an existing Droplet requires OS-level config changes that are outside of the scope of Terraform itself. This PR updates the docs to point to the DigitalOcean product docs with the details. It also outputs a warning with that information when IPv6 is enabled. 
Example:
```
digitalocean_droplet.ipv6-test: Modifying... [id=400155502]
digitalocean_droplet.ipv6-test: Still modifying... [id=400155502, 10s elapsed]
digitalocean_droplet.ipv6-test: Modifications complete after 11s [id=400155502]
╷
│ Warning: Enabling IPv6 requires additional OS-level configuration
│ 
│   with digitalocean_droplet.ipv6-test,
│   on main.tf line 64, in resource "digitalocean_droplet" "ipv6-test":
│   64: resource "digitalocean_droplet" "ipv6-test" {
│ 
│ When enabling IPv6 on an existing Droplet, …
```
=> droplet: Document and warn that enabling IPv6 requires OS-level config changes.

digitalocean/app/datasource_app.go, digitalocean/app/datasource_app_test.go, digitalocean/app/resource_app.go, digitalocean/app/resource_app_test.go, docs/data-sources/app.md, docs/resources/app.md
Adds support for specifying a project ID for a app. Addresses #1112 
Tried it out locally and was able to confirm an App was created in specified project:
```
terraform {
required_providers {
digitalocean = {
source = "digitalocean/digitalocean"
version = ">= 2.8.0"
}
}
}
provider "digitalocean" {
#
}
resource "digitalocean_project" "foobar" {
name = "test_apps"
}
resource "digitalocean_app" "golang-sample" {
project_id = digitalocean_project.foobar.id
spec {
name   = "golang-sample"
region = "ams"
service {
name               = "go-service"
environment_slug   = "go"
instance_count     = 1
instance_size_slug = "professional-xs"
git {
repo_clone_url = "https://github.com/digitalocean/sample-golang.git"
branch         = "main"
}
}
}
}
```
=> Apps: Support Project Assignment

digitalocean/certificate/datasource_certificate.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/certificates.go, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/modules.txt
[NETPROD-3585](https://do-internal.atlassian.net/browse/NETPROD-3585)
[NETPROD-3585]: https://do-internal.atlassian.net/browse/NETPROD-3585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NETPROD-3585] Optimised fetching certificates by name

digitalocean/certificate/datasource_certificate.go, digitalocean/certificate/resource_certificate.go
While reviewing https://github.com/digitalocean/terraform-provider-digitalocean/pull/1115, I realized an already existing issue with the certificate resource. `FindCertificateByName` will never return `StatusNotFound` as it is a list endpoint. It returns an empty list if there is no match. So our special casing of a 404 response is never encountered. 
This means if a certificate is deleted outside of Terraform, we currently do not attempt to reconcile state and prompt to recreate. `FindCertificateByName`  returns an error and we surface that to the user instead. This reorders the logic to check that `cert == nil` before checking `err != nil` so that a missing cert is handled like other missing resources. 
```
$ make testacc PKG_NAME=digitaloc
ean/certificate
==> Checking that code …
```
=> certificates: handle missing certificate.

docs/resources/project.md, docs/resources/project_resources.md
As mentioned in https://github.com/digitalocean/terraform-provider-digitalocean/issues/1117, the docs don't mention that apps can be added to projects when they can:
https://docs.digitalocean.com/reference/api/api-reference/#tag/Project-Resources
(Also went all in on plural)
=> docs: apps can be added to projects.

digitalocean/loadbalancer/datasource_loadbalancer.go, digitalocean/loadbalancer/resource_loadbalancer.go, docs/resources/loadbalancer.md
This field has been deprecated. You can no longer specify an algorithm for load balancers.
https://docs.digitalocean.com/reference/api/api-reference/#operation/loadBalancers_create
=> Load Balancer: Deprecate "algorithm" attribute

digitalocean/app/app_spec.go
This unblocks users of private non-DOCR registries with App Platform (https://github.com/digitalocean/terraform-provider-digitalocean/issues/1132). 
`registry_credentials` is currently documented here:  https://docs.digitalocean.com/products/app-platform/how-to/deploy-from-container-images/#deploy-container-using-the-apps-spec
This unfortunately has the same draw back as other App Platform secret values when used with Terraform:
> The registry_credentials field requires you to initially submit your access credentials in clear text, but App Platform then encrypts and stores these values similar to secret environment variables. After submitting the spec, App Platform replaces the values in the spec with encrypted values. Once the values are encrypted, you can safely store the spec in the …
=> apps: included registry_credentials option for images

digitalocean/database/resource_database_cluster_test.go, digitalocean/database/resource_database_postgres_config.go, digitalocean/database/resource_database_postgres_config_test.go, digitalocean/provider.go, docs/resources/database_postgresql_config.md
This pull request adds a new PostgreSQL configuration resource and a corresponding test. The resource allows users to configure various PostgreSQL settings for a DigitalOcean database cluster, similar like to MySQL.
I tried to implement all options from [godo](https://github.com/digitalocean/terraform-provider-digitalocean/blob/629bb3b8b4717cc2d6e96acf02207009d22790d7/vendor/github.com/digitalocean/godo/databases.go#L512). For the test I'm not sure if they are working correct, I guess here it will need some more work.
=> Add PostgreSQL configuration resource and test

digitalocean/project/resource_project.go, digitalocean/project/resource_project_test.go
Addresses  #1143
Fixes following scenario:
1. User creates plan with a new project and adds unacceptable resources (i.e. vpc) to project
3. Terraform plan fails, project is still created but not added to terraform state
4. User fixes plan by removing unacceptable resources
5. User re-applies plan, plan fails with `project with same name already exists` error because project was never added to terraform state, so terraform thinks it doesn't exist, though the project does exist in DO.
This fix will delete a project if the adding resources to project request fails, therefore being more aligned with the terraform state. 
Terraform plan to reproduce:
```
resource "digitalocean_droplet" "web" {
name   = "web-01"
size   = "s-1vcpu-1gb"
image  = "ubuntu-22-04-x64"
region = "nyc3"
}
resource …
```
=> Project: Remove project from state if tf project creation plan fails

go.mod, vendor/modules.txt
I am working on [Crossplane DigitalOcean No Fork Upjet Provider](https://github.com/straw-hat-team/provider-digitalocean/pull/4) that requires me to add this package as a dependency. I noticed this old package being pinned to an old version, so I had to deal with adding the `replace` statement to then realize that this package does not seem to be used.
=> chore: remove go.mod replace for old unused pkg

digitalocean/database/datasource_database_cluster.go, digitalocean/database/resource_database_cluster.go, docs/data-sources/database_cluster.md, docs/resources/database_cluster.md, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/godo.go, vendor/modules.txt
This PR aims at adding support for Opensearch in Terraform Provider.
=> Terraform Provider updates for Opensearch

digitalocean/app/app_spec.go, digitalocean/app/datasource_app.go, digitalocean/app/resource_app.go, digitalocean/app/resource_app_test.go, docs/data-sources/app.md, docs/resources/app.md
Addresses #1151
API reference:
[https://docs.digitalocean.com/reference/api/api-reference/#operation/apps_create](https://docs.digitalocean.com/reference/api/api-reference/#operation/apps_create
)
Example config:
```
resource "digitalocean_app" "foobar" {
spec {
name   = "%s"
region = "ams"
static_site {
name              = "sample-jekyll"
build_command     = "bundle exec jekyll build -d ./public"
output_dir        = "/public"
environment_slug  = "jekyll"
catchall_document = "404.html"
git {
repo_clone_url = "https://github.com/digitalocean/sample-jekyll.git"
branch         = "main"
}
}
egress {
type = "DEDICATED_IP"
}
}
}
```
Tests passing:
```
x@x terraform-provider-digitalocean % TF_ACC=1 go test -v -run TestAccDigitalOceanApp_Egress ./digitalocean/app
=== RUN …
```
=> Apps: Add egress/dedicated IPs support

digitalocean/database/resource_database_cluster.go
For all databases. Use password from subsequent GET requests in case it's not empty.
Fixes #1165.
=> Databases: Save DB password from initial POST request

digitalocean/database/resource_database_cluster.go, digitalocean/database/resource_database_connection_pool.go, digitalocean/database/resource_database_connection_pool_test.go, digitalocean/database/resource_database_replica.go
This builds on the work in https://github.com/digitalocean/terraform-provider-digitalocean/pull/1166 to also make sure the password is not overwritten in connection URIs, replicas, and connection pools.
=> dbaas:  ensure password is always retained in connection URIs, replicas, and connection pools.

CHANGELOG.md
While this release contains no code changes, a release is needed to update the live documentation at registry.terraform.io
=> Prep v2.39.2 release

docs/resources/app.md
Looks like we neglected to document the `registry_credentials` argument for apps.
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/1179
=> apps: document registry_credentials argument.

digitalocean/app/app_spec.go, digitalocean/app/resource_app_test.go
This protects against a panic when using CORs ingress rules that do not specify `allow_origins`
Resolves: https://github.com/digitalocean/terraform-provider-digitalocean/issues/1176
While fixing this, I encountered a number of other small issues that needed to be fixed in order to get the relevant tests passing. Each commit addresses a different issue.
1. [apps: don't set empty lists to state in CORs ingres rules](https://github.com/digitalocean/terraform-provider-digitalocean/commit/97ddc6a00a659d5adc2cb98c3502b7a731fc5cd9)
We were setting empty lists to state which caused diffs like:
```
~ rule {
~ cors {
+ allow_headers     = []
+ allow_methods     = []
+ expose_headers    = []
}
}
```
2. [apps: prefix based matching for CORs ingress rules is …
=> apps: protect against panic when CORS has no allow_origins

digitalocean/database/import_database_replica_test.go, digitalocean/database/resource_database_replica.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/modules.txt
Now that `size` is available in the `GET /v2/databases/{uuid}/replicas/{name}` response, we can set it to state on read.
Resolves: https://github.com/digitalocean/terraform-provider-digitalocean/issues/1185
=> databases: set replica size to state on read.

CHANGELOG.md, digitalocean/app/resource_app_test.go, digitalocean/database/resource_database_kafka_topic.go, digitalocean/database/resource_database_user.go, digitalocean/domain/resource_record_test.go, digitalocean/kubernetes/resource_kubernetes_cluster_test.go, digitalocean/snapshot/resource_droplet_snapshot.go, digitalocean/snapshot/resource_volume_snapshot.go, docs/data-sources/droplet.md, docs/resources/database_kafka_topic.md, docs/resources/droplet.md, docs/resources/uptime_check.md, docs/resources/volume.md, docs/resources/vpc_peering.md, internal/mutexkv/mutexkv.go
At time of writing
```
cat _typos.toml
[files]
extend-exclude = [
"go.mod",
"vendor/*",
]
[default.extend-identifiers]
"reservedIPURNtoFloatingIPURN" = "reservedIPURNtoFloatingIPURN"
[default]
extend-ignore-re = [
"(?Rms)\\s*-----BEGIN CERTIFICATE-----(.*)-----END CERTIFICATE-----\\s*",
"(?Rms)\\s*-----BEGIN PRIVATE KEY-----(.*)-----END PRIVATE KEY-----\\s*",
]
```
=> fix: run https://github.com/crate-ci/typos --write-changes to fix up typos

CHANGELOG.md
```
$ github-changelog
-generator -org digitalocean -repo terraform-provider-digitalocean -token $GH_TOKEN
- #1192 - @halkeye - fix: run https://github.com/crate-ci/typos --write-changes to fix up typos
- #1177 - @cotyhamilton - Update kubernetes_cluster surge_upgrade default in docs
- #1189 - @moritzbruder - digitalocean_app: Service Autoscaling
- #1186 - @andrewsomething - databases: set replica size to state on read.
- #1188 - @andrewsomething - apps: support DEPLOYMENT_STARTED and DEPLOYMENT_CANCELLED alerts.
- #1182 - @andrewsomething - apps: support additional database engines
- #1184 - @andrewsomething - apps: protect against panic when CORS has no allow_origins
- #1180 - @andrewsomething - apps: document registry_credentials argument.
- #1178 - @andrewsomething - Update for …
```
=> Prep v2.40.0 release

digitalocean/database/resource_database_postgres_config.go, digitalocean/database/resource_database_postgres_config_test.go
Fix Postgres Config TimescaleDB configuration. Until now it expect a list of objects but the godo library expect it as a single object. Also, the fixing the attribute key for TimescaleDB configuration.
I'm not sure if I implemented this correct, since I'm not really sure how to test this.
=> Fix Postgres Config TimescaleDB configuration

docs/resources/app.md
Fixes #1196 
Tiny fix to the documentation to match the supported alert types. The code work has already been done in #1188 .
=> fix(docs): include newly supported alerts

digitalocean/app/app_spec.go, docs/data-sources/app.md, docs/resources/app.md
WIth this PR we would like to add support for OpenShift using the **log_destination** block. 
based on the spec of digital ocean we should have something like this:
```
log_destination: 
-name: app-staging-opensearch
open_search:
basic_auth:
user: username
cluster_name: cluster_name
ndex_name: logs
```
In the specification created setting the forward from digital ocean from the UI there is no field for `password` in the `basic_auth` and im not sure if i have to include it or not
=> Added support for opensearch configuration on log_destination block

digitalocean/database/datasource_database_cluster_test.go
Logging into our acceptance test account showed that we had a handful of old test databases laying around from failed tests. The account sweeper failed to delete them since they were not using the standardized name prefix for acceptance tests:
https://github.com/digitalocean/terraform-provider-digitalocean/blob/78596c3e994acc58d452635ef0cdf5f1d47b75cc/digitalocean/database/sweep.go#L37
I've cleaned them up manually, but this should prevent more stranded resources in the future.
=> dbaas: Use standardized name prefix in tests.

digitalocean/app/datasource_app.go, digitalocean/app/resource_app.go, digitalocean/app/resource_app_test.go, docs/data-sources/app.md, docs/resources/app.md
The API exposes a `live_domain` attribute. We should support it in Terraform.
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/issues/1207
=> apps: expose live_domain computed attribute.

.golangci.yml, digitalocean/certificate/resource_certificate.go, digitalocean/droplet/resource_droplet.go, digitalocean/spaces/resource_spaces_bucket.go
Fixes issue #1228 
Output of `make lint` after enabling back `ineffassign`:
```
jameskim:~/workspace/tmux-powerline $ git branch
* main
jameskim:~/workspace/terraform-provider-digitalocean $ make lint
INFO golangci-lint has version 1.61.0 built with go1.23.1 from a1d6c56 on 2024-09-09T14:33:19Z
INFO [config_reader] Config search paths: [./ /Users/jameskim/workspace/terraform-provider-digitalocean /Users/jameskim/workspace /Users/jameskim /Users /]
INFO [config_reader] Used config file .golangci.yml
WARN [config_reader] The configuration option `linters.errcheck.ignore` is deprecated, please use `linters.errcheck.exclude-functions`.
INFO [lintersdb] Active 7 linters: [gofmt goimports gosimple govet ineffassign staticcheck unconvert]
INFO [loader] Go packages loading at mode 575 …
```
=> [ISSUE-1228] Resolve failing linter: ineffassign and enable back

digitalocean/database/resource_database_user.go, digitalocean/database/resource_database_user_test.go
This PR aims at adding support for opensearch acl changes to DO's Terraform Provider.
```
make testacc TESTARGS='-run=TestAccDigitalOceanDatabaseUser_OpenSearchACLs'
```
=> Update Terraform provider to include new opensearch acl changes

digitalocean/database/resource_database_kafka_config.go, digitalocean/database/resource_database_kafka_config_test.go, digitalocean/provider.go, docs/resources/database_kafka_config.md, go.mod, go.sum, vendor/github.com/digitalocean/godo/databases.go, vendor/modules.txt
This PR adds a support for Kafka advanced configuration.
Terraform config example:
```
terraform {
required_providers {
digitalocean = {
source  = "digitalocean/digitalocean"
version = ">= 2.4.0"
}
}
}
provider "digitalocean" {
token = "dop_v1_<your-token>"
}
resource "digitalocean_database_cluster" "new-kafka-tf-example" {
name       = "kafka-cluster-test"
engine     = "kafka"
version    = "3.7"
size       = "db-s-2vcpu-2gb"
region     = "nyc1"
node_count = 3
tags       = ["production"]
}
resource "digitalocean_database_kafka_config" "new-tf-example-cfg" {
cluster_id                              = digitalocean_database_cluster.new-kafka-tf-example.id
group_initial_rebalance_delay_ms        = 7000
log_flush_interval_ms                   = 10
}
```
=> [databases]: add support for Kafka advanced configuration

docs/data-sources/app.md, docs/resources/app.md
This fixes a few issues with App `log_destination` docs. Specifically, it adds `log_destination` to all supported component types. It also fixes some indentation issues.
Before:
After:
=> docs: fix formatting for apps log_destination

.golangci.yml, digitalocean/acceptance/droplets.go, digitalocean/droplet/import_droplet_test.go, digitalocean/droplet/resource_droplet.go, digitalocean/registry/resource_container_registry_test.go
Fixes issue #1227 
The following files were modified. They all had the same issue of not checking errors before assigning values:
digitalocean/acceptance/droplets.go
digitalocean/droplet/import_droplet_test.go
digitalocean/droplet/resource_droplet.go
digitalocean/registry/resource_container_registry_test.go
I am also attaching the following image showing that there are no existing linting issues now:
=> Enabled Linting errcheck and fixed linting issues

docs/resources/spaces_bucket.md
Closes #1217 
Minor documentation update: add a default for digitalocean_spaces_bucket acl.
Source code: https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/digitalocean/spaces/resource_spaces_bucket.go#L60
=> [documentation]: add a default for digitalocean_spaces_bucket acl

.golangci.yml, digitalocean/database/resource_database_mysql_config.go, digitalocean/database/resource_database_postgres_config.go, digitalocean/database/resource_database_redis_config.go, digitalocean/domain/resource_record.go, digitalocean/droplet/resource_droplet.go
In #1237, a number of deprecated methods were update to allow for enabling additional staticchecks including usage of the deprecated `GetOkExists` method. Unfortunately, `GetOk` is not a drop in replacement. There is an important difference in its functionality.
> This is nearly the same function as `GetOk`, yet it does not check for the zero value of the attribute's type. This allows for attributes without a default, to fully check for a literal assignment, regardless of the zero-value for that type. This should only be used if absolutely required/needed.
https://pkg.go.dev/github.com/hashicorp/terraform/helper/schema#ResourceData.GetOkExists
Because of this change, Droplets can not currently be destroyed with main. It always timeouts waiting for the `locked` attribute to move to `false` …
=> Re-introduce d.GetOkExists usage.

digitalocean/droplet/datasource_droplet.go, digitalocean/droplet/datasource_droplet_test.go, digitalocean/droplet/datasource_droplets.go, digitalocean/droplet/datasource_droplets_test.go, digitalocean/droplet/droplets.go, digitalocean/droplet/resource_droplet_test.go, docs/data-sources/droplet.md, docs/data-sources/droplets.md, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/droplet_autoscale.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/monitoring.go, vendor/github.com/digitalocean/godo/sizes.go, vendor/modules.txt
This adds support for GPU Droplets to the `digitalocean_droplet` and `digitalocean_droplets` data sources.
```
$ DO_RUN_GPU_TESTS=1 make testacc TESTARGS='-run=TestAccDataSourceDigitalOceanDroplets'
=== RUN   TestAccDataSourceDigitalOceanDroplets_Basic
=== PAUSE TestAccDataSourceDigitalOceanDroplets_Basic
=== RUN   TestAccDataSourceDigitalOceanDroplets_GPUDroplet
=== PAUSE TestAccDataSourceDigitalOceanDroplets_GPUDroplet
=== CONT  TestAccDataSourceDigitalOceanDroplets_Basic
=== CONT  TestAccDataSourceDigitalOceanDroplets_GPUDroplet
--- PASS: TestAccDataSourceDigitalOceanDroplets_Basic (58.23s)
--- PASS: TestAccDataSourceDigitalOceanDroplets_GPUDroplet (92.15s)
PASS
ok      github.com/digitalocean/terraform-provider-digitalocean/digitalocean/droplet    92.248s
$ DO_RUN_GPU_TESTS=1 make …
```
=> Support GPU Droplets in Droplet data sources

docs/resources/loadbalancer.md
Now that GLB is GA, remove notes indicating some fields are part of a closed beta
=> LBAAS-3509: update loadbalancer field descriptions

docs/resources/database_redis_config.md
This PR adds information on which ports to use depending on `redis_ssl` value.
> When SSL is disabled, the cluster opens port 25060 for non-ssl connection while port 25061 still will be available for SSL connection. 
=> [databases]: update a description for redis_ssl in redis advanced config

digitalocean/droplet/resource_droplet.go, digitalocean/droplet/resource_droplet_test.go, docs/resources/droplet.md, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/droplet_actions.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/registry.go, vendor/github.com/digitalocean/godo/strings.go, vendor/modules.txt
This PR adds a support for Droplet backup policy.
=> [droplets]: add support for backup policy

digitalocean/database/resource_database_opensearch_config.go, digitalocean/database/resource_database_opensearch_config_test.go
As reported in https://github.com/digitalocean/terraform-provider-digitalocean/issues/1266, "creating" a `digitalocean_database_opensearch_config` without any setting leads to an error. This change protects against that by preventing sending the PATCH on create if no other values beside `cluster_id` are set.
Additionally, I ran into some issue running the acceptance test. One is a bug. We need to use `GetOkExists` when checking the value for a bool. If not, it is not correctly detected when being set to `false`.
There are also a few changes to the test that do not impact functionality which I will note inline.
=> opensearch_config: only send PATCH on create if values set.

docs/resources/droplet.md
We [recently discovered](https://github.com/jenkins-infra/digitalocean/pull/211#issuecomment-2485170603) that `user_data` is immutable for a given Droplet and changing its value forces a resource re-creation.
It is a different behavior than other Terraform providers (Azure does not care, AWS triggers instance reboot, etc.) so it is worth documenting it.
This PR updates the `user_data` description by adding the link to official DigitalOcean documentation and specifying that changing this attribute forces a new resource.
=> docs(droplet) details `user_data` behavior (resource forces recreate)

docs/resources/database_opensearch_config.md
The description for the `action_auto_create_index_enabled` argument appears to be a copy-paste error. Use a more correct description from: https://www.elastic.co/guide/en/elasticsearch/reference/current/index-management-settings.html
=> Fix docs for "digitalocean_database_opensearch_config"

digitalocean/database/resource_database_opensearch_config.go
This change makes it so that we only send attributes that have changes for Opensearch configurations. The one exception is for the ISM-related settings. The API seems to require that they are sent together, e.g.:
```
Error: Error updating Opensearch configuration: PATCH https://api.digitalocean.com/v2/databases/f3587545-9002-415b-9593-8473bc770a98/config: 422 (request "41520d54-cf5e-408d-ae19-e4fd45c310fa") invalid 'user_config': invalid input for opensearch: 'ism_history_enabled' is a required property
```
We may want to consider making similar changes for the other database engines. Though that is less pressing. The main motivator here is working around the bug triggered by sending `override_main_response_version`.
Fixes: https://github.com/digitalocean/terraform-provider-digitalocean/is …
=> opensearch_config: follow PATCH semantics

CONTRIBUTING.md
This PR updates the contributing documentation to improve the development process for both external contributors and internal DigitalOcean teams.
- Added a detailed section on how to test code changes locally.
- Reorganized content with subsections for better readability.
- Adjusted the order of acceptance test commands, moving the full suite section to the bottom to reduce the risk of accidentally running all tests.
- Highlighted that acceptance tests use real resources, emphasizing the potential costs and impact.
=> [documentation]: update contributing doc

digitalocean/loadbalancer/datasource_loadbalancer.go, digitalocean/loadbalancer/resource_loadbalancer.go, docs/resources/loadbalancer.md
Some small fixes for things we already support but have not been added to terraform:
- increase maximum lb size_unit to 200
- add regional_network type support
=> LBAAS: increase maximum lb size_unit, add regional_network type support

digitalocean/database/resource_database_cluster.go, digitalocean/kubernetes/resource_kubernetes_cluster.go, docs/resources/database_cluster.md
The docs did not really tell me how to use this field.
=> Add maintenance day validation for database and kubernetes clusters

digitalocean/app/app_spec.go, docs/data-sources/app.md, docs/resources/app.md
This adds support for Bitbucket as an app component source. It includes the docs from @dbrian57 in https://github.com/digitalocean/terraform-provider-digitalocean/pull/1303.
Note, like GitHub and GitLab, there are no acceptance tests. We only have ones using unauthenticated git clones so as to not require an account beyond a DigitalOcean one to run these tests.
=> apps: support Bitbucket as a source.

digitalocean/project/resource_project.go
When a project is gone from DO, a refresh fails because the project cannot be found. The code detects the 404 but still returns an error, so the refresh fails, instead of saving the updated state.
Here's a log (from Pulumi):
```
[2025-01-17 03:01:35]  ~  digitalocean:index:Project project refreshing (0s) error:   sdk-v2/provider2.go:457: sdk.helper_schema: Error reading Project: GET https://api.digitalocean.com/v2/projects/7242f1c8-65fb-46bd-93e2-63b263ddd15e: 404 (request "f81512c7-d34c-4c04-ab6b-aedbad9cead9") project not found: provider=digitalocean@4.32.0
```
After erasing the resource ID, the code falls through to the error, instead of returning `nil` (which is also the behavior of many other resources in the 404 case).
=> Project: return success after removing ID

digitalocean/kubernetes/kubernetes.go, digitalocean/kubernetes/resource_kubernetes_cluster.go, digitalocean/kubernetes/resource_kubernetes_cluster_test.go
This PR allows to configure https://docs.digitalocean.com/products/kubernetes/how-to/add-control-plane-firewall/
=> feat(kubernetes): add support to configure control plane firewall

digitalocean/loadbalancer/resource_loadbalancer.go, digitalocean/loadbalancer/resource_loadbalancer_test.go, docs/resources/loadbalancer.md, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/modules.txt
support loadbalancer network_stack
=> LBAAS-3600: support loadbalancer network_stack in terraform

digitalocean/kubernetes/kubernetes.go
`control_plane_firewall` is nullable. When attempting to flatten a k8s cluster without it set causes a panic. This can be seen running the acceptance tests, e.g.:
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanKubernetesCluster_Basic'
=== RUN   TestAccDigitalOceanKubernetesCluster_Basic
=== PAUSE TestAccDigitalOceanKubernetesCluster_Basic
=== CONT  TestAccDigitalOceanKubernetesCluster_Basic
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe2bcd9]
goroutine 271 [running]:
github.com/digitalocean/terraform-provider-digitalocean/digitalocean/kubernetes.flattenControlPlaneFirewallOpts(...)
/home/asb/projects/go/src/github.com/digitalocean/terraform-provider-digitalocean/digitalocean/kubernetes/kubernete …
```
=> kubernetes: protect against panic in flattenControlPlaneFirewallOpts

digitalocean/kubernetes/datasource_kubernetes_cluster.go, digitalocean/kubernetes/resource_kubernetes_cluster.go
fixes https://github.com/digitalocean/terraform-provider-digitalocean/issues/1318
=> [kubernetes]: fixing issues related to some missing fields in config

digitalocean/kubernetes/datasource_kubernetes_cluster.go, digitalocean/kubernetes/datasource_kubernetes_cluster_test.go, digitalocean/kubernetes/kubernetes.go, digitalocean/kubernetes/resource_kubernetes_cluster.go, digitalocean/kubernetes/resource_kubernetes_cluster_test.go
This PR adds the `ClusterAutoscalerConfiguration` with the `scale_down_utilization_threshold` and the `scale_down_unneeded_time` fields.
=> kubernetes: add cluster autoscaler configuration fields

vendor/github.com/google/go-cmp/cmp/report_slices.go, vendor/github.com/hashicorp/terraform-exec/tfexec/options.go, vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_importer.go
Minor typo fixes in comments.
Changed files:
- vendor/github.com/google/go-cmp/cmp/report_slices.go
- vendor/github.com/hashicorp/terraform-exec/tfexec/options.go
- vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_importer.go
This change does not include functional changes.
=> Fix typo in code comment

.github/release.yml, CHANGELOG.md, CONTRIBUTING.md
This change generates automatic notes on github release.
=> Add automatically generated github release notes

docs/resources/droplet.md
Adds a link to the API docs for finding image IDs. Also updates an existing link to the new URL format.
Fixes: #1334
=> docs: link to API docs for finding image IDs.

docs/resources/app.md, docs/resources/custom_image.md, docs/resources/database_cluster.md, docs/resources/database_kafka_config.md, docs/resources/database_mongodb_config.md, docs/resources/database_mysql_config.md, docs/resources/database_opensearch_config.md, docs/resources/database_postgresql_config.md, docs/resources/database_redis_config.md, docs/resources/droplet.md, docs/resources/monitor_alert.md, docs/resources/record.md, docs/resources/uptime_alert.md, docs/resources/uptime_check.md, docs/resources/vpc.md
Working on https://github.com/digitalocean/terraform-provider-digitalocean/pull/1336, I realized there are more broken API reference links. :disappointed:  
It looks like there is a redirect in place, but it does not retain the URL fragment. For example:
`https://docs.digitalocean.com/reference/api/api-reference/#tag/VPCs` redirects to `https://docs.digitalocean.com/reference/api/digitalocean/` rather than `https://docs.digitalocean.com/reference/api/digitalocean/#tag/VPCs`
=> docs: update links to API reference

digitalocean/loadbalancer/datasource_loadbalancer.go, digitalocean/loadbalancer/datasource_loadbalancer_test.go, digitalocean/loadbalancer/import_loadbalancer_test.go, digitalocean/loadbalancer/loadbalancer.go, digitalocean/loadbalancer/resource_loadbalancer.go, digitalocean/loadbalancer/resource_loadbalancer_test.go
This fixes importing global load balancers. We were not setting the GLB related attributes in the read method, so they were not set on import. This required setting the `type` attribute to `Computed`. There are also some related test fix ups as well as a new test for importing GLBs. Finally, I cleaned up some of the error messages (No need to preface them with `[DEBUG]`).
Fixes: #1338
=> load balancers: fix importing global LBs

digitalocean/kubernetes/datasource_kubernetes_cluster.go, digitalocean/kubernetes/datasource_kubernetes_cluster_test.go, digitalocean/kubernetes/kubernetes.go, digitalocean/kubernetes/resource_kubernetes_cluster.go, digitalocean/kubernetes/resource_kubernetes_cluster_test.go
Tested manually:
Acceptance tests:
```
=== NAME  TestAccDataSourceDigitalOceanKubernetesCluster_Basic
datasource_kubernetes_cluster_test.go:26: TestCase error running init: exit status 1
Error: Incompatible provider version
Provider registry.terraform.io/hashicorp/kubernetes v1.13.2 does not have a
package available for your current platform, darwin_arm64.
Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider
may have different platforms supported.
```
=> add routing_agent option to kubernetes cluster

digitalocean/kubernetes/kubernetes.go, digitalocean/kubernetes/resource_kubernetes_node_pool_test.go, docs/resources/kubernetes_cluster.md
This feature is in private preview and not available for public use. Will add another PR for more guardrails such asvalidating node count for a cluster is greater than 1 before allowing a min_nodes=0
```
Running tool: /opt/homebrew/bin/go test -timeout 30s -run ^TestAccDigitalOceanKubernetesNodePool_MinNodesZero$ github.com/digitalocean/terraform-provider-digitalocean/digitalocean/kubernetes
ok  	github.com/digitalocean/terraform-provider-digitalocean/digitalocean/kubernetes	0.662s
```
=> Kubernetes: Add support for autoscaling to zero

digitalocean/database/resource_database_cluster.go, digitalocean/database/resource_database_cluster_test.go, docs/resources/database_cluster.md
This treats `valkey` like `redis` in the `digitalocean_database_cluster` resource. It updates the validation for using `eviction_policy` and the `DiffSuppressFunc` that deals with the forced version upgrades to both work with Valkey as well.
There is still additional work to be done around Valkey support:
- Addition of a Valkey advanced configuration resource (`digitalocean_database_valkey_config`)
- Handle the path for converting existing Redis instances to Valkey
Those can come at a later date. This will unblock basic use cases.
Fixes: #1362
=> dbaas: initial valkey support

digitalocean/kubernetes/datasource_kubernetes_cluster_test.go, digitalocean/kubernetes/kubernetes.go
This PR has a fix for [Issue-1364](https://github.com/digitalocean/terraform-provider-digitalocean/issues/1364).
```
terraform-provider-digitalocean % TF_ACC=1 go test -v -run TestAccDataSourceDigitalOceanKubernetesCluster_NodeCountZero ./digitalocean/kubernetes
=== RUN   TestAccDataSourceDigitalOceanKubernetesCluster_NodeCountZero
=== PAUSE TestAccDataSourceDigitalOceanKubernetesCluster_NodeCountZero
=== CONT  TestAccDataSourceDigitalOceanKubernetesCluster_NodeCountZero
--- PASS: TestAccDataSourceDigitalOceanKubernetesCluster_NodeCountZero (115.33s)
PASS
ok      github.com/digitalocean/terraform-provider-digitalocean/digitalocean/kubernetes 115.967s
```
=> Issue-1364:- Allow node count to be zero

digitalocean/provider.go, digitalocean/spaces/import_spaces_bucket_logging_test.go, digitalocean/spaces/resource_spaces_bucket_logging.go, digitalocean/spaces/resource_spaces_bucket_logging_test.go, docs/resources/spaces_bucket.md, docs/resources/spaces_bucket_cors_configuration.md, docs/resources/spaces_bucket_logging.md, docs/resources/spaces_bucket_object.md, docs/resources/spaces_bucket_policy.md
https://docs.digitalocean.com/products/spaces/how-to/access-logs/
```
$ make testacc TESTARGS='-run=TestAccDigitalOceanSpacesBucketLogging -count=1'
=== RUN   TestAccDigitalOceanSpacesBucketLogging_importBasic
=== PAUSE TestAccDigitalOceanSpacesBucketLogging_importBasic
=== RUN   TestAccDigitalOceanSpacesBucketLogging_basic
=== PAUSE TestAccDigitalOceanSpacesBucketLogging_basic
=== RUN   TestAccDigitalOceanSpacesBucketLogging_update
=== PAUSE TestAccDigitalOceanSpacesBucketLogging_update
=== CONT  TestAccDigitalOceanSpacesBucketLogging_importBasic
=== CONT  TestAccDigitalOceanSpacesBucketLogging_update
--- PASS: TestAccDigitalOceanSpacesBucketLogging_update (14.46s)
=== CONT  TestAccDigitalOceanSpacesBucketLogging_basic
--- PASS: TestAccDigitalOceanSpacesBucketLogging_importBasic (15.36s) …
```
=> spaces: add support for bucket logging

digitalocean/loadbalancer/resource_loadbalancer.go, docs/resources/loadbalancer.md
certificate_id is a read only attribute on the GLB domains. As such we should only be setting it on the datasources call to flatten domains as it doesnt exist in the resources schema.
=> GLB fix domains certificate id/name on loadbalancers_resources

docs/data-sources/app.md
Clarifies that customers need to provide App Platform access to their repository account.
=> Update App docs to mention repository access

digitalocean/app/app_spec.go, docs/resources/app.md
This PR adds a new alert for autoscale succeeded to app platform.
This PR depends on https://github.com/digitalocean/godo/pull/879 being merged.
=> App Platform: Add autoscale alert rules to appSpec and documentation

digitalocean/database/datasource_database_cluster.go, digitalocean/database/datasource_database_cluster_test.go, digitalocean/database/datasource_database_metrics_credentials.go, digitalocean/database/datasource_database_metrics_credentials_test.go, digitalocean/database/resource_database_cluster.go, digitalocean/database/resource_database_cluster_test.go, digitalocean/provider.go, docs/data-sources/database_cluster.md, docs/data-sources/database_metrics_credentials.md, docs/resources/database_cluster.md, examples/database/README.md, examples/database/main.tf, examples/database/outputs.tf, examples/database/variables.tf
This PR adds support for retrieving database related details via Terrafrom. This is done by:
* Adding a `metrics_endpoints` attributre to the `digitalocean_database_cluster` resource and datasource
* Added a new `digitalocean_database_metrics_credentials` datasource 
* Added/Update docs to reflect changes
* database example including new attributes and datasources
These changes allow users to create database clusters and then generate the configurations need to monitor those database via Prometheus or other monitoring systems.
* plan and apply with new database example
* Ran acceptance tests:
* `TestAccDigitalOceanDatabaseCluster_Basic`
* `TestAccDataSourceDigitalOceanDatabaseCluster_Basic`
* `TestAccDataSourceDigitalOceanDatabaseMetricsCredentials`
=> Add database metrics attributes and datasources

docs/data-sources/vpc_peering.md, docs/resources/vpc_peering.md
This pull request makes a small documentation update to the VPC Peering data source. The change removes a note about the alpha status of VPC peering, reflecting that the feature is now [generally available](https://www.digitalocean.com/blog/vpc-peering-ga).
=> docs(digitalocean_vpc_peering): VPC Peering is GA

digitalocean/vpcnatgateway/resource_vpc_nat_gateway.go
Enforce dependency between NAT gateway and VPC in the resources schema: we currently don't support updating the vpc in place for existing gateways (also don't support add/removing ingresses) so we'll need to force new creates (teardown and replace) any existing gateways if their ingresses are tied to a vpc which is also being replaced.
=> Force replace nat gateway with vpc update
